### ISSUE TITLE
How does Fractal submit slurm jobs from the correct user?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#10]
Now that the server setup is progressing and different users can submit jobs: How do we make sure that Fractal submits jobs from the correct user?

The correct user needs to be selected, because read & write rights on our servers are user specific (on the Pelkmans side: broad read rights, but write rights limited to the personal drive). Also important on the FMI side for accounting on who uses the cluster.

As discussed with @tcompa today, the SlurmProvider does take an account string. But can we just set that to the correct user? How is this authenticated? (see here: https://parsl.readthedocs.io/en/stable/stubs/parsl.providers.SlurmProvider.html) Can we have a generic Fractal server to which users authenticate or do there need to be user-specific servers running?

**Comment by tcompa** [comment]
Feedback from @benclifford (on parsl slack channel):
We could put `sudo -u $CORRECT_USER` in front of all SLURM commands (after adding the appropriate permissions to a `fractal` user).
My guess is this would happen for instance in https://github.com/Parsl/parsl/blob/master/parsl/launchers/launchers.py#L333.

Such a solution at least mitigates our issue, as we wouldn't have to run the whole server as `sudo`. And the user's code would be executed as their own user.

**Comment by jluethi** [comment]
> We could put sudo -u $CORRECT_USER in front of all SLURM commands (after adding the appropriate permissions to a fractal user).

This sounds like a really good approach and is also my understanding of what Enrico suggested (sorry if I wasn't able to convey that). If we can have this in front of the slurm srun command as you describe, that would limit the scope of sudo being used and put the srun or sbatch job as the correct user (=> correct file permissions).

**Comment by mfranzon** [comment]
Here the possible fix to give an user the permission to impersonate another user without giving him the sudo power. 
(Already implemented for fractal user on the Pelkmans cluster)

```
# /etc/sudoers
[...]
fractal  ALL=(!root)/bin/su$
fractal  ALL=(root)/bin/su - [a-zA-Z][a-z0-9A-Z]*
fractal  ALL=(!root)/bin/su -
fractal  ALL=(!root)/bin/su - root
[...]
```

**Comment by mfranzon** [comment]
Update on the rules to impersonate another user. Now from fractal user you can just use sbatch and srun command.
```
# /etc/sudoers
fractal  ALL=(!root)/bin/su$
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c whoami # just for debug
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c sbatch [A-Za-z0-9_*/.]*
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c srun [A-Za-z0-9_*/.]*
fractal  ALL=(!root)/bin/su -
fractal  ALL=(!root)/bin/su - root

**Comment by tcompa** [comment]
Brief comment just to say that https://github.com/fractal-analytics-platform/fractal-server/pull/112 is progressing. By running the server as a special user `fractal`, this user can submit SLURM jobs as any other user. Several smaller points are to be refined (see https://github.com/fractal-analytics-platform/fractal-server/pull/112#issuecomment-1271327215) but we have a first working version.
This will make room to several important architecture updates, mainly about which environment is used to run a task, which tasks are known to the server,  and how can a user play with these parameters. Several issues/PRs will appear next week, and we expect the architecture to be non-backwards-compatible soon enough. We can then rediscuss all of this on Wednesday.

**Comment by mfranzon** [comment]
Last version of the sudoer rules for the fractal user.
Thanks to these, fractal can impersonate any user BUT it can run ONLY 
- `sbatch`,
- `scancel`, 
- `squeue`,
with arguments.

```bash
fractal  ALL=(!root)/bin/su$
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c sbatch [A-Za-z0-9_*-/.]*
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c scancel [A-Za-z0-9_*-/.]*
fractal  ALL=(root) NOPASSWD:/bin/su - [a-zA-Z][a-z0-9A-Z]* -c squeue [A-Za-z0-9_*-/.]*
fractal  ALL=(!root)/bin/su -
fractal  ALL=(!root)/bin/su - root
```

**Comment by gusqgm** [comment]
Thank you for the the rules list @mfranzon !
I crossed-checked with FMI sysadmin and first feedback I got was
that with the last line 

`fractal  ALL=(!root)/bin/su - root`

fractal could potentially become root which was seen as a security issue. Isthere a reason for this particular rule? 

After revising the way the rules were written, we now have a shorter version for them:

`Runas_Alias FRACTAL_USERS = fractal, %group_name
Cmnd_Alias FRACTAL_CMD = /bin/sbatch, /bin/scancel
fractal ALL=(FRACTAL_USERS) NOPASSWD:FRACTAL_CMD`

'squeue' is not added here with the idea that is does not require sudo in the first place and can be run by the fractal user, with the possibility to query other user's job status.



In any case, we now have a fractal user added to our SLURM test machine along with the rules stated here above.

**Comment by mfranzon** [comment]
Hi @gusqgm! 
Thank you for the feedback, the line regarding the root user: 

`fractal ALL=(!root)/bin/su - root`

was a rule to prevent fractal user to become root, but now it can be deprecated due to the fact that we give the permissions just to `sbatch` and `scancel`. 
I have update the rules in order to be aligned with yours.

**Comment by enricotagliavini** [comment]
> Hi @gusqgm! Thank you for the feedback, the line regarding the root user:
> 
> `fractal ALL=(!root)/bin/su - root`
> 
> was a rule to prevent fractal user to become root, but now it can be deprecated due to the fact that we give the permissions just to `sbatch` and `scancel`. I have update the rules in order to be aligned with yours.

You could become any other user, including some that might have elevated privileges. Also please note that we can allow more commands than just

```
Cmnd_Alias FRACTAL_CMD = /bin/sbatch, /bin/scancel
```
as sbatch will anyway allow arbitrary command execution, so limiting the command to sbatch only doesn't add much security.

**Comment by enricotagliavini** [comment]
> Thank you for the the rules list @mfranzon ! I crossed-checked with FMI sysadmin and first feedback I got was that with the last line
> 
> `fractal ALL=(!root)/bin/su - root`
> 
> fractal could potentially become root which was seen as a security issue. Isthere a reason for this particular rule?
> 
> After revising the way the rules were written, we now have a shorter version for them:
> 
> Runas_Alias FRACTAL_USERS = fractal
> 
> Cmnd_Alias FRACTAL_CMD = /bin/sbatch, /bin/scancel
> 
> fractal ALL=(FRACTAL_USERS) NOPASSWD:FRACTAL_CMD
> 
> 'squeue' is not added here with the idea that is does not require sudo in the first place and can be run by the fractal user, with the possibility to query other user's job status.
> 
> In any case, we now have a fractal user added to our SLURM test machine along with the rules stated here above.

This should be clarified: the FRACTAL_USER variable is actually a list of users that fractal is allowed to impersonate. With the above ruleset fractal is not able to run sbatch as any other user. This is what we are using in our testing environment, I also renamed the variable definition to make it clearer
```
Runas_Alias FRACTAL_IMPERSONATE_USERS = fractal, %usergroup, potenally, other, single, users
Cmnd_Alias FRACTAL_CMD = /bin/sbatch, /bin/scancel
fractal ALL=(FRACTAL_IMPERSONATE_USERS) NOPASSWD:FRACTAL_CMD
``` 

We explicitly list and allow all the users that might want to use fractal and that fractal is allowed to impersonate. Group members can be added as well with the %usergroup option, where `usergroup` is the UNIX / Linux user group name
