### ISSUE TITLE
Make all list relationships ordered

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1062]
As in https://github.com/fractal-analytics-platform/fractal-server/pull/951/files

The default should be by ID, but in some cases we may want to use name.
For instance let's order `project.dataset_list` alphabetically (https://github.com/fractal-analytics-platform/fractal-web/issues/351).

**Comment by jluethi** [comment]
And other lists should be ordered by criteria like creation date, see https://github.com/fractal-analytics-platform/fractal-web/issues/339

**Comment by tcompa** [comment]
> And other lists should be ordered by criteria like creation date, see https://github.com/fractal-analytics-platform/fractal-web/issues/339

At a difference with ID-based or name-based ordering, this has to be done in a different way. I'll open a different issue.

**Comment by tcompa** [comment]
Note: as of #1082, some endpoints use custom queries rather than these relationships - which would require additional sorting.

**Comment by tcompa** [comment]
Closing as of https://github.com/fractal-analytics-platform/fractal-server/pull/1071#issuecomment-1860630953.
