### ISSUE TITLE
Add `project.timestamp_created` column 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1068]
The main reason for this change is to be able to sort the project list of a user (that is, `UserOAuth.project_list`) by this new attribute.
Refs:
* https://github.com/fractal-analytics-platform/fractal-server/issues/1062
* https://github.com/fractal-analytics-platform/fractal-web/issues/339

The new attributed should be filled upon project creation (in the corresponding `POST` endpoint), and it should not be editable.

---

This approach won't work by default for projects that already exist, and we will need to prepare the corresponding fix-db script (similar to https://github.com/fractal-analytics-platform/fractal-server/pull/1058).

To be defined: how to assign timestamps to existing projects without knowing their creation time?
Some options:
1. Create fake timestamps which are sorted as the project IDs. This will work reasonably well if there have not been too many project deletions, but it may lead to inconsistencies if some projects were deleted and then their ID were re-assigned.
2. Create fake timestamps based on the jobs in the projects (that is, take the earliest job submission time and use it as a project creation time). This would be more accurate, but we it will be inconsistent for projects which have no jobs (and in that case we have to set a default).
3. A mix of the previous two points -> I tried to come up with a reasonable one, but it seems too complex IMO.

My preference would be to go with 2. All projects with jobs would come up sorted correctly, and all projects with no jobs (which are likely the least interesting ones) would be assigned a fake timestamp like 2023-06-01-00:00:00 and end up in the end of the list.

**Comment by tcompa** [comment]
Side comment: because this is a non-trivial change, let's decide early if it needs to also take place for other tables (e.g. datasets, workflows, tasks).

**Comment by jluethi** [comment]
> Create fake timestamps based on the jobs in the projects (that is, take the earliest job submission time and use it as a project creation time). This would be more accurate, but we it will be inconsistent for projects which have no jobs (and in that case we have to set a default).

This option 2 sounds good to me.

If we can also do it for datasets & workflows, that could come in useful down the road.
I'm not sure how relevant it is for tasks, but could potentially be useful to know if a task was added this months or 12 months ago (e.g. if we do breaking changes to Fractal server that would change the task interface, we'd have a way to check which tasks are likely to give us issues)
