### ISSUE TITLE
Check that `status` endpoint can return `running`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1072]
For endpoint `GET /api/v1/project/{project_id}/dataset/{dataset_id}/status`

> Moreover I'm never receiving the running status. Jobs remain in submitted status for a while, then go directly to done or failed.

Ref https://github.com/fractal-analytics-platform/fractal-web/pull/363#issuecomment-1840559238

**Comment by tcompa** [comment]
> My concept for (at least the slurm runner) was that we can't differentiate between a job that has been submitted to slurm and one that actually starts running.

This is 100% true. We currently have no visibility in whether the SLURM job is queued or running.

**Comment by tcompa** [comment]
After double-checking (see below), I take back my original remark, and I'm closing this issue.

Let's re-open (this one or a different one) when we want to introduce a new feature that also queries SLURM to know the status of the _SLURM_ jobs (reminder: there may be multiple jobs per task, with a number that is not directly matching the number of parallel components).

---

I was mixing up two of our `Enum`s, as shown below. The job-status one has a finer distinction between submitted and running, but the time that passes between job creation in the DB (with submitted status) and setting its status to running is a very small interval (unrelated to SLURM). To rephrase it: we almost never have jobs in the "submitted" status. For this reason, there is no such granularity in the workflowtask status: submitted essentially corresponds to running (which is _not_ the same as "currently running on SLURM", to be clear).

```python
class JobStatusType(str, Enum):
    """
    Define the available job statuses

    Attributes:
        SUBMITTED:
            The workflow has been applied but not yet scheduled with an
            executor. In this phase, due diligence takes place, such as
            creating working directory, assemblying arguments, etc.
        RUNNING:
            The workflow was scheduled with an executor. Note that it might not
            yet be running within the executor, e.g., jobs could still be
            pending within a SLURM executor.
        DONE:
            The workflow was applied successfully
        FAILED:
            The workflow terminated with an error.
    """

    SUBMITTED = "submitted"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
```

```python

class WorkflowTaskStatusType(str, Enum):
    """
    Define the available values for the status of a `WorkflowTask`.

    This model is used within the `Dataset.history` attribute, which is
    constructed in the runner and then used in the API (e.g. in the
    `api/v1/project/{project_id}/dataset/{dataset_id}/status` endpoint).

    Attributes:
        SUBMITTED: The `WorkflowTask` is part of a running job.
        DONE: The most-recent execution of this `WorkflowTask` was successful.
        FAILED: The most-recent execution of this `WorkflowTask` failed.
    """

    SUBMITTED = "submitted"
    DONE = "done"
    FAILED = "failed"
```

**Comment by jluethi** [comment]
In this part:

```
        SUBMITTED:
            The workflow has been applied but not yet scheduled with an
            executor. In this phase, due diligence takes place, such as
            creating working directory, assemblying arguments, etc.
        RUNNING:
            The workflow was scheduled with an executor. Note that it might not
            yet be running within the executor, e.g., jobs could still be
            pending within a SLURM executor.
```

I think it's somewhat misleading to call it RUNNING if it may be scheduled with slurm, but not actually running. And the differentiation on whether it has gone through our due diligence isn't very valuable to a typical user.
