### ISSUE TITLE
Write history file in each dataset

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#108]
Let's start to store a simple history file in each dataset. The first version will just be a printout of the whole dataset attributes (including the `history` entry in the metadata), then we can decide what kind of information should be there.

Clarification: the main goal of this file is to keep track of all processing that lead to the current data. At the moment this does **not** correspond to a re-runnable "pipeline" file (see #1 for that feature).

**Comment by jluethi** [comment]
Sounds good. Let's keep this simple and check whether our exported "pipeline" from #1 could also take over this purpose eventually, combining both the history and rerun function. But that will probably get trickier to implement (i.e. what if we run multiple pipelines on the same project => history useful, certainly to get this started).

**Comment by tcompa** [comment]
Closing as obsolete.
As of #803, the history now does offer a way to export a re-runnable workflow. And its storage, server-side, is perfectly fine in the DB. As per the ome-zarr side of history, see e.g. #508 .
