### ISSUE TITLE
Should non-admin user own the tasks they collect?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1084]
As reported in https://github.com/fractal-analytics-platform/fractal-tasks-template/issues/2 by @adrtsc:
> Also, when tasks are collected from a package, the user that imported them is not the owner of the task, meaning that they can't be edited (and therefore I can't add a meta-file via the fractal client).

I agree that this is suboptimal: the user collects tasks (possibly based on a local in-progress wheel package), but then cannot change/delete them any more.

The rationale here was that we want _some_ tasks (e.g. the `fractal-tasks-core` ones) to be marked as "common" (via the `owner=null` property), and to curb complexity our current choice is to only have two kinds of tasks:
1. Those coming from task collection -> common
2. Those added by users (one by one) -> user-owned

---

As we encourage users to turn their tasks into packages, maybe we can review this choice. My suggestion would then be:
1. Tasks collected by a superuser have `owner=null` (if an admin wants to play with their own tasks, they should use a different account from the superuser one)
2. Tasks collected by a standard user are owned by the user triggering the collection.
3. Tasks added one-by-one are always owned by the user (as it is now).

Note: I'm suggesting that we take a default decision based on whether the user is a superuser just in order to avoid yet another option in the task-collection prompt, but we can obviously make this flexible.

The only downside I can think of is that user-owned tasks can be edited, even if they come from a package. In this sense, they are not any more guaranteed to be portable. That is, a given source points to a task that the user may have modified after collection, and therefore it's unclear what that task contains. In principle I'm OK with giving up full portability for user's tasks, but let's be aware of this consequence if we make changes to task-collection.

**Comment by jluethi** [comment]
Thanks for writing this up Tommaso.

> The only downside I can think of is that user-owned tasks can be edited, even if they come from a package. In this sense, they are not any more guaranteed to be portable. That is, a given source points to a task that the user may have modified after collection, and therefore it's unclear what that task contains. In principle I'm OK with giving up full portability for user's tasks, but let's be aware of this consequence if we make changes to task-collection.

I'm a bit hesitant to give up on this portability. It could open up a big reproducibility issue in the future. Thus, changing the actual task function should require a new version being collected, if we are talking about packages.

But changing the meta parameters is something that I see as less drastic. That's setting a default that the user can change, not potentially changing which executable is run.

------

It could still be useful to have a task associated to a user of course, so only that user (and admins) can make small adjustments.

One idea from that: Can users currently change the task executable for their task? If no, all good. If yes, we could make this a superuser only function (also for single tasks) and then follow your logic above. And if someone wants to change the executable, they add a new version of the task

**Comment by tcompa** [comment]
Superseded by https://github.com/fractal-analytics-platform/fractal-server/issues/1736. Closing.
