### ISSUE TITLE
Establish some first API response-times benchmarks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1089]
Together with optimization of fractal-web (see e.g. https://github.com/fractal-analytics-platform/fractal-web/issues/361), we may want to verify the API response times in some scaling scenarios (with a large number of jobs/projects/users/...).

This is currently done in a non-systematic way, e.g., in
* https://github.com/fractal-analytics-platform/fractal-server/issues/1088
* https://github.com/fractal-analytics-platform/fractal-server/pull/1082#issuecomment-1856676097

but we could set it up some in a more systematical way.

Since the scope here could easily grow a lot, the first two specific goals would be:
1. Set up some benchmark tool (the simplest we find - it can also be fully custom)
2. Test only the few cases for which we already have some reports of slow responses (https://github.com/fractal-analytics-platform/fractal-web/issues/361), starting with GET-ting jobs for a user with many of them.

**Comment by zonia3000** [comment]
As per https://github.com/fractal-analytics-platform/fractal-web/issues/361#issuecomment-1857593865, the `/api/v1/dataset/` takes some time and returns a quite big payload, so maybe something can be optimized here. However notice that, after the refactoring of the project page mentioned in the comment, this endpoint will not be needed by fractal-web anymore.

**Comment by tcompa** [comment]
> As per [fractal-analytics-platform/fractal-web#361 (comment)](https://github.com/fractal-analytics-platform/fractal-web/issues/361#issuecomment-1857593865), the `/api/v1/dataset/` takes some time and returns a quite big payload, so maybe something can be optimized here. However notice that, after the refactoring of the project page mentioned in the comment, this endpoint will not be needed by fractal-web anymore.

Thanks!
For the record, this endpoint is now being modified as part of `1.4.1a1`. This is not necessarily an optimization, but it could affect its response time.

Would it be possible to repeat the profiling with this more recent version?

**Comment by zonia3000** [comment]
I'm not able to run the migration due to the following error:

```
NotNullViolationError: column "workflow_dump" of relation "applyworkflow" contains null values
```
Do we have some scripts to fix the values in the database?

**Comment by tcompa** [comment]
For the moment you can run the two scripts in https://github.com/fractal-analytics-platform/fractal-server/tree/main/scripts/database_updates/from_1.3_to_1.4 by hand:

```
# From an environment where fractal-server is >= 1.4.0, and
# from a folder where you have the correct .fractal_server.env
python fix_db.py
python fix_db_add_user_email.py
```

(I still need to update the DB dump in `tests/data`..)

**Comment by zonia3000** [comment]
Response payload size is much smaller (1.3 MB -> 44K) and response time is faster (230ms -> 140 ms).

**Comment by tcompa** [comment]
Here's the proposal for a minimal working setup:

1. Start from fractal-containers, and copy the postgres and fractal-server containers.
2. Adapt the fractal-server container so that it uses local code base, rather than pulling it from elsewhere (github or PyPI).
3. Adapt the postgres container so that it loads one or more databases from file.
4. Run bash a script (ideally from within the fractal-server container) which
    * makes a `GET /auth/current-user/` call and the appropriate authorization header for subsequent calls;
    * makes N `curl` calls to each one of the endpoints in a given list (let's start with a bunch of `GET` ones), and logs their timing to standard output or to a file
5. Turn this procedure in a github action
6. Make the github action loop over two possible database input files (a very lightweight one, and one where the user has many projects with many jobs and so on).

This procedure can produce a decently-reproducible benchmark (when running on the same machine, or in similar environment) for any given point in the git history.

What is missing (with respect to some existing benchmarking framework) is:
* Persistence of previous logs (we could use github artifacts, but they are not really dev-friendly for use and especially for long-term storage)
* Automatic comparison of different performance at two points in git history, e.g. in the same form of the coverage-update comment we have in PRs.


----

Another option: we use pytest-benchmark (note: this would be independent on our current pytest use, with a set of benchmarks defined in `benchmarks`, and not in `tests`), and https://github.com/openpgpjs/github-action-pull-request-benchmark. This covers the missing point above, but it's unclear to me who would be responsible for running fractal-server (especially if we want the benchmark to make actual http calls, rather than connecting directly to a fastapi app as I think we currently do in tests). One option here is to provide the same docker containers as above, as requirements to the part of the action which then runs `pytest-benchmark`.


---

There are plenty of other tools (see e.g. https://www.libhunt.com/l/python/topic/benchmarking, including e.g. [locust](https://github.com/locustio/locust)), but for the moment I'd rather try out one of the "simple" solutions.

---

To be explored.

**Comment by tcompa** [comment]
First prototype is now there, as of #1123, and available at https://htmlpreview.github.io/?https://github.com/fractal-analytics-platform/fractal-server/blob/benchmark-api/benchmarks/bench.html. This issue is then closed - see https://github.com/fractal-analytics-platform/fractal-server/issues/1132 for follow-ups.
