### ISSUE TITLE
Review location of fix-db scripts

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1094]
After the 1.3->1.4.0 version update, we ran some fix-db scripts from the `scripts/database_updates/from_1.3_to_1.4` folder.
As of #1070 (and in future PR related to #1068), we'll have one or two more such scripts.

Having them in an arbitrary `scripts` folder is not great for usability, not for reliability. I propose that, together with #1073, we also test the scripts from the migrations github action.

A plan could be:
1. Move the scripts within an appropriate subfolder of the package (e.g. `fractal_server/fix_db_scripts`).
2. Turn the scripts into functions.
3. Make the functions version-aware. This could be done in multiple ways, and an example is that a given function would first check that the version matches a certain regex (e.g the script introduced in #1070 should be only applied if version is `>=1.4.2`, and we may even want to require that it is strictly equal to 1.4.2 - up to alpha prereleases).
4. Expose the appropriate function via the `fractalctl` CLI. An example procedure would be:
    * `pip install fractal-server==1.4.2`
    * `fractalctl set-db`
    * `fractalctl fix-db 1.4.2` -> this runs the appropriate function
    * `fractalctl start`
5. Add the same procedure (`set-db` and then `fix-db` to `migrations.yml` test). This obviously requires keeping an up-to-date test DB, as in #1073).

I think that with this versioning approach we could even avoid keeping track of old scripts, and only keep the one needed for the last transition (to be verified). If possible, that'd be preferable, so that we don't have obsolete/untested code in the package and repo.

**Comment by tcompa** [comment]
Here is an example of why this issue matters:

The current script has a tiny bug:
```diff
diff --git a/scripts/database_updates/from_1.4.1_to_1.4.2/fix_db_add_project_dump.py b/scripts/database_updates/from_1.4.1_to_1.4.2/fix_db_add_project_dump.py
index 59a458d8..5b363456 100644
--- a/scripts/database_updates/from_1.4.1_to_1.4.2/fix_db_add_project_dump.py
+++ b/scripts/database_updates/from_1.4.1_to_1.4.2/fix_db_add_project_dump.py
@@ -39,7 +39,7 @@ with next(get_sync_db()) as db:
             logging.warning(
                 f"Handling job with ID {row.id:4d}, setting {project_dump=}"
             )
-            ProjectDump(project_dump)
+            ProjectDump(**project_dump)
             row.project_dump = project_dump
             db.add(row)
             db.commit()
```
which is hard to detect without actual tests.

**Comment by tcompa** [comment]
Some more exploration of how this could work - with @ychiucco 

Let's say that a `fix_db_1_4_3.py` (or the equivalent function) exists, somewhere in the package, and is exposed through `fractalctl fix-db` (or a similar command, with arguments TBD). This update sets the correct values of the `ApplyWorkflow.project_dump` column. As of 1.4.4, this fix must have been run - or the API will start failing in response validation.

Sequential 1.4.2->1.4.3 and 1.4.3->1.4.4 updates of fractal-server work fine:
```
pip install fractal-server==1.4.2
fractalctl set-db
fractalctl fix-db (SOME MORE ARGS)   #  --> this calls `fix_db_1_4_3.py`

pip install fractal-server==1.4.3
fractalctl set-db

fractalctl start
```

Direct 1.4.2->1.4.4 updates of fractal-server is not OK:
```
pip install fractal-server==1.4.4
fractalctl set-db
fractalctl start
# -> some response-validation errors
```


TBD

**Comment by tcompa** [comment]
For the record, what we are doing here ("data migration", as opposed to "schema/database migration") is considered as out-of-scope in alembic, and the typical recommendations is to do it somewhat like we are currently doing it:
* https://alembic.sqlalchemy.org/en/latest/cookbook.html#data-migrations-general-techniques
* https://github.com/sqlalchemy/alembic/discussions/972#discussioncomment-1766394
* https://github.com/sqlalchemy/alembic/discussions/972#discussioncomment-2820869

Example quotes:
>  it’s not in fact advisable in the general case to write data migrations that integrate with Alembic’s schema versioning model.
> (https://alembic.sqlalchemy.org/en/latest/cookbook.html#data-migrations-general-techniques)

> That is, the data migration was handled in a way that took advantage of the application business logic at the current version rather than trying to weld itself into alembic migrations, and consisted of scripts in a different directory that were run based on particular application versions
> (by sqlalchemy maintainer, https://github.com/sqlalchemy/alembic/discussions/972#discussioncomment-1766394)

---

Given this context, it's probably best to invest on the current issue (making it easy to run the correct script), rather than on including data migration within alembic schema migrations.

**Comment by tcompa** [comment]
Here is our next option for how a version upgrade (that includes both schema and data migrations) could work, based on discussions with @mfranzon.

```
# CURRENT
pip install fractal-server[postgres]==1.4.2
fractalctl set-db
wget some-script-from-github.com
python current.py

# FUTURE
pip install fractal-server[postgres]==1.4.2
fractalctl set-db
fractalctl update-db-data
```

Where the `update-db-data` interactively asks for a bunch of confirmations, e.g.
1. Please make a backup of current DB (hint: `psql ...`)
2. Confirm that you already ran `fractalctl set-db` with the new version
3. Confirm that you are not skipping a version (e.g going from 1.4.0 to 1.4.2)
4. Confirm that the current version is 1.4.2, by typing "1.4.2"
5. Final confirmation (irreversible)

After this preliminary checks, we probably call https://docs.python.org/3/library/importlib.html#importlib.import_module. It may look like
```python
def update_db_data():
    import fractal_server
    slug = slugify_version(fractal_server.__VERSION__)   # note: this strips any prerelease info here, and converts 1.4.2 into 1_4_2, and coverts 1.4.2a123 into 1_4_2
    module = import_module(f"fractal_server.migrations.data_migration.{slug}")
    module.update_db_data_function()
```

Note that `fractal_server.migrations.data_migration` is not included in coverage, but its most recent file must be tested within the migrations.yml action. Maybe useful (TBD) to move all the old versions into a  `old` subfolder (that can be ignored when building the package).

**Comment by tcompa** [comment]
As part of #1197, the actual flow would be the following

```console
$ grep SQLITE_PATH .fractal_server.env   # just an example, to show that the env file is in the current directory
SQLITE_PATH=test.db

$ pip install fractal-server==1.4.3a1
...

$ fractalctl set-db
...

$ fractalctl update-db-data
**WARNING**
This command acts directly on database data. If you have any doubt about this, do not run it!

Expected use case:
You have updated fractal-server from some old version to a target version, and now need to fix some database data.
The detected target version is '1.4.3a1' (corresponding to the update-db-data module '1_4_3.py').
Note that the old and target versions MUST be consecutive, that is, you cannot skip an intermediate version.
The list of released versions is available at https://github.com/fractal-analytics-platform/fractal-server/blob/main/CHANGELOG.md.

Do you confirm that the old and target versions are consecutive? (yes/no)
yes
Do you confirm that the target version is 1.4.3a1? (yes/no)
yes
Have you run 'fractalctl set-db' with the target version? (yes/no)
yes
Have you made a backup of your database (e.g. via `pg_dump`)? (yes/no)
yes
Are you sure you want to proceed? (yes/no)
yes
OK, now starting data-migration script

WARNING:root:FRACTAL_TASKS_DIR="Tasks" is not an absolute path; converting it to "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks"
fractal_server.app.db
WARNING:fix_db:START execution of fix_db function
...
WARNING:fix_db:END of execution of fix_db function
```

We took multiple steps to avoid applying one of these scripts by mistake:
1. The long list of yes/no questions
2. If there is no `.fractal_server.env` in the current directory the procedure stops
3. If there is a version mismatch (due to an human error, like writing the wrong version number in the fix-db script), the procedure stops. Note that this error is in principle also visible in the CI.

@jluethi could you please double-check the `fractalctl update-db-data` wording in the example above? Is it clear?

**Comment by jluethi** [comment]
That looks great. The wording is clear to me and thumbs up on the explicit check-list that one needs to go through!
