### ISSUE TITLE
Running tasks in different python environments

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#114]
We should start the discussion about running tasks in defined python environments. Not an urgent thing to implement, but we should discuss our overall strategy to this.

Will come up when we run different neural networks, but may also come up when we implement more diverse napari workflows (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/31, these all run within the same environment still, but one could easily define new workflows with different environment needs).

**Comment by tcompa** [comment]
Superseded by #198 and related ongoing work/issues.
