### ISSUE TITLE
Edge cases in setting SLURM account for a job

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1146]
As of #1145, the two following ways of setting a SLURM account will be forbidden:
1. Via the job worker_init variable
2. Via the `WorkflowTask.meta["account"]` value

Not fully addressed yet: what happens when the SLURM configuration file sets a given SLURM account and then the user sets a different one when applying a workflow?

**Comment by jluethi** [comment]
> Not fully addressed yet: what happens when the SLURM configuration file sets a given SLURM account and then the user sets a different one when applying a workflow?

Would be great if in that case, the config setting is treated as the default that can be overwritten by the user by setting a slurm account.

**Comment by tcompa** [comment]
Let's try to bring it down to specific expected outcomes.

SITUATION: No global account, `myuser.slurm_accounts=[]`, no `slurm_account` in apply-workflow request body
OUTCOME: Job sets no account

SITUATION: Global account `common`, `myuser.slurm_accounts=[]`, no `slurm_account` in apply-workflow request body
OUTCOME: Job sets `common` account

SITUATION: No global account, `myuser.slurm_accounts=["account1", "account2"]`, no `slurm_account` in apply-workflow request body
OUTCOME: Job sets `account1` account

SITUATION: Global account `common`, `myuser.slurm_accounts=["account1", "account2"]`, no `slurm_account` in apply-workflow request body
OUTCOME: Job sets `account1` account

SITUATION: Global account `common`, `myuser.slurm_accounts=["account1", "account2"]`, `slurm_account="account2"` in apply-workflow request body
OUTCOME: Job sets `account2` account

If these expected outcomes are OK (cc @jluethi), I think this requires no change to fractal-server.

---

The question arises for the two following (hypothetical) cases

SITUATION: No global account, `myuser.slurm_accounts=["account1", "account2"]`, **something else which is still TBD**
OUTCOME: Job sets no account

SITUATION: Global account `common`, `myuser.slurm_accounts=["account1", "account2"]`, **something else which is still TBD**
OUTCOME: Job sets no account

That is, do we need to support the case where accounts are defined somewhere (either a global one, or some accounts associated to the user) but we want the possibility to run a job with no account?

I've not explored it in detail yet, but my guess is that:
* We could make it reasonable simple to override the default choice of using the first account in `user.slurm_accounts` through an appropriate API request-body argument, and make it such that the job runs with no account
* It would be complex to do the same to override a global SLURM account to fully remove the account.

**Comment by jluethi** [comment]
> If these expected outcomes are OK (cc @jluethi), I think this requires no change to fractal-server.

Yes, this sounds like the desired behavior!
The way I imagine the Fractal web implementation is that if there are `myuser.slurm_accounts`, the user has to select one (with the first one being the default). Thus, from Fractal web, we likely couldn't have a scenario like "myuser.slurm_accounts=["account1", "account2"], no slurm_account in apply-workflow request body". But the handling above is fine!

> That is, do we need to support the case where accounts are defined somewhere (either a global one, or some accounts associated to the user) but we want the possibility to run a job with no account?

I don't think this is a critical feature. But if we want something like that: Can we do something like `slurm_account` in apply-workflow request body is set to an explicit value that is different from not providing something in apply-workflow request body. 
I would not want to default to this behavior though, e.g. in most cases, either the thing set in common or set in the myuser.slurm_accounts should be used. Not 100% sure how we'd show this following scenario in Fractal web:

SITUATION: Global account common, myuser.slurm_accounts=[], no slurm_account in apply-workflow request body
OUTCOME: Job sets common account

=> Can we include "common" in the drop-downs for available options for slurm_account in apply-workflow request body? If so, then adding a None option would seem fine to me

**Comment by jluethi** [comment]
See also discussion here whether "" is a valid slurm account setting here: https://github.com/fractal-analytics-platform/fractal-web/issues/334#issuecomment-1888665099

**Comment by jluethi** [comment]
I don't think we need to support this in more detail for now
