### ISSUE TITLE
Explore other options for slurm-containers

### ISSUE THREAD

**Issue by mfranzon** [fractal-analytics-platform/fractal-server#1170]
https://github.com/eth-cscs/slurm-container/tree/main

**Comment by tcompa** [comment]
Also relevant for https://github.com/fractal-analytics-platform/fractal-containers

**Comment by tcompa** [comment]
For the record:
* https://github.com/rancavil/slurm-cluster
* https://github.com/eth-cscs/slurm-container
* https://github.com/giovtorres/slurm-docker-cluster
* https://github.com/xtreme-d/docker-slurm-cluster
* https://github.com/synpse-hq/slurm-cluster
* https://github.com/SciDAS/slurm-in-docker
* https://github.com/naterini/docker-scale-out
* https://github.com/zhonger/docker-slurm
* https://github.com/kwaszczuk/slurm-docker
* https://github.com/sarusso/SlurmID
* https://github.com/GRomR1/docker-slurmbase

**Comment by tcompa** [comment]
For the record, the current images are based on ubuntu20, which only offers python 3.8 and 3.9.
It's then quite tricky to install python 3.10 or 3.11, which is one good reason for moving on towards a different image.

(ref #528)

**Comment by tcompa** [comment]
We eventually created our own image. The first version is available as
```
docker pull ghcr.io/fractal-analytics-platform/ubuntu22-slurm:0.1
```
