### ISSUE TITLE
Deprecate python 3.9

### ISSUE THREAD

**Issue by mfranzon** [fractal-analytics-platform/fractal-server#1177]
The main reasons are:
* near end of life 2025,
* https://github.com/fractal-analytics-platform/fractal-demos/issues/65

@jluethi could you please confirm that we can deprecate python3.9 and keep only 3.10/3.11?

**Comment by tcompa** [comment]
> @jluethi could you please confirm that we can deprecate python3.9 and keep only 3.10/3.11?

For the record: 3.11 support is not fully there yet, but it's mostly related to https://github.com/fractal-analytics-platform/fractal-server/issues/1170 and https://github.com/fractal-analytics-platform/fractal-server/issues/528.

**Comment by jluethi** [comment]
We can not deprecate Python 3.9 for the time being:
Multiple deployment machines only run Python 3.9, not newer versions of Python just yet. That currently applies to FMI machines.

We can start investigating using different Python versions on those, but that won’t be immediate.

I also checked numpy and they recommend dropping Python 3.9 support in April

**Comment by tcompa** [comment]
>  Multiple deployment machines only run Python 3.9, not newer versions of Python just yet.

Just to avoid ambiguity: Are there active fractal-server instances running with Python 3.9? (the deprecation would only concern fractal-server, not tasks)

**Comment by jluethi** [comment]
Yes, the 2 servers at FMI are running under Python 3.9

> EDIT: given https://github.com/fractal-analytics-platform/fractal-demos/issues/65, I thought this was not the case. But of course I may be wrong ;)

That warning was just about not using Python 3.9.0 or 3.9.1. The later 3.9.x versions are running fine.

We're using venvs from the system Python at FMI, as conda environments are having some issues with system libraries. On the machines we are running, the system only provides Python 3.9.x versions (some later 3.9.x release).

That may be something that can be changed in the future. Let's check back what machines we get after the FMI move in March / April. And if really necessary, we can find a way to install newer Python on them I guess (just maybe not via the system Python)

**Comment by tcompa** [comment]
OK, thanks for the clarification.

Closing.
