### ISSUE TITLE
Improve and "standardize" error-message header

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1213]
As of https://github.com/fractal-analytics-platform/fractal-web/issues/373#issuecomment-1929709045, we parse the error messages in fractal-web and then highlight the most relevant parts.
In fractal-server, we should make sure that the three known cases (task error, job error, unknown error) produce homogeneous error messages.
For instance they could look like 
```
TASK ERROR in task '{name}' (Fractal job {job_id}, WorkflowTask ID: {wftask_id}, position in Workflow: {order})
TRACEBACK:
...

JOB ERROR in Fractal job {id}
TRACEBACK:
...

UNKNOWN ERROR in Fractal job {id}:
TRACEBACK:
...
```

**Comment by jluethi** [comment]
I like this version:
```
TASK ERROR in task '{name}' 
TRACEBACK:
```


It should make it more clear to a user which task failed in the workflow based on the task name. We can add relevant IDs, though they would not have user relevance. Adding the position in the workflow can be helpful again in case of having the same task multiple times (e.g. multiple measurement tasks)
