### ISSUE TITLE
Remove `slurm` extra

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1254]
Right now, the `slurm` extra adds these two additional requirements:
```console
$ poetry show clusterfutures

 name         : clusterfutures                           
 version      : 0.5                                      
 description  : futures for remote execution on clusters 

dependencies
 - cloudpickle *

$ poetry show cloudpickle
 name         : cloudpickle                                  
 version      : 2.2.1                                        
 description  : Extended pickling support for Python objects 

required by
 - clusterfutures *
```
These are lightweight packages, with no further transitive dependencies.

Having `slurm` as a conditional extra makes a few codepaths within the runner more complex, with no actual benefit (since we mostly deploy in SLURM clusters). As a side comment, this also doesn't play nicely with conda-forge, since the code analysis always tries to add `cloudpickle` as a required dependency, since it is identified within the code base.

Shall we simply make clusterfutures and cloudpickle required dependencies? I don't see any relevant downside of it.

It'd be best to do this before V2 or as part of V2, to make a bunch of runner internals simpler.

**Comment by jluethi** [comment]
No veto from my side. We can always get more complex if we'd actually support different backends in the future.
