### ISSUE TITLE
Handling errors in the middle of a task

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#128]
The more complex version of https://github.com/fractal-analytics-platform/fractal-server/issues/106

Most tasks will probably fail initially because some parameter was wrong. But it's possible that a task runs for some ROIs and only fails later.

If we're doing something on the label or measurement side, that's fine. We can fix the errors and rerun everything.
If we were doing something on the image side, e.g. illumination correction or registration, rerunning this again on the ROIs that it has already completed would be a problem.

Thus, for overwrite cases, how do we continue after an error?

The best case would be: We only process the ROIs that haven't been processed so far. To be able to do that, Fractal would need some concept of what happens inside the task, to know which ROIs have been processed and tell a task only to process the remaining ROIs.

That would require:
1) Tasks take a ROI argument to set which ROIs to process or which ROIs to skip
2) A failing tasks reports which ROIs have been processed in a way that Fractal can make sense of it
3) The continue workflow / resume workflow function that can take this information and pass it to the task when it is rerun.

**Comment by tcompa** [comment]
Mentioned today during our call:
where would this information ("task failed at ROI 7") be stored? Should we think about additional metadata (not the current dataset metadata) on the fractal side? Maybe, but let's also keep in mind that this adds complexity to the runner.

**Comment by jluethi** [comment]
Out of scope for the momnet
