### ISSUE TITLE
How to validate self-association of the pair (fractal user, SLURM user)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#129]
This is currently set by the user, upon registration with fractal.
Possible options:
1. Admins need to authorize association
2. User is given a challenge to associate their fractal/SLURM users (e.g. "read a certain file from your home, on the cluster")

**Comment by jluethi** [comment]
Alternatively: Only admins can register users (=> e.g. do this during setup of the server for our tests)

**Comment by tcompa** [comment]
Currently fixed by restricting registration to superusers (see #403 and #446)
