### ISSUE TITLE
treat each task as an independent executable

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#132]
this allows to have potentially completely separate environments per task

**Comment by tcompa** [comment]
As long as we stick with parsl, this also involves the switch from `python_app`s to `bash_app`s. Tasks need to be modified accordingly: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/133

Note that this is also essential for the use of per-task python environments (which would be hard/impossible when running a task as a python function or parsl app).

**Comment by jacopo-exact** [comment]
closed by #159
