### ISSUE TITLE
PyPI release cannot include parsl fork from github

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#137]
`poetry publish` yields
```
Uploading fractal-server-0.3.0.tar.gz FAILED

HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'parsl[monitoring] @ git+https://github.com/fractal-analytics-platform/parsl.git@1.3.1-dev' | [...]
```

**Comment by tcompa** [comment]
This seems to be a fundamental problem with PEP440 and PyPI not accepting dependencies of this kind, see e.g.
* https://github.com/python-poetry/poetry/issues/2828
* https://peps.python.org/pep-0440/#direct-references

For the time being, we'll switch to github releases (with attached binaries), so that installing the 0.3.1 version becomes
```
pip install https://github.com/fractal-analytics-platform/fractal-server/releases/download/0.3.1/fractal_server-0.3.1-py3-none-any.whl
```

Let's try to fix it in a cleaner way later on.

**Comment by jluethi** [comment]
That's just for the server, right? Tasks & client can still be released to pypi?

Suboptimal of course, but good that we have this backup installation procedure until there is an actual fix.

**Comment by tcompa** [comment]
> That's just for the server, right?

Yes

**Comment by jacopo-exact** [comment]
need to check if pre-built packages hosted as github releases are allowed

**Comment by tcompa** [comment]
Currently obsolete, as we do not depend on parsl (fork) any more.
