### ISSUE TITLE
Allow modifying dataset zarr-dir if there is no image yet

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1385]
ref https://github.com/fractal-analytics-platform/fractal-web/issues/441#issuecomment-2051225917

> When is the `zarr_dir` something the user can modify?
> My first-level take-away: Before there are any entries in the image list, it can be modified. Afterwards, it's not something the user can change anymore

**Comment by jluethi** [comment]
At least in fractal server 2.0.0a4, I can still modify it after creation, even if there are images in the image list already.
(have not tested 2.0.0a5 yet though!)

**Comment by tcompa** [comment]
> At least in fractal server 2.0.0a4, I can still modify it after creation, even if there are images in the image list already.
> (have not tested 2.0.0a5 yet though!)

This is part of an open PR (https://github.com/fractal-analytics-platform/fractal-server/pull/1367), where we forbid modifying zarr-dir. We will update the PR based on this new issue.
