### ISSUE TITLE
Alembic sets default boolean to 0 rather than false

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1388]
As part of https://github.com/fractal-analytics-platform/fractal-server/pull/1386/commits/6bf745ac1af7ef6ddfe7e37ba2797744af2902bc, the autogenerated migration scripts include
```python
    op.add_column(
        "task",
        sa.Column(
            "is_v2_compatible",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
```
rather than `sa.text("false")`.

This is now fixed manually with https://github.com/fractal-analytics-platform/fractal-server/pull/1386/commits/18558a02bd7aaf6253f573ae2b114ae44fe0f2f6, but let's review the issue and see whether we are setting something wrong in the model definition.

**Comment by tcompa** [comment]
For the record, we currently use
```python
    is_v2_compatible: bool = Field(
        default=False, sa_column_kwargs={"server_default": sql.false()}
    )
```

**Comment by ychiucco** [comment]
Using   `sqlalchemy.sql.false()` (or, equivalently, `sqlalchemy.sql.expression.false()`) as `server_default` will produce differents results after `alembic revision --autogenerate`, depending on the DB currently used:
- SQLite -> `sa.text("0")`,
- Postgres -> `sa.text("false")`.

While `"false"` is accepted and interpreted correctly by SQLite (https://www.sqlite.org/quirks.html#no_separate_boolean_datatype), this is not true for `"0"` and Postgres.

It seems there is nothing we can use in place of `sqlalchemy.sql.false()` to generate the same exact migration with SQLite and Postgres.
