### ISSUE TITLE
When I try to locally collect fractal-tasks-core 0.14.3 on a 2.0.0a9 server, I run into the following error:

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1415]
When I try to locally collect fractal-tasks-core 0.14.3 on a 2.0.0a9 server, I run into the following error:

```
2024-04-18 13:40:00,775 - fractal-tasks-core - INFO - Background collection failed. Original error: 'TaskManifestV1' object has no attribute 'executable_non_parallel'
```

Is this unrelated (=> new issue?)

_Originally posted by @jluethi in https://github.com/fractal-analytics-platform/fractal-server/issues/1411#issuecomment-2063682734_

**Comment by tcompa** [comment]
I cannot reproduce this - more info would be useful:

1. How do you trigger this task collection? CLI or web client?
2. Are you using the V1 or V2 task-collection feature?
3. Did you already collect (or try collecting) the same package before?

**Comment by tcompa** [comment]
This is with fractal-server `main` and with fractal-web `further-v2-changes`

![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/67df6fd0-bd2e-4a18-902d-75cb432d9be5)

**Comment by jluethi** [comment]
Ah, I was trying to do this in Fractal V2, not the legacy branch! Didn't realize I had to switch to the legacy branch for that collection, but it makes sense of course!

**Comment by tcompa** [comment]
> 2024-04-18 13:56:39,400 - fractal-tasks-core - INFO - Background collection failed. Original error: 'TaskManifestV1' object has no attribute 'executable_non_parallel'

This appears when I try to collect fractal-tasks-core 0.14.1 with the V2 collection.
