### ISSUE TITLE
Cannot remove task (perhaps WorkflowV2 was not removed properly upon project deletetion?)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1457]
Reported by @jluethi:

I deleted the project that used a task. Then I wanted to delete the task. But couldn’t:
{
  "detail": [
    "Cannot remove TaskV2 7 because it is currently imported in WorkflowsV2 [1]. If you want to remove this task, then you should first remove the workflows."
 ]
}

**Comment by jluethi** [comment]
There are 2 parts to this issue for me:
1) In this case, I think the deletion of the task should have worked. At least as far as I can understand
2) It would be great to make this error a bit more easily actionable: Can we e.g. provide the name of the user & name of the project & workflow?

**Comment by jluethi** [comment]
On why it didn't work: Are V2 workflows deleted when a project gets deleted?

**Comment by tcompa** [comment]
For the moment I cannot reproduce in a clean situation. The following set of actions goes through, and I can delete the task.

![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/1ba008ab-8ed8-4197-92a3-4b1106dac942)
![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/102a07e9-b5f9-453e-8911-ae4608563fe7)
![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/29b1353a-89c5-4e7f-8715-87206b864130)
![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/a13675f5-d54f-4ad3-a4f1-8f6181d87e88)

**Comment by tcompa** [comment]
> On why it didn't work: Are V2 workflows deleted when a project gets deleted?

Yes, this is expected to work the same way as in V1. Deleting a V2 project deletes all related workflows (see my log in the previous comment).

**Comment by tcompa** [comment]
> It would be great to make this error a bit more easily actionable: Can we e.g. provide the name of the user & name of the project & workflow?

Agreed, we can improve this message.

Also, I'd find it useful to show object IDs in fractal-web. I agree that this is not crucial for users, and it can even be confusing, but having id=7 e.g. in a task modal is very useful for debugging (note that workflow/project IDs can be somehow obtained from the URLs, but task IDs are mostly hidden).

**Comment by tcompa** [comment]
This:
> "Cannot remove TaskV2 7 because it is currently imported in WorkflowsV2 [1]. If you want to remove this task, then you should first remove the workflows."

could become something like

> Cannot remove TaskV2 with ID=7 ("task name xxx) because it is currently imported in N workflows. If you want to remove this task, then you should first remove the following workflows:"
> Workflow 111 ("workflow name xxx"), in project 222 ("project name xxx") of user 123 (user@example.org)
> Workflow 123 ("workflow name xxx"), in project 333 ("project name xxx") of user 123 (user@example.org)

TBD: let's first review the access-control rules for this endpoint. A standard user should not be allowed to get information about other users' profiles or projects.

**Comment by jluethi** [comment]
> Cannot remove TaskV2 with ID=7 ("task name xxx) because it is currently imported in N workflows. If you want to remove this task, then you should first remove the following workflows:"
> Workflow 111 ("workflow name xxx"), in project 222 ("project name xxx") of user 123 ([user@example.org](mailto:user@example.org))
> Workflow 123 ("workflow name xxx"), in project 333 ("project name xxx") of user 123 ([user@example.org](mailto:user@example.org))

I like this direction. Could also be something that just shows up on an admin page for tasks to simplify access control.

> then you should first remove the following workflows:

Should become: Then you should update the task in these workflows or remove the workflows:
