### ISSUE TITLE
Conditionally include V1 API

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1477]
Let's add a new configuration variable
```python
FRACTAL_API_V1_ENABLED: Literal["true", "false"] = "true"
"""
Whether to include the v1 API; accepted values are `true` (default) or `false`.
"""
```
such that if `FRACTAL_API_V1_ENABLED == "false"` then we do not include the V1 routers.

(even better if can stick with a `bool` variable, but we need to make sure of which string values are parsed and coerced correctly).

**Comment by ychiucco** [comment]
Valid values for boolean `FRACTAL_API_V1_ENABLED`:

- as `True`:
    - any string that made lower case is equal to `true` or `t`: e.g. `TrUE`,`truE`,  `T`, `t`;
    - `1`;
- as `False`:
    - any string that made lower case is equal to `false` or `f`: e.g. `FalSe`,`FALSE`,  `F`, `f`;
    - `0`.
