### ISSUE TITLE
Make app more robust against current-directory index-number changes

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1483]
The most likely explanation we found for https://github.com/fractal-analytics-platform/fractal-server/issues/1478 was a change in the current-working-directory index number, probably due to an export of the NFS shares where `fractal-server` runs. Note that we cannot verify the old index number any more.

This scenario is not expected, but we can still partly mitigate it. The specific issue in #1478 was with the [`Path.resolve` function](https://github.com/python/cpython/blob/3.12/Lib/pathlib.py#L1228), which then calls `os.getcwd()` as part of its internals. We use `resolve()` in very few modules, and it's likely that we could always ~~replace it with `as_posix()`~~ remove it (or, when we cannot, these are parts of the code that would probably run at startup - when the folder definitely hasn't changed index number yet). This change would mitigate the issue in #1478.

---

To debug:
* `cd` into a temporary folder `tmp1` and start `fractal-server` from there (first take a note of the results of `ls -ila`, where `-i` prints the index number)
* From a different terminal: `cd ..`, `cp -r tmp1 tmp2`, `rm -r tmp1`, `mv tmp2 tmp1`. If we now `cd` into `tmp1` and run `ls -ila`, we'll find a different index number
* Keep interacting with `fractal-server`, and see what goes wrong.

If we find other parts of the code that rely on the current working directory, we should check whether it's easy to replace them with equivalent robust versions.

---

Higher level advice:

1. It's best to run the application from a very stable mount (e.g. an attached ext4 volume)
2. System-side, one should consider NFS re-exports as potentially breaking

**Comment by ychiucco** [comment]
With upcoming pull request, we solved the error from #1478 but we found a similar error related to Task collection (collecting `fractal-tasks-core` with `pip`):

```
Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/Users/yuri/Library/Caches/pypoetry/virtualenvs/fractal-server-zZ2T8p1a-py3.10/lib/python3.10/site-packages/pip/__main__.py\", line 8, in <module>\n    if sys.path[0] in (\"\", os.getcwd()):\nFileNotFoundError: [Errno 2] No such file or directory\n")
Invalid package or manifest. Original error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/yuri/Library/Caches/pypoetry/virtualenvs/fractal-server-zZ2T8p1a-py3.10/lib/python3.10/site-packages/pip/__main__.py", line 8, in <module>
    if sys.path[0] in ("", os.getcwd()):
FileNotFoundError: [Errno 2] No such file or directory
```
