### ISSUE TITLE
Fix bug in accessing WorkflowTaskV2 meta in V2 local runner 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1554]
We are currently using the `wftask.meta` attribute, which doesn't exist.

**Comment by ychiucco** [comment]
Ref

**Comment by ychiucco** [comment]
solved with https://github.com/fractal-analytics-platform/fractal-server/pull/1544/commits/2db7497e598f83e0fc58fcd3f8ad5c1fa5112654
