### ISSUE TITLE
Fabric `connection.run` never takes less than a second?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1606]
`connection.run("whoami", hide=True)` takes almost exactly a second (plus small overhead), independently on how fast the command (e.g. `whoami`) would take

(ref #1605)

**Comment by tcompa** [comment]
Here is minimal example
```python
import time
from devtools import debug
from fabric.connection import Connection

with Connection(
    host=ADDRESS,
    user="fractal",
    connect_kwargs={"password": "fractal"},
) as connection:
    
    connection.open()
    debug("START")

    t0 = time.perf_counter()
    res = connection.run("whoami")
    t1 = time.perf_counter()
    debug(res, t1-t0)
    debug(res.stdout)
```
which prints an elapsed time of more than one second.

Note that 
```
$ time ssh fractal@ADDRESS ls

real	0m0.148s
user	0m0.032s
sys	0m0.001s
```

(cc @mfranzon)

**Comment by mfranzon** [comment]
The average time after 10 runs on my local machine is:

```python
res: <Result cmd='whoami' exited=0> (Result)
t1-t0: 0.06541475800008811 (float)
```

As we said, the overhead was related to the VPN.

**Comment by tcompa** [comment]
Agreed, I also tested it and can confirm.
Funny how the VPN introduces a precise one-second delay, but we don't need to understand this right now.
