### ISSUE TITLE
Should we include the Python version in the package-venv folder name?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1631]
For this moment, when a user collects tasks package `xxx` with python 3.11 and then tries to collect it again with python 3.10 they receive a response like "All good, package is already present". This is because the endpoint checks whether a folder called `xxx` exists as a valid collection folder, but the folder name does not include the Python version.

If we modify the folder so that it includes the Python version, the second task-collection API call will trigger a second task collection. The obvious downside is that it'd be easier to create many venvs - with all related problems in terms of disk space.

Which option do we prefer?

**Comment by jluethi** [comment]
Hmm...
There normally _shouldn't_ be a reason to have the same task package & version with different Python version. But if there _can't_ be these 2 versions coexisting on a Fractal server, that also seems tricky to me.

If we actually support this though, there will also be downstream issues regarding how we show the tasks to users. How do we show that there are 2 versions of a given task for 1.1.0?

My initial thinking was to allow for this. But given all the complexities it introduces, I don't think we should for the time being. Less for task env space and more for confusion of what it means to have multiple tasks of the same version available.

**Comment by tcompa** [comment]
> My initial thinking was to allow for this. But given all the complexities it introduces, I don't think we should for the time being. Less for task env space and more for confusion of what it means to have multiple tasks of the same version available.

This makes sense to me.

Closing - and we can revisit later if appropriate (after the upcoming work on tasks)
