### ISSUE TITLE
Catch exception in `db_sync.get(JobV2, job_id)` in `submit_workflow`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1709]
We did observe an error like
```python traceback
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) consuming input failed: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[SQL: SELECT jobv2.id AS jobv2_id, jobv2.project_id AS jobv2_project_id, jobv2.workflow_id AS jobv2_workflow_id, jobv2.dataset_id AS jobv2_dataset_id, jobv2.user_email AS jobv2_user_email, jobv2.slurm_account AS jobv2_slurm_account, jobv2.dataset_dump AS jobv2_dataset_dump, jobv2.workflow_dump AS jobv2_workflow_dump, jobv2.project_dump AS jobv2_project_dump, jobv2.worker_init AS jobv2_worker_init, jobv2.working_dir AS jobv2_working_dir, jobv2.working_dir_user AS jobv2_working_dir_user, jobv2.first_task_index AS jobv2_first_task_index, jobv2.last_task_index AS jobv2_last_task_index, jobv2.start_timestamp AS jobv2_start_timestamp, jobv2.end_timestamp AS jobv2_end_timestamp, jobv2.status AS jobv2_status, jobv2.log AS jobv2_log 
FROM jobv2 
WHERE jobv2.id = %(pk_1)s::INTEGER]
[parameters: {'pk_1': 33}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
with the traceback pointing at this line
https://github.com/fractal-analytics-platform/fractal-server/blob/060680e35d8fe74311464ab2f280fb11a4cd8d0f/fractal_server/app/runner/v2/__init__.py#L117

---

Independently on the reason (in this case it was probably due to an unexpected restart of the postgresql service), let's catch this error and call `fail_job` if appropriate.

**Comment by tcompa** [comment]
> Independently on the reason (...), let's catch this error and call `fail_job` if appropriate.

We actually cannot call `fail_job`, as it would likely fail for the same reason (not being able to access the database).
The best we can do is probably to raise a more explicit ERROR log, to clarify where this comes from in the fractal-server logs.

**Comment by jluethi** [comment]
Ah interesting. Makes sense, if we can't connect to the database, we also can't set the job state to failed, in the database 😂
