### ISSUE TITLE
Upcoming releases

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1735]
Here is the plan for what the next minor versions will be (to be updated as we go):

* `2.4.0`: A release that introduces the API for user groups, in a dummy way (it should be fully functional, but not used for any access-control).
* `2.4.1`: A bugfix release
* `2.4.2`: `sudo --set-home`
* `2.5.0`: A release that only deprecates legacy tasks in v2 workflows.
* `2.5.1`: Minor feature (validation of task commands) and bugfix
* `2.5.2`: Refactor of SSH-connections setup, in view of supporting multiple service users
* PLANNED: `2.6.0`: A release that implements user settings, and uses them for all background operations
    * https://github.com/fractal-analytics-platform/fractal-server/issues?q=is%3Aissue+is%3Aopen+label%3Av2.6.0
* PLANNED: `2.6.1`: Make necessary adjustments after 2.6.0 update-db-data has run
    * https://github.com/fractal-analytics-platform/fractal-server/issues?q=is%3Aissue+is%3Aopen+label%3Av2.6.1
* PLANNED: `2.7.0`:
    * Introduce task groups in the database, API and `tasks` subpackage
    * Setup new ACL scheme for tasks.
* Next releases:
 
   * Introduce deactivate/restore logic in API and `tasks` subpackage - issue TBD
   * Support for additional task metadata (both admin-related & user-related)

**Comment by jluethi** [comment]
+ support for additional task metadata (both admin-related & user-related)

**Comment by tcompa** [comment]
Not needed any more, since the current batch of releases is coming to an end with 2.7.0.
