### ISSUE TITLE
Setup new access rules for tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1736]
For the moment this is not a precise implementation plan, but a review of our preliminary discussions.

Note that this is not yet well integrated with the task-group plans (TBD in a different issue).

---

### Which users can see a task?
* A task is associated to both a single user (the one who collected/created it) and to N user groups.
* The task creator sets the "visibility" property of a task (user-only, groups-only, all users).
* If visibility="user", then only the creator (and all superusers) can see the task
* If visibility="groups", then only the task-groups members (and the creator, and all superusers) can see the task
* If visibility="all", any registered user can see the task

### Which users can import a task into their workflows?
* Same as the users who can see a task.

### Which users can edit task visibility?
* Only the task creator and superusers, but visibility can only be broadened (not restricted).

### Which users can edit other task metadata?
* Only the task creator and superusers.

### Which users can delete a task?
* Only the task creator and superusers.

### Which user can deactivate/reactivate task groups?
* Only the task creator and superusers.
* This is related to a new feature - TBD

**Comment by tcompa** [comment]
Here is a new proposed specification, which updates and replaces the one above. Briefly: if we remove the possibility of linking a single task to more than one user group, then we can get rid of the concept of `task.visibility` (and have it as part of the data).

## Proposed approach

### Data structure
* A task is **always** associated to a single user (the one who collected/created it), let's call this e.g. the `task.owner` (or "author",  "creator", "collector", "user", ..)
* A task is **optionally** associated to a single user group (which can also be the "All" group)

### Which users can see a task?
* Any admin and the task owner
* If the task is associated to a group, then all users of that group can also see the task. Note that the group can also be the "All" one (which includes all users).

### Which users can import a task into their workflows?
* Same as the users who can see a task.

### Who can edit what?
* The task owner in principle cannot be edited.
* The task group can be edited by the owner or by any admin. Note that access broadening is "easy", while access limitations require a bit of review (ref #1744).
* For other task metadata: some (e.g. tags) can be edited by the task owner or superusers, while others (e.g. commands) cannot be edited. This is defined in the API code (e.g. by explicitly listing the ones that can be modified - as we already do).

### Which users can delete a task?
* Only the task owner and superusers.

### Which user can deactivate/reactivate task groups?
* Only the task owner and superusers.
* This is related to a new feature - TBD

## Example of use cases

* Upon task collection or task creation, the user can choose a group to associate to some task(s):
    * None -> task is only visible to that specific user (and admins)
    * A specific group (e.g. one of the research groups in a multi-research-groups instance) -> task is visible to that specific group (and owner, and admins)
    * The "All" group -> task is visible to all instance users
* After some tests, the task owner (or an admin) can patch a task and move from "group=None" to "group='my-research-group" or to "group='All'".
* For each task that a non-admin user can see/use, it's easy to determine where the access rights come from:
    * tasks that the user own
    * tasks that the user can see because of non-"All" user-group membership
    * tasks that the user can access because they belong to the "All" group
* This same information (let's call it e.g. "access type") can be used to filter the task list, or to change the way it's displayed.

**Comment by tcompa** [comment]
(feedback on the latest comment is obviously welcome - cc @jluethi)

**Comment by jluethi** [comment]
>  if we remove the possibility of linking a single task to more than one user group, then we can get rid of the concept of task.visibility (and have it as part of the data).

Hmm... I think it may be important that task could belong to multiple user groups.

The default for tasks should be that they are visible to all and some tasks are only visible to the owner (e.g. tasks in development). 
But what if we have a new task package called `new_special_task_package` which a research group doesn't want to share with all users yet. Later, they either want to share it with an additional group or a second group wants to collect `new_special_task_package` of the same version. => what do we do?

I see 3 options, in roughly descending order of preference:
1. We allow task packages to be associated to multiple user groups
2. We allow multiple groups to collect a task package in the same version independently, e.g. they both have their own `new_special_task_package` in version 0.3.5 installed.
3. We work around these limitations by defining ad-hoc user groups which combine multiple research groups

Given that the default should be tasks accessible to all or a single user, I am somewhat fine with tasks only having a single group they are associated to if we can work around with option 2. But if the only way to enable this is option 3, then I think the trade-off is likely not worth it

**Comment by jluethi** [comment]
Results of further discussions:
This is a rare scenario. We want the default to be tasks getting shared with all.

Therefore, we can live with tasks getting associated with a single group.
As a workaround for admins in scenarios where this doesn't work out, we'll do the ad-hoc user groups

**Comment by tcompa** [comment]
The discussion above informed #1803, and it is now tracked over there.
Closing.
