### ISSUE TITLE
Eliminating the appearance of zombie processes when server gets stuck

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal-server#174]
When testing the client and server at FMI without the `--non-interactive` flag the server got stuck as the `sudo `command stayed hanging while waiting for a response due to its interactive mode. ultimately this led to time-out errors of the type `Not sending due to non-ready zmq pipe, timeout: 1048576 ms` . After trying to stop the server process with ctrl-c there was not a clean end to the process and `htop` ended up showing a couple of zombie processes.

Since for the particular example we already know the reason for this problem in the first place this one should not be an issue anymore. Still, I wonder whether there is a way to be sure that when the process terminates it is correctly collected by the parent process and to avoid zombie creation.

Has anyone seen this behavior of the server processes as well? Is there any straightforward practice that we could add to the current code to avoid the zombie processes in case the server runs into such a state?

**Comment by tcompa** [comment]
These days experiments with @jluethi suggest that the most likely behavior is correct (no zombie process).
I'm closing this, let's re-open if this error comes up again.
