### ISSUE TITLE
Split `FRACTAL_SLURM_SSH_WORKING_BASE_DIR` into tasks/jobs

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1768]
In the non-SSH case, we have `FRACTAL_TASKS_DIR` vs `FRACTAL_RUNNER_WORKING_BASE_DIR`.
We should replicate this in the SSH case (and we can obviously start by setting them to the same value, to maintain the current situation).

**Comment by jluethi** [comment]
Just for my understanding: We're placing the job logs in the same place as the task environments? Great if we start separating this. Depending on how we handle permissions of things, it would make sense that job logs are in a place that only that service user has access to, vs. tasks may be in a location with broader access for many service users

**Comment by jluethi** [comment]
Sure, no concern for the alpha server anyway. But 👍🏻 for this change and being able to handle this differently eventually
