### ISSUE TITLE
Structure for task-collection and job-execution configuration settings

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1769]
We explored with @mfranzon how to to define per-user configurations in view of multi-service-users support in SSH instances. Because of the difference between SSH/sudo scenarios, we have a choice to make between two somewhat opposite options. Feedback is welcome - cc @jluethi.

NOTE: This issue also serves as a recap of what/where is currently configured, in view of possible future updates - even though the specific decision to be taken has a limited scope (and reasonable workarounds do exist for non-optimal solutions).

# Required configurations

Let's first review what kind of configuration is needed, for each one of the current runners, for both task collection and job execution.

## local

Both task collection and job execution are performed by the single machine user who runs fractal-server.

Configuration is global (AKA identical for all Fractal users), and defined via these sources:
* For task collection, app configuration variables (e.g. `FRACTAL_TASKS_DIR`, `FRACTAL_TASKS_PYTHON_3_*`).
* For job execution, app config variables (`FRACTAL_RUNNER_WORKING_BASE_DIR`) and the content of a JSON configuration file `FRACTAL_LOCAL_CONFIG_FILE`.

## sudo-slurm

Task collection is performed by the single machine user who runs fractal-server, and venvs are placed in a broadly-accessible share. Job execution passes through granular user impersonation via `sudo -u`.

Configuration is a mix of global and per-user, with these sources:
* For task collection, app configuration variables (e.g. `FRACTAL_TASKS_DIR`, `FRACTAL_TASKS_PYTHON_3_*`).
* For job execution, app config variables (`FRACTAL_RUNNER_WORKING_BASE_DIR`), the content of a JSON configuration file `FRACTAL_SLURM_CONFIG_FILE`, and user-specific database attributes (`user.slurm_user` and `user.cache_dir`).

## ssh-slurm

Both task collection and job execution are performed by a user on the remote machine (whether it's the same user is partly TBD, depending on how we will define data-access to venvs for different users), and all commands are run via SSH.

Configuration is currently global:
* SSH credentials are defined in app config variables (`FRACTAL_SLURM_SSH_{HOST,USER,PRIVATE_KEY_PATH}`)
* For task collection, we have app configuration variables (e.g. `FRACTAL_TASKS_DIR`, `FRACTAL_SLURM_SSH_WORKING_BASE_DIR`, `FRACTAL_TASKS_PYTHON_3_*`).
* For job execution, we have both app config variables (`FRACTAL_RUNNER_WORKING_BASE_DIR`) and the content of a JSON configuration file `FRACTAL_SLURM_CONFIG_FILE`.

This must evolve towards a more granular definition, where different Fractal users may be associated to different SSH credentials (and remote folders).

# Options

The need for updating the current situation is mostly because we need to move from a global ssh-slurm configuration to a more granular (per-user) one.

Options A and B below are two directions we can take for the data structure. In our opinion, intermediate data-structure choices (e.g. having a `user.slurm_settings` unstructured JSON column, or having non-homogeneous ssh/sudo configurations) are not worth it, since the same functionality can be covered with a clean data structure and some helper feature (in the API or webclient).

## Option A

We maintain the current structure of config settings being part of the user table. On top of `slurm_user` and `cache_dir`, we include a few other attributes that are needed for SSH instances. All attributes are optional, and the config validity is verified at the API- and/or runner-level.

Upside:
* This is a small incremental change in the code base and database.

Downside:
* Settings are per-user, and any procedure to make N users share some setting (e.g. their SSH credentials or some relevant working directory) has to be a workaround (e.g. a specific bulk-edit endpoint or a bulk-edit webclient page).

## Option B

We establish a new table (e.g. `user_setting_profile`s), and each user is associated to one (and only one) of these setting "profile". The table is common to both ssh and sudo runners, and a flag like `runner_type: Literal["slurm_sudo", "slurm_ssh"]` is used for additional validation.

When creating/modifying a user, the admin can associate them to an existing settings profile (or create a new one).

Upside:
* In a multi-research-groups instance, a few settings profiles should cover many users, and the admin doesn't have to re-type the same configuration again when creating a new user of an existing group.
* We would create a separation between the user properties related to the API (email, active/superuser/verified, oauth_accounts) and those related to the collection/execution (slurm_user, cache_dir, username, ssh credentials, working directories). The latter represents a link between database and the actual system where we run Fractal (e.g. an HPC cluster with some specific data-access pattern, or whatever computational resource or workflow manager we end up using in the future).

Downside:
* There is an obvious complexity overhead for having a new table and some API changes;
* For a sudo-slurm instance, the setting profiles would have "many" lightweight rows (basically one per individual user, apart from admins or service users).

**Comment by tcompa** [comment]
Yet another addition: it could be reasonable to move some of the worker-init or local-exports (ref #1755) into this new container of configuration settings (especially as part of option B).

**Comment by jluethi** [comment]
Thanks for writing the overview. My first thoughts are that I like option B. 

SSH-slurm deployments are the ones that need to scale to many more users than sudo deployments very likely and the group configs make them much easier to maintain, especially if settings need to be adapted down the road.

Additionally, I think we should aim towards having the slurm-sudo mode evolve more towards running task collection remotely with specific configuration => sounds like something that matches remote profiles well.

> We would create a separation between the user properties related to the API and those related to the collection/execution 

This sounds like a good separation, especially also in view of potential new orchestrators in 2025 => we avoid overfilling the user table with many runner-specific options

Last part of the benefits:
Would it then be reasonable on a sudo instance to have some users use different `FRACTAL_SLURM_CONFIG_FILE` settings? That may become useful if some users typically run very different workflows (e.g. it's not generally convenient to set up large memory nodes, but we could allow it for some users that need it?)

-----

The only part where it does not seem very convenient is setting `slurm_user` where they vary per user. That would potentially mean we cannot share much config between users, but repeat it for each user with different slurm_user settings?
Other parameters (often also e.g. `slurm_accounts` would likely not vary much between users.

**Comment by tcompa** [comment]
> Would it then be reasonable on a sudo instance to have some users use different FRACTAL_SLURM_CONFIG_FILE settings? That may become useful if some users typically run very different workflows (e.g. it's not generally convenient to set up large memory nodes, but we could allow it for some users that need it?)

We also considered this possibility, especially as part of Option B.
It's certainly feasible to move some (or all) configuration from the current configuration JSON file into the per-user settings "profiles". We should find the right trade-off to avoid having to "type" the same (verbose) configuration for all users (e.g. we would use the current JSON file as a default, and then allow patches when needs be).

**Comment by tcompa** [comment]
> The only part where it does not seem very convenient is setting slurm_user where they vary per user. That would potentially mean we cannot share much config between users, but repeat it for each user with different slurm_user settings?

That's correct, and it applies to both `slurm_user` and `cache_dir` (namely the two attributes which are currently required for the sudo instances).

The way around this is twofold, IMO: we either introduce some more complex feature (e.g. a split of configuration attributed into "shareable" vs "private"), or we accept that each user is associated to a different profile and introduce mitigations/workarounds for some specific sudo-instance use cases.

In the current sudo-based instances, the only attribute that could be shared among multiple users is the `slurm_accounts` list - which I guess has a few items and rarely/never changes. For this use case alone, my take is that it's acceptable to keep filling the `slurm_accounts` list by hand for each user, as it's been up to now. At most, this is worth finding workarounds to streamline this operation.

This could change in the future, if we start using more complex settings that are to be shared among users (e.g. some task-collection working directory, or the whole SLURM configuration which is currently in the config JSON file). In that case, I can imagine workarounds so that the admin does not have to re-type the same information several times. An example is that profiles could have some global defaults (as in the current config JSON file, and possibly including anything that should be shared), and then the profile of each user could be modified for specific attributes.

Note that this being a workaround it would not be feature-complete:
* There wouldn't be a simple way to automatically update some configuration for all/many users at once. If these settings are to change somewhat often and in a coordinated way (i.e. in the same way for many users), then the original Option B is clearly suboptimal.
* There would not be any granularity (as in "we have several homogeneous subgroups of users within this instance"), because each user would still have a single profile associated to them.

**Comment by jluethi** [comment]
> In the current sudo-based instances, the only attribute that could be shared among multiple users is the slurm_accounts list

To make sure I understand the scope: Would things like `FRACTAL_SLURM_CONFIG_FILE` stay separate & global? As long as we have the concept of some global configurations and some user-specific ones, I think that should mostly fulfill the needs. The question then becomes: Can an individual user overwrite some global configs or are things strictly separated into "this can only be set per user" vs. "this can only be set globally"?

If we allow for global defaults that can be overwritten, even accounts could be handled that way: Set a global default and have individual users adapt it where necessary.

**Comment by tcompa** [comment]
In the current plan, settings would be stored in three places:

1. **Global config variables or config files** (e.g. the current JSON config for SLURM). These are _not_ persistent in the database, and the admin may change them at every app restart. These settings can be used in two (valid) ways:

    * A: They are used 'as is', at runtime, and they can change any time.
    * B: They are used as defaults for some database information (within the API, upon user creation or update), and then the settings that are used at runtime are the ones in the database.

2. **User attributes** (e.g. the current `slurm_user` or `cache_dir` or `slurm_accounts`). These are part of the database, and they are obviously per-user. The definition of "who can modify what" is not part of the data structure, but it's rather part of some internal logic (e.g. a user can change their `cache_dir`, but only a superuser can change their `slurm_user`).

3. **User-settings profiles**. These are stored in the database, but in general they are not per-user (that is, they may be shared among users - which is their entire point). As for point 2, the definition of "who can modify what" has to be defined in code rather than data. At a difference with 2, though, a change to a setting profile would affect multiple users at once (all the users associated to that profile) - which I guess is not the intended behavior.

---

To recap, it seems that the requirement is to have settings at these different levels:
* global (e.g. slurm defaults or working directories, only controlled by the admin)
* shared among multiple users (e.g. SSH credentials, only controlled by the admin)
* individual-locked (e.g. `slurm_user`, only controlled by the admin)
* individual-mutable (e.g. `cache_dir` or overrides of slurm accounts, controlled by each single user)

Is is correct? @jluethi

This granularity makes me partly take back the proposal above, and perhaps it's not worth it to implement the shared-profiles if they only cover a small subset of the relevant configurations. An alternative option (close to option A) is to store all settings at the per-user level, and define everything (validation, checks, defaults) in terms of internal logic. [Note that we can still keep a separate user-settings db table, to avoid polluting the user table, but the two tables would have a one-to-one relationship].
We would lack the by-design shareability of multi-user profiles (see downside of Option A above), but we can find workarounds to simplify the admin work (e.g. when creating a new user that has to share some other users' config).

**Comment by tcompa** [comment]
Here is our latest suggested approach, coming from discussions with @mfranzon  and @ychiucco - to re-discussed later this morning.

## Key points

1. Settings only exist as "global" or "per-user". This means that e.g. SSH information is not _shared_ among users but _replicated_. The API makes up for this data replication, e.g. by offering a bulk-user-edit endpoint.
2. Per-user settings are stored in a separate table, which is in a one-to-one relationship with the user table and then simply consists in a structured set of attributes. This offers a clear separation between a user and their settings, while keeping the database structure trivial.
3. This additional table can grow over time along with Fractal development. We start by only using it for SSH-related credentials, and then integrate other existing settings (e.g. the sudo-related ones) or new ones (e.g. overrides of global SLURM configurations, or anything else coming up in the future).

## Minimal example

To provide a clear example, let's consider that only these attributes and settings exist:
* `user.email`
* `slurm_user` and `cache_dir` (relevant for sudo instances)
* `ssh_username` and `ssh_key_path` (relevant for SSH instances)

The plan would be to move them all into a `user_settings` table, in a one-to-one relationship with the user table. This is how the user and settings tables would look like on sudo and SSH instances:

```
# user table (same on all instances)
id | email | user_settings_id
 1 | a@a.a | 1
 2 | b@b.b | 2
 3 | c@c.c | 3
 
# user_settings table on a sudo instance
id | user_id | slurm_user | cache_dir | ssh_user | ssh_key_path |
 1 |       1 |      aaaaa |  /tmp/a/  |     null |         null |
 2 |       2 |      bbbbb |  /tmp/b/  |     null |         null |
 3 |       3 |      ccccc |  /tmp/c/  |     null |         null |

# user_settings table on a SSH instance
id | user_id | slurm_user | cache_dir |  ssh_user | ssh_key_path |
 1 |       1 |       null |      null |    team-A |  /some/key-A |
 2 |       2 |       null |      null |    team-A |  /some/key-A |
 3 |       3 |       null |      null |    team-B |  /some/key-B |
```

## Remarks

1. The fractal-server code interacts with this data structure in multiple ways:
    * The API defines which columns are "locked" (only an admin can set or update a `slurm_user`) and which ones can be modified by the user (e.g. `cache_dir`).
    * The API may optionally perform additional validation, depending on the chosen backend.
    * The data structure is backend-runner-agnostic: for a local backend this would be a table filled with `null` values, while for sudo/SSH instances some specific columns will be required (and some other may or may not be filled). The definition of what is required belongs to task-collection and job-execution subpackages, which can perform additional runtime validation (e.g. if the backend is sudo-slurm then the user must have `slurm_user` and `cache_dir` set).
2. The webclient is aligned with the API, and for instance it can show to each user their settings (or a subset), and let them modify some of them. This would be next to the user's profile. If the complexity of settings grow, it's actually a clean solution to extract them from the profile.
3. The separation between the user and settings table is important, as already discussed in the current issue, and it's critical if the complexity of user settings grows over time.
4. This approach can be implemented incrementally. We can start by only moving _some_ attributes to the settings table (notably the ones for the SSH authentication), then move the existing sudo-related attributes, then introduce new attributes (e.g. overrides of default job-batching options). We don't have to move them all at once in the first release.
    * We can decide when it's worth grouping some of the columns together (e.g. in a single JSON column). This is often cumbersome, in general, but may be useful when a set of attributes always have to be set together.
5. The most obvious **downside is that we replicate the same data for N users**, in the SSH instances. We can work on the API or webclient to make its use smoother, e.g. through:
    * Dedicated endpoint for creating N users with the same settings
    * Dedicated endpoint for updating the settings of N users at once
    * Dedicated webpage for easily selecting users to edit based on some of their properties (e.g. "edit settings for all users that belong to this group")
6. In the current proposed approach, where all settings are per-user, we avoid creating _two_ independent user-group abstractions (the actual user groups, and user profiles). This mitigates the complexity of having two non-aligned way of grouping users.
7. (technical detail) The roll-out of this feature would be in two-steps: first we need to introduce an optional foreign-key relationship and to fill the new settings table, then we should make the relationship required in the subsequent patch version.
8. The proposed approach does not help nor hinder the possibility of using two different SSH configurations for task collection and for job execution - if needs be. We would only have to include different columns in the settings table.

**Comment by jluethi** [comment]
Approved :)

**Comment by tcompa** [comment]
The more precise implementation discussion and tracking is now in #1774 - closing
