### ISSUE TITLE
task collection 1.x from pypi

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#180]
Preliminary requirement: we need a shared folder that is readable and executable by the fractal user, let it be `FRACTAL_ROOT_DIR`

# from PyPI

in a subprocess...

1. create dedicated venv in `FRACTAL_ROOT_DIR/<pkg>_<version>`
2. install package in venv
3. extract manifest by `/venv/python -c "import <pkg>; print(pkg.__manifest__)"`
4. load all tasks exposed in manifest

## default behaviour

```bash
cd $FRACTAL_ROOT_DIR
PKG_DIR=$PKG_NAME_$PKG_VERSION
mkdir $PKG_DIR
cd $PKG_DIR
python -m venv venv (or similar for conda and the like)
source /venv/bin/activate (or similar)
(venv) pip install $PKG_NAME==$PKG_VERSION
(venv) python -c "import $PKG_NAME; print($PKG_NAME.__manifest__)" > /tmp/fractal/pkg_name_version.manifest.json
```
we read the output of the last command and access the manifest from within the server

the resulting tasks will have
- source = pypi:fractal-tasks-core==0.2.3
- command =  /path/to/venv/python path/to/module.py

## custom behaviour (TODO)
We keep the folder structure with the following pseudo-script

```bash
cd $FRACTAL_ROOT_DIR
PKG_DIR=$PKG_NAME_$PKG_VERSION
mkdir $PKG_DIR
cd $PKG_DIR
```

the user can provide a custom initialisation / installation script, which needs to output
1. how to call the dedicated python interpreter
2. the manifest

# from `FRACTAL_ROOT_DIR/<userdir>/<taskdir>/`

TODO

**Comment by jacopo-exact** [comment]
@tcompa can you please write here the command you would use to start an env with conda pls?

**Comment by tcompa** [comment]
```
conda create --prefix /tmp/MY_ENV python==3.8 --quiet --yes
conda activate /tmp/MY_ENV
pip install fractal-tasks-core==0.2.6
```

But notice that there is no special reason to use `conda`, for the default modules (to be made available for all users). You can go on with standard venvs if you prefer.

**Comment by tcompa** [comment]
Also note that the previous script creates a 3G folder (that would be only 200M before installing the tasks).

**Comment by jacopo-exact** [comment]
> ```
> conda create --prefix /tmp/MY_ENV python==3.8 --quiet --yes
> conda activate /tmp/MY_ENV
> pip install fractal-tasks-core==0.2.6
> ```
> 
> But notice that there is no special reason to use `conda`, for the default modules (to be made available for all users). You can go on with standard venvs if you prefer.

I actually prefer venv, but we need a way to specify the python version. I can write some fallback logic if needed, i.e.,
1. try `venv`
2. if it doesn't work try `pyenv + vnev`
3. if it doesn't work try `conda`
