### ISSUE TITLE
Introduce new TaskV2 attributes

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1828]
We should enrich the task model with some new (optional) attributes:
1. `type: Optional[str] = None`. Examples of typical values: `Conversion`, `Segmentation`, `Registration`, `Measurement`
    * `type` is already in use for parallel/non-parallel/compound tasks - let's find a better name
2. `modality: Optional[str] = None`. Examples of typical values: `HCS`, `lightsheet`, `EM`
3. `authors: list[str] = Field(default_factory=list)`. Example of typical values: `["Name1 Surname1", "Name2 Surname2"]` or `["Organization 1"]`
4. `tags: list[str] = Field(default_factory=list)`.

### Changes to make

Planned changes include

- [x] Update the database `TaskV2` model and create a new schema-migration script
- [x] Update the single-task API schemas (Create/Update/Read)
- [x] Update the task-collection manifest schema
- [x] Propagate single-task attributes from the manifest into the single task, upon task creation during task collection
- [x] Same as above, for the "global" `authors` attribute
- [x] Include query-parameters in the `GET /api/v2/task/` endpoint for filtering the task list so that the response only include a subset of matching tasks -> TBD whether this should be done in the backend or in the webclient
- [x] Update PATCH-single-task endpoints
- [x] Add tests
- [x] Test icontains on nullable column

### Expected behavior for PATCH endpoints

* `type`, `modality` and `tags` can be patched by users who have full access to tasks (ref #1803)
* `authors` can only be set upon task creation (either explicitly, for a single-task creation, or through the task-package manifest)

### Side note:

In principle some attributes (e.g. `authors`) may be identical for the tasks of a given taskgroup. For the moment we still choose to have them as single-task attributes, rather than shared task-group attributes. This makes access to these attributes simpler, removing the need for an additional database query.

---

cc @jluethi @lorenzocerrone let me know if this match with our discussion earlier today, or if I forgot something - thanks!

**Comment by jluethi** [comment]
This looks great to me!

> type is already in use for parallel/non-parallel/compound tasks - let's find a better name

Lorenzo and I brainstormed a little yesterday. Until we have a better answer, let's go with `category`.

> authors can only be set upon task creation (either explicitly, for a single-task creation, or through the task-package manifest)

Given that authors is just a free text field in the manifest, I don't think it needs special protection. I'd be fine treating it like `category`, `modality` & `tags`. The authors can put whatever they want there anyway, so why not let them edit it afterwards (e.g. if they forgot something, had a spelling mistake, notice that for one task they entered themselves as firstname-lastname and for the other package they just added their first name etc.)

> In principle some attributes (e.g. authors) may be identical for the tasks of a given taskgroup. For the moment we still choose to have them as single-task attributes, rather than shared task-group attributes. This makes access to these attributes simpler, removing the need for an additional database query.

Fine by me. We can discuss in manifest creation to have a single authors parameter used from the task list that then is applied to all tasks.

**Comment by tcompa** [comment]
How do we expect a query based on the new task-metadata parameters to work? Here are some simple examples:

* `category`: we require an exact match of the user-provided string (if any) with the attribute
* `modality`: we require an  exact match of the user-provided string (if any) with the attribute
* `authors`: one of the following?
    * we keep the list structure (e.g. `["name1 surname1", "name2 surname2"]`), and require that the user-provided string (if any) matches exactly with one of the list items
    * we move to an arbitrary single string (e.g. `"name1 surname1, name2 surname2"`), and require that the user-provided string (if any) is contained in the authors string
* `tags`: we require an exact match of the user-provided string (if any) with one of the list items
* for all comparisons above: is the match case-sensitive?

cc @jluethi @lorenzocerrone

**Comment by jluethi** [comment]
Good questions. The fuzzier we can be, the better. 

> for all comparisons above: is the match case-sensitive?

No

For some of the views, I imagine we provide pre-made filters to select from or allow users to e.g. sort the task list by category or modality. Alternatively, I imagine we will often do something similar to e.g. the dropdown filters on the dataset, e.g. list all options to filter by.

If we do expose search-term based search (which I'm open on when we implement, doesn't need to be now), fuzzy matching would be great. E.g. if I enter part of the name (just surname1), it matches. But we can start with only exact matching and just show selections in drop downs for the beginning
