### ISSUE TITLE
Test loss of access to a task

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1840]
Some API operations indirectly lead to the loss of access to a given task group (and then to one or more tasks):

1. The `TaskGroupV2.user_group_id` is changed from being set to being unset, so that only the task-group owner maintains access.
2. A `TaskGroupV2` is associated to a `UserGroup`, and a user is removed by that group.

If a user looses access to a task that they never imported into a workflow, this requires no special handling.
Here we are concerned with the case where a user looses access to a task that they had already imported into a workflow. We describe a user story based on case 2 above:

* User `a@a.a` belongs to user group `team1`
* Task group `my_pkg_1.2.3` is associated to user group `team1`
* When the users gets a task list, this list also includes task from `my_pkg_1.2.3`. In the webclient: when the user wants to add a task into a workflow, they also see `my_pkg_1.2.3` tasks in the dropdown menu.
* The user imports a given `my_pkg_1.2.3` task into their workflow `my_wf`
* The user possibly runs some jobs based on workflow `my_wf`
* An admin removes the user from user group `team1`
* When the users gets a task list, tasks from `my_pkg_1.2.3` are not there any more.
* If the user tries to get a given `my_pkg_1.2.3` task via its ID, the API responds with some Unauthorized error.
* The database `WorkflowTaskV2`/`TaskV2` relationship still exists and is still valid.
* When the user gets the information about their workflow `my_wf`, the API responds correctly. This means that the user can still see the task in the workflow task list, as if they had access.
* When the user tries to run `my_wf`, the API responds with some Unauthorized error.

The crucial point here is that if a user ever imported a task, we cannot _fully_ remove their knowledge of such task. We can prevent them from importing it again in new workflows, and we can prevent them to run an old workflow including such task. But the user should still be able to see what they did in the past.
To rephrase it: we are stating that the access-control rules should not apply to the read operation for something you already had access to in the past.

**Comment by jluethi** [comment]
> The crucial point here is that if a user ever imported a task, we cannot fully remove their knowledge of such task. We can prevent them from importing it again in new workflows, and we can prevent them to run an old workflow including such task. But the user should still be able to see what they did in the past.
To rephrase it: we are stating that the access-control rules should not apply to the read operation for something you already had access to in the past.

Great summary, that's the target outcome! And fully agreed with the user story above.

> The database WorkflowTaskV2/TaskV2 relationship still exists and is still valid.

Looks like a nice benefit of this WorkflowTask & Task model! :)
