### ISSUE TITLE
Updates to task collection / endpoint

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1853]
Branching from #1831 - see companion issue about background task (TBD)

The ongoing work on task groups gives us the opportunity to cleanup some logic of the task collection endpoints (the description below is for local/ssh collections, but the custom-collection one is similar).

Re: task group identity, the endpoint request falls into one of these options:
1. Local wheel file
2. Package name + version
3. Package name only

Based on this information above, we want to construct a `TaskGroupV2` object and add it to the database, and then pass it on to the background task which will actually perform the on-disk steps (venv creation, pip install, pinned dependency, pip freeze, ...). This means we have to:
* Find the normalized package name
* Find the package version (required)
* Find the target venv folder
* Verify non-duplication constraints
* Verify an additional constraint about uniqueness of the task-group venv_path - this in principle not required, but it could be useful in case of "dirty" on-disk status.
* Create and commit the taskgroup db object.
* Respond appropriately
* Call the background task

## Normalized package name

For wheel file, we start with `_parse_wheel_filename` to get package name and version.

For user-provided package name, we use `_normalize_package_name` (based on https://packaging.python.org/en/latest/specifications/name-normalization).

Note that normalization must take place _after_ the first interaction with `pypi` is over (the one about finding out the version, see next section).

## Package version

If the version is user provided, no action is needed.

For wheel file, we start with `_parse_wheel_filename` to get package name and version.

For pypi collection where the version is not provided, we make a pypi query - ref #1857.

## Venv folder

This is made of a base-path part and a package-specific part.

The base path definition is different depending on whether we are in SSH mode or not:
* In non-SSH mode, it is the config variable `FRACTAL_TASKS_DIR`
* In SSH mode, it is defined per-user within `user.settings.ssh_tasks_dir`. The planned use is that we could either have it identical for all users or we could group users in some way (e.g. a different subfolder corresponding to each service-user group).

The package specific part, up to now, was always in a folder like `.fractal/{package}{version}`. This cannot work any more, since two users will be allowed to collect the same package twice (in _private_ mode). I think the best approach is
* Remove the obsolete `/.fractal/` intermediate layer
* Introduce a `/user_id/` intermediate layer, so that the folder would be e.g. `{FRACTAL_TASKS_DIR}/{user.id}/my_package1.2.3`
    * Note: the `taskgroupv2.user_id` foreign key is required, and therefore always set.
    * Note: we don't delete users, so that this should not introduce any complexities (which would anyway be easily fixable by saying "if a user is deleted, all their collection folders must be deleted).
* Non-recommended alternative option: use the `TaskGroupV2` ID instead, and include it in the folder name as in `{FRACTAL_TASKS_DIR}/my_package1.2.3_{taskgroup.id}`. I'd say the user-id-based one is more relevant, as grouping tasks by who collected them may be more relevant in itself.

## Response for existing task group

When one non-duplication constraint is violated, the response is a 422 with an informative error (e.g. specifying whether the issue is with the task-group owner or with the required user group).

When the db already contains another task group with the same venv folder, again it's a 422.

Note (cc @jluethi): in case of overlapping folders, we currently have a feature that tries to determine whether a collection already took place - and respond with a 200 (OK) message if appropriate. I suggest we fully drop this attempt at verifying whether the same identical collection already went through smoothly, in favor of a more clear interaction:
* If the collection collides with an existing one, the user receives an informative error message (which most likely means they should rather use some already-existing task)
* If the collection target folder collides with the one of another existing taskgroup, this means something went wrong (e.g. some cleanup was not performed properly) - and an error message should say so.

**Comment by jluethi** [comment]
> {FRACTAL_TASKS_DIR}/{user.id}/my_package1.2.3 

Sounds like a good task path. We do expose user ids through that (because people can see their env paths for the tasks), but I don't think that's sensitive information :)

> we don't delete users

We don't delete users yet. May come down the road. But let's not tackle this here. Could imagine we then either don't reuse IDs or delete task packages (though that is somewhat tricky if they are in use by other users)

> Note (cc @jluethi): in case of overlapping folders, we currently have a feature that tries to determine whether a collection already took place - and respond with a 200 (OK) message if appropriate. I suggest we fully drop this attempt at verifying whether the same identical collection already went through smoothly, in favor of a more clear interaction:
> 
> If the collection collides with an existing one, the user receives an informative error message (which most likely means they should rather use some already-existing task)
> If the collection target folder collides with the one of another existing taskgroup, this means something went wrong (e.g. some cleanup was not performed properly) - and an error message should say so.

Sounds good to me!

**Comment by tcompa** [comment]
> We do expose user ids through that

Yes, I thought this was not a big deal - but we can easily decide to rely on the task-group ID if it's preferred.

> Could imagine we then either don't reuse IDs or delete task packages (though that is somewhat tricky if they are in use by other users)

For the moment a user _owns_ a task group, so that the user cannot be deleted without deleting the task group. We may introduce a "change ownership" feature, and just accept that the task-group path would not reflect the new ownership. But task-group paths are not attributed any special meaning (apart from the need of being unique), so that if we ever hit unexpected name clashes we can easily start adding suffixes or anything else that makes the paths unique.

**Comment by jluethi** [comment]
> Yes, I thought this was not a big deal - but we can easily decide to rely on the task-group ID if it's preferred.

I'm fine with the user ids here. Just wanted to have it explicitly mentioned so we're aware of that. I don't see them as sensitive.

Path question sounds good!

**Comment by tcompa** [comment]
As part of #1861, I am settling on paths like
```
/something/FRACTAL_TASKS_DIR/1/fractal-tasks-mock/0.0.1
```
to introduce a clear split between package and version.
