### ISSUE TITLE
Add test for non-python task

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#189]
* Write a minimal bash script conforming to the the right interface (`./script.sh -j /path/to/args.json -o /path/to/out.json`)
* Construct the task object, and set the appropriate `command`.
* Run it through fractal-server, e.g. as in `test_runner_backends.py`

**Comment by jluethi** [comment]
This will be very nice. E.g. if we'd want to integrate with the Java-based OME-NGFF converter from Glencoe to allow parsing of OME-compatible files to OME-Zarr (they just recently released their converter. I haven't tested it yet, but it may be a nice way to get access to more OME-Zarr parsing for diverse microscopes, though certainly wouldn't handle ROIs yet and probably not save things as individual images per well): https://github.com/glencoesoftware/NGFF-Converter
Also, it has a GPL 2.0 license, so we can't directly depend on it from our BSD3 license repo.

But in general, integration with such tools should become easier with the support for arbitrary executables.

**Comment by tcompa** [comment]
How to proceed in practice:
- Prepare a script that takes `--json` and `--metadata-out` string arguments (this could be 1. python+argparse, 2. bash, 3. whatever, and the arguments are just ignored)
- Install fractal-server 1.0.4a0 or higher (this is to use the new endpoint)
- In a new test, add a task **through the endpoint** (see `test_full_workflow.py::test_full_workflow` for examples of how to call endpoints in tests), setting all attributes by hand in a `TaskCreate` payload.
- Apply the workflow (as in `test_full_workflow`), make assertions about outcome.

**NOTE: all of this should first be tested with the local backend only, not with slurm,docker,etc..**
