### ISSUE TITLE
Prevent modifying a task or task-group `version`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1900]
For the moment we redundantly store `version` both in task and task-group. We can decide a bit later whether to fully deprecate `task.version` (ref #1855), but in the meanwhile we have to prevent any mismatch.

In general, the use case where a task or task-group version is edited is not really relevant. For sure it should never happen for tasks that were collected automatically, and for tasks that users added by themselves I think it'd be always best to create a new task with a new version - if needed.

If we keep the possibility of PATCH-ing a task or task-group version, we'll need to make sure we propagate this into as appropriate.

**Comment by jluethi** [comment]
Agreed, we can deactivate the option for users to edit task versions for now
