### ISSUE TITLE
Drop `WorkflowTaskCreateV2.order`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1901]
We currently expose two independent user flows:
1. Append task at the end (default), and change things later by re-ordering tasks.
2. Directly insert task at the expected position

If we find out out that one of the two is not very useful, I suggest we drop it and simplify things.

**Comment by jluethi** [comment]
I'd say we can drop the second option of inserting at an integer-specified order position. Instead, I'd say we can improve the reordering front-end side (e.g. by offering a drag & drop reorder version instead of the current arrow-based approach once the reorder menu is started).
