### ISSUE TITLE
what does it mean to patch / update a task

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#192]
as tasks are now treated as executables and automatically created from the manifest, it makes less sense to allow arbitrary changes to the Task db records.

A user may still want to change the name, but definitely should not change the command or the source.

This issue is just to remember that we'll have to think about this.

**Comment by jacopo-exact** [comment]
what are reasonable use cases? currently the task is loaded from the manifest

**Comment by jluethi** [comment]
Hmm, we (eventually) want users to be able to create custom tasks. In that case, they may have an initial version of the task, run it in Fractal and notice an issue (e.g. they want to add an additional parameter to be parsed through the task to the core function that is called). In that case, they may want to quickly patch their task and run it through Fractal again to test whether the updated version is working as expected within the framework.

Also, may be useful to test a bugfix of e.g. the fractal core tasks before committing it to the repo, no?

**Comment by tcompa** [comment]
@jluethi @gusqgm: let's turn this issue into something more precise.

Questions:
1. Do we want to have a task-update endpoint (and the corresponding client command) available to all users? Note that also the answer "for the moment yes, but we'll have to limit its scope in the future" is also valid.
2. If yes, which ones of the task attributes can the user modify? See list below.
3. If not, should this still exist but be restricted to superusers? Or should it just not exist?


Task attribute list:
* `command`
* `input_type` and `output_type`
* `default_args`
* `meta`
* `source`
* `name`

---

I would say that the user should not be able to modify `source` and `name` (this is especially true for `source`, but currently we also rely on the `name` field). For all the other fields, I have no special opinion.

Just stating the obvious: at the moment there is no "user role" or "access control", that is, any user would be able to modify the `command` of a core task. I guess it is a small risk which we can accept, in the current testing phase.

**Comment by tcompa** [comment]
As of our last discussion:
let's restrict this endpoint to superuser, and allow update of all attributes apart from `source`
