### ISSUE TITLE
Duplicate task-collection folder into local/remote, for SSH case

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1931]
Related to #1881.
High-level goal: if the remote folders are lost, can we recreate all venvs from scratch based on the VM data?

**Comment by jluethi** [comment]
Thanks for the write-up @tcompa . That seems fine by me. I agree that this really should be a common case, so if we don't handle all potential scenarios here automatically, that's acceptable.

The fact that pypi tasks aren't affected by this gives me further confidence that it's fine not to invest more time into this for the time being.
