### ISSUE TITLE
Manifest schema

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#195]
Two minor questions re: https://github.com/fractal-analytics-platform/fractal-server/blob/195df67a803299f42682ab859079645bb4918c00/fractal_server/app/schemas/manifest.py

1. Shouldn't `meta` be `Optional`?
2. Why `ManifestV1` has no attribute `manifest_version`?

**Comment by tcompa** [comment]
I also don't understand the difference between `executable` (in `_TaskManifestBase`) and `command`. But for all these details it's probably easier if we discuss quickly _live_.

**Comment by jacopo-exact** [comment]
> 1. Shouldn't `meta` be `Optional`?

definitely, thanks

> 2. Why `ManifestV1` has no attribute `manifest_version`?

it inherits it from _ManifestBase

I'll give priority to this and add documentation.

**Comment by tcompa** [comment]
> > 2. Why `ManifestV1` has no attribute `manifest_version`?
> 
> it inherits it from _ManifestBase

Trivial question: then why is `task_list` treated differently (it is an attribute of `ManifestV1`)?
