### ISSUE TITLE
Review missing ID autoincrement for sqlite

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1991]
As part of #1934, we need dataset IDs to be unique, even if a dataset is removed.
@ychiucco wrote a test for it (in #1990), which is OK on postgres but fails on sqlite.

Relevant refs:
* https://docs.sqlalchemy.org/en/20/dialects/sqlite.html#using-the-autoincrement-keyword
* https://sqlite.org/autoinc.html

**Comment by ychiucco** [comment]
We've tried
```python
class DatasetV2(SQLModel, table=True):

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_column_kwargs={'autoincrement': True}
    )
```
but nothing changed
