### ISSUE TITLE
Implement new endpoint for replacing `WorkflowTask.task` (part of update-task-version web-client feature)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#2055]
This is meant to make the corresponding web-client feature more atomic, and avoid issues as https://github.com/fractal-analytics-platform/fractal-web/issues/636.

Tentative endpoint URL:
```
POST /api/v2/project/{project_id}/workflow/{workflow_id}/wftask/{workflow_task_id}/replace-task/?task_id={task_id}
```

Request body:
* `args_non_parallel: Optional[dict[str, Any]]`
* `args_parallel: Optional[dict[str, Any]]`

Endpoint logic:
* Check that all input IDs correspond to existing objects
* Update the `WorkflowTaskV2.task_id` foreign-key and refresh the `WorkflowTaskV2.task` relationship.
* Update `args_parallel` and/or `args_non_parallel`, depending on the request body

### NOTE
This process appears as much simpler when performed backend-side, since we don't have to delete/recreate the WorkflowTaskV2 but we can edit it in-place. That's one more reason for extracting this logic from the web-client.

**Comment by zonia3000** [comment]
Seems fine to me. The only thing that I would like to have is receiving the updated workflow task as response.

**Comment by jluethi** [comment]
I like this! If the user set something, let's keep those settings. Otherwise, update to the new config the dev may have updated to.
