### ISSUE TITLE
Fix API rendering of non-UTC timestamps

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#2063]
While deprecating sqlite, we noticed with @ychiucco that there is also a difference in how timezones are handled in asyncpg/psycogp3.
Since we now only support psycopg3, it's best to remove obsolete customizations and use a single approach everywhere.

The relevant documentation is https://www.psycopg.org/psycopg3/docs/basic/adapt.html#date-time-types-adaptation, and it states that:

> Python [`datetime`](https://docs.python.org/3/library/datetime.html#datetime.datetime) objects are converted to PostgreSQL `timestamp` (if they don’t have a `tzinfo` set) or `timestamptz` (if they do).

> PostgreSQL `timestamptz` values are returned with a timezone set to the [connection TimeZone setting](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE),

> PostgreSQL `timestamptz` doesn’t store “a timestamp with a timezone attached”: it stores a timestamp always in UTC, which is converted, on output, to the connection TimeZone setting:

----

Prescriptions for fractal-server:
1. All timestamps that end up into the database must be created _with_ `tzinfo`, and that should be set to UTC.
2. The API must always return timezone-aware timestamps (that can be in UTC or in local timezone - this is not necessarily relevant).

---

Right now, we are handling timestamps correctly in the db but not in the API (which is reflecting the old asyncpg behavior - see e.g. https://github.com/MagicStack/asyncpg/issues/481).

**Comment by jluethi** [comment]
> The API must always return timezone-aware timestamps (that can be in UTC or in local timezone - this is not necessarily relevant).

If we can move towards showing all time zones in local times, that would likely be useful

**Comment by jluethi** [comment]
The part where I most recently noticed this: The server job page shows me the runtimes in local time, but when I open the workflow.log, it shows logs in UTC. But anyhow, I'll open a separate issue on that. I mostly agree with the "let's make sure that the API returns timestamps with time codes.
