### ISSUE TITLE
Review use of `encode_as_utc`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#2082]
Test a job submission, on a locale which is not UTC, and check that "dump" attributes of the `JobV2` currently have the wrong timestamp.

Fix can be either converting to UTC properly or just using the original timezone.

**Comment by ychiucco** [comment]
Dumps timestamp are broken
```
fractal_test_db=# select project_dump from jobv2;
                                      project_dump
----------------------------------------------------------------------------------------
 {"name": "Progetto", "id": 1, "timestamp_created": "2024-11-20T12:05:37.554186+00:00"}
(1 row)

```
The hour is my current hour, but I'm in timezone `+01:00`.
