### ISSUE TITLE
In pyproject, rename `server` script to `fractal-server`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#21]
With the current naming, one should call the executable via the `server` command (in the terminal), which seems too generic.
Should we make it `fractal-server`?

**Comment by jluethi** [comment]
`fractal-server` sounds like a good convention.
The client can be invoked as `fractal` (see here: https://github.com/fractal-analytics-platform/fractal/issues/187), then having `fractal-server` would be logical :)
