### ISSUE TITLE
Validate new-dataset `zarr_dir`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#2127]
![image](https://github.com/user-attachments/assets/9fcd87cb-bc39-4d85-b6b9-b4ab80e91706)
![image](https://github.com/user-attachments/assets/a32182a4-fbff-4c33-9300-14973b6dba92)

**Comment by jluethi** [comment]
> 6. Note that we are anyway moving to a situation where we hope users do not type zarr_dir very often (because of default project-dir-based value), then any choice we make in this issue is a bit less critical than it would be in past versions.

Agreed. But will that validation also apply if a project dir is e.g. `/base/path/to/my weirdly spelled/base/folder`? Or is this just for manual user inputs?

I fully agree with removing leading & trailing whitespace of course! The other parts like 4 & 5 sound conceptually good, until someone comes with base paths that contain spaces, parentheses or such. Should we encourage that? No! Do we want to make it a Fractal requirement that all paths don't contain these special characters? Not sure
