### ISSUE TITLE
Test sending-email feature

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#2149]
* Based on #2013, developed in https://github.com/fractal-analytics-platform/fractal-server/tree/2013-feature-request-inform-admin-when-user-signs-up.
* Minimal example of SMTP container: `docker run --name=mailhog -p 2525:1025 -p 8025:8025 mailhog/mailhog`
* Minimal example of reading email `curl http://localhost:8025/api/v2/messages`
* Minimal example of sending email
```python
import smtplib

sender = "sender@localhost"
recipient = "recipient@example.org"
password = "fakepassword"

with smtplib.SMTP("localhost", 2525) as server:
    server.set_debuglevel(1)
    server.ehlo()
    # server.starttls()   # This fails on mailhog
    server.login(
        sender,
        password=password,
        initial_response_ok=True,
    )
    server.sendmail(
        from_addr=sender,
        to_addrs=recipient,
        msg="\nMessage contents",
    )
```

## Expected behavior

1. Before any login, there is no email
2. After the first oauth login, there is one email
3. After the second oauth login, there is still only one email

**Comment by ychiucco** [comment]
closed by #2151
