### ISSUE TITLE
When collecting tasks with `version=None`, fill `source` with the actual version

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#215]
Right now we have
```python
'source': 'pip:fractal-tasks-core==None',
```

My guess is that we want to show the actual version that was installed.

**Comment by jacopo-exact** [comment]
do we want to give the possibility to leave the version blank and update the package? kind of like tasks-latest...

**Comment by tcompa** [comment]
> do we want to give the possibility to leave the version blank and update the package? kind of like tasks-latest...

My take:
* Yes, you can call the endpoint without specifying any version. In that case, the install command is just `pip install package`.
* The task/env folders should all have a version in their name (i.e. `fractal-tasks-core-1.2.3` is valid, `fractal-tasks-core` or `fractal-tasks-core-latest` are not valid). Having some non-standard name would be confusing, when more than one version is available in Fractal. There are (at least) two ways to achieve this:
    1. Install the package, find the current version, rename the env folder.
    2. Find out the latest available version, then proceed in the standard way with that version specified. This requires a preliminary `pip` call. `pip search` would do it, but it's not available any more. Now we may use something like `pip install package --dry-run  --report /tmp/report.json`, and parse the output to extract the latest version.

**Comment by jacopo-exact** [comment]
Ok.
This can be achieved by splitting installation in download + local install.

```bash
# download without dependencies
pip download --no-deps <pkg>
# install the local wheel
pip install <local pkg>
```

incidentally, this allows us to inspect the package before installation and read the manifest before installation, cf. #250
