### ISSUE TITLE
Define private task

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#223]
private task should only be visible to its owner

**Comment by jluethi** [comment]
This will be interesting.

Users should be able to register a task that is only available to them

**Comment by tcompa** [comment]
What about this issue? If we consider it important, let's define it better. If not, let's close it for now and re-open when we want to implement it.

**Comment by jluethi** [comment]
We should define it more clearly. I've started seeing users at UZH (especially Adrian) add his own tasks and that can quickly get quite messy, if there are 10 development tasks suddenly showing up for everyone.
I'll try to define it better next week

**Comment by tcompa** [comment]
We brainstormed with @mfranzon, and a few points came to mind.

For a task, being "private" may have multiple (possibly overlapping) meanings:

* It is associated to a subgroup of users via database relationships (like projects are).
* It is installed in a folder with a name that includes a specific-user username.
* It is installed by a certain user (ref #686).
* It has a flag that says it belongs to a certain user (or to a subgroup of users).
* It has some file permissions such that only a certain user can run it (e.g. it points to files in the user's home, wit restricted access).

(note that not all of these features can be implemented as part of Fractal - see e.g. the last one)

Each one of these properties may be used for different goals, including:

* Enforcing strict access control (as for projects).
* Sharing private tasks with other users.
* Applying a client-side (e.g. in the web client) filter during visualization of the task list. Examples:
    * Hide private tasks of other users
    * Apply different visual effects to common tasks, my private tasks, other users' tasks.
    * ...

For sure we need to better define "private", and what's its goal. Broadly, a choice seems due between having real access control to tasks (a bit cumbersome, but reasonably well defined) and a "light" feature that is mostly implemented client-side (e.g. to filter the tasks that a user sees as available, but without any actual restriction).

**Comment by jluethi** [comment]
Very good discussion to get more concrete on. Overall, I think I'd come down on a version of this:

> It has a flag that says it belongs to a certain user (or to a subgroup of users).

(in the database or with another method).

> It has some file permissions such that only a certain user can run it (e.g. it points to files in the user's home, wit restricted access).

This would be more of an accident and I would not encourage this approach (e.g. where possible, would be good if users can share tasks with other users without having to worry about file permissions). But if there are ways to use custom tasks (e.g. just register a task with a python env in a users folder with arbitrary permissions), then that task may just not be easily shareable. Not sure that Fractal should get involved in this. Mostly, I'd expect the server to install the tasks in a commonly accessible location.

-----

### On the overall goals:
We can think very broadly and some of it would be premature at the moment. We don't know for example whether we'll be running a single Fractal server for many research groups (=> access control quite important) or individual fractal servers for different groups (less critical). Here are some initial thoughts:

There should be global tasks (i.e. the core tasks we install) as well as user-specific tasks. There are different purposes for user specific tasks:
1. A big purpose is testing for task development => It would be useful to not have all the testing tasks clutter our task lists
2. Users may have actual tasks that are useful to them (and some others). If they become globally useful, they should be installed by the Fractal server admin for everyone. But if users didn't go to the length to make it generally useful, some tasks could stay around as shared tasks. Some of those tasks should actually remain private to those users, i.e. not be visible to others unless explicitly shared (some users may not care much about this, others much more).
3. There may in the future be tasks that are only relevant to certain groups of users (e.g. tasks by a specific research group => a set of users)

-----

### My current conclusions:
If it's feasible without much overhead to have a system with actual access control and sharing of tasks, that seems to scale even to more complex use-cases. If that gets too complex before we know more about our large deployments, I'd also be fine with a way to split the display / listing of tasks into:
1. The core tasks (+ optionally a version choice, as we'll soon have multiple versions of them installed)
2. List of all other tasks (i.e. any user-installed task)

I imagine we'll eventually want full user access control, but that wasn't the reason I brought it up now.

**Comment by tcompa** [comment]
This was addressed, in its first form, as part of #702 - and implemented in #704.

* Tasks now have a `owner` attribute, which can be `None` (-> common tasks) or not `None` (-> "private" tasks).
* For the moment we do not introduce any kind of access control, since the goal of this new feature is to make it easy to display tasks in a clear way on the client side.
* The only place where `owner` actually matters is that a user can only create a custom task if they have either a `username` attribute or a `slurm_user` attribute.
