### ISSUE TITLE
Type of `component` (for the moment: `str`)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#239]
This came up in https://github.com/fractal-analytics-platform/fractal-server/pull/237#pullrequestreview-1175845807.
Let us re-assess it later (as we may want to parallelize over some numeric values..).

**Comment by tcompa** [comment]
To do:
make the call of `sanitize_component` optional, inside `FractalSlurmExecutor.map()`, in case we want to run `executor.map(function, [1, 2, 3])` (AKA with non-string arguments)

**Comment by jluethi** [comment]
Second part is achieved with https://github.com/fractal-analytics-platform/fractal-server/pull/497 => non string components do not fail.
But we will work with str components, because they come from a json file
