### ISSUE TITLE
make sure task collection / installation logger always writes log

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#268]
right now it looks like it depends on the global logging level, and levels higher than debug result in empty log files.

**Comment by jluethi** [comment]
It seems to be writing to the log nicely. If a task collection fails, the error shows up in the log of the `fractal task check-collection 1` output. Formatting could still be improved, but the error is there: https://github.com/fractal-analytics-platform/fractal-server/issues/536

It also shows up on the server side, see this:
<img width="1032" alt="Screenshot 2023-02-24 at 10 39 55" src="https://user-images.githubusercontent.com/18033446/221145160-3ea7ba11-a57f-4739-b4da-2e416e7bbf43.png">

Not sure whether it should still show up in the server terminal, but that's not a big issue. From my side, this issue could be closed.

**Comment by tcompa** [comment]
> Not sure whether it should still show up in the server terminal, but that's not a big issue. From my side, this issue could be closed.

It shouldn't, to be honest. But I agree: it's a very low-priority issue (provided that the information is also there in the DB), and we can forget about it now. After this appears 100 times in real-life tests, we'll be more motivated to fix it - or maybe not ;)

**Comment by jluethi** [comment]
Sounds good, closing the issue then :)
