### ISSUE TITLE
dataset snapshotting brainstorming

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#273]
Warning: This is just an idea.
@mfranzon @tcompa @gbrandino 

It should be possible to take snapshots of datasets after each task is applied. This would allow
* trivial restore of a previous state
* forking workflows
* partial running
all at the same time without keeping N>>1 full copies of the data.

See [rsync snapshots](http://www.mikerubel.org/computers/rsync_snapshots/) for a possible implementation with `cp` and `rsync` only.

Note that we should introduce the concept of workflow working directory, and each time we start a new workflow we pull the correct snapshot into the working directory and start working on it.

**Comment by jluethi** [comment]
Probably quite complex. Discussion relevant for https://github.com/fractal-analytics-platform/fractal-server/issues/128
But probably rsync will not be the way
