### ISSUE TITLE
When are workflows linked to datasets?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#276]
In the current implementation, workflows only know what dataset they run on when workflow apply is called. This logic keeps workflows very flexible and easily shareable between projects with different dataset. The share-ability of workflows is very important, I'm not sure whether there are other areas where we benefit from this.

The question whether we should link them earlier came up for me in 3 areas:
1) Web user stories: Users will create the workflow within a project and expect it to run on the dataset of that project
2) Multiplexing processing: We need to think about how different resources / different acquisition in multiplexing are processed. If there are actually different workflows for different resources, then it's important that this assignment is clear and can't be mixed up (I'll open a separate issues with thoughts on multiplexing workflows)
3) If we want to do inference of potential inputs (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/200), then we'll need to know which dataset a workflow will run before it is submitted

Is there something that would argue against associating workflow with datasets upon their creation? This probably should be something that gets downloaded as part of the workflow (because we want to potentially upload the same workflow to another project with different datasets). Are there other concerns?

**Comment by tcompa** [comment]
Brief (personal and high-level) comment based on last-week meetings:

Establishing DB relationships between workflows and datasets can easily turn into a tricky business, depending on how flexible they need to be. We briefly explored some options (one-to-one, one-to-many, many-to-many) and often hit some roadblock.

When reviewing this, let's also consider the option of moving part of this association to fractal-web. For a given workflow, there could be a toggle-list of "associated" datasets (either the ones that are linked via an existing job, or new ones that the user can add). By selecting one of the datasets, we would access e.g. the corresponding history and then task status (ref https://github.com/fractal-analytics-platform/fractal-server/issues/793).

**Comment by jluethi** [comment]
> When reviewing this, let's also consider the option of moving part of this association to fractal-web. For a given workflow, there could be a toggle-list of "associated" datasets (either the ones that are linked via an existing job, or new ones that the user can add). By selecting one of the datasets, we would access e.g. the corresponding history and then task status (ref https://github.com/fractal-analytics-platform/fractal-server/issues/793).

Based on last week's discussion, I also favor this as the primary direction to investigate. The server keeps its flexibility, but Fractal web offers a nice user experience and ability to show relevant workflow history for a given dataset.
