### ISSUE TITLE
SLURM backend should expose a `stop_workflow_execution` function

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#280]

**Comment by tcompa** [comment]
Quick recap of discussions with @mfranzon

* Each `Executor` object may/should have a `shutdown` method. This is already present in the `class Executor` definition ([here](https://github.com/python/cpython/blob/3.11/Lib/concurrent/futures/_base.py)).
* `ThreadPoolExecutor` already has this method implemented.
* `FractalSlurmExecutor` (or its clusterfutures parent class) doesn't have the `shutdown` method implemented, but it can be implemented (the executor knows about its SLURM job IDs, and it could call `scancel` on all of them, and then cancell all Futures).
* In fractal-server, each workflow execution opens (and then closes) a single Executor object, so that in principle we have the means to stop execution of a single workflow.

Up to there it's all fine, the missing piece is: how could we communicate to the Executor from outside (that is, from a stop-execution endpoint)?

An obvious answer would be to use some kind of socket-based (IPC) communication, but there is a simpler method that may be more appropriate - at least for the `FractalSlurmExecutor`. This executor already opens a monitoring thread, which is used to check whether some condition is met (some pickle file exists, or some job is missing in `squeue`) and trigger some callback function. We could add another method in this thread, that checks whether a certain `shutdown` file exists in the workflow and then calls the `shutdown()` method.

It remains an open question what to do with the `local` backend, because in this case we have no already-present communication mechanism. The same logic of the other backend (i.e. an external monitoring thread) could be implemented, in a custom version of `ThreadPoolExecutor`, but let's re-discuss it.

**Comment by jluethi** [comment]
Let's collect the different requirements for the local executor and implement the shutdown as part of a bigger local executor effort.

**Comment by tcompa** [comment]
This is in principle implemented, via #631, but we'll need to test it in real-life - once released.
