### ISSUE TITLE
Postgres specs

### ISSUE THREAD

**Issue by mfranzon** [fractal-analytics-platform/fractal-server#296]

**Comment by mfranzon** [comment]
## Postgres specs

Fractal-server requires Postgres in production phase as DBMS. 
Installation phase is slight different for each OS. 

Few example:
On **Ubuntu** (20.04-22.04):
```bash
sudo apt update 
sudo apt install postgresql postgresql-contrib
```
It is possible checking the status of the database with `service` or `systemctl` and see that it is **active**.

On **CentOS** (8):
```bash
dnf module list postgresql # to see available version

sudo dnf module enable postgresql:<latest>

sudo dnf install postgresql-server
```
It is necessary also create a database cluster before connecting:
```bash
sudo postgresql-setup --initdb
sudo systemctl start postgresql
sudo systemctl enable postgresql
```
Also in this case check the status, to be sure that the daemon is running correctly.

### Requirements for fractal-server
- Postgres must be reachable from fractal-server service via http (default port 5432)
- An User with permissions grated for registering new users and making CRUD operations on the database.

**Comment by jluethi** [comment]
Minor clarification from discussions with Enrico (& discussed with @mfranzon):
> An User with permissions for registering new users and making CRUD operations on the database.

This means there is an admin user which can register new Fractal users (=> new entries to the user database table), not that we will have different postgres users. The admin user can make CRUD operations on the database.

**Comment by jluethi** [comment]
Also, at the FMI, we'd be running the whole Fractal server in a separate VM from the cluster. Thus, the database doesn't need its own separate VM anymore.

**Comment by tcompa** [comment]
No further action required, closing
