### ISSUE TITLE
Can a user define custom backend executors?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#30]
At the moment the answer is:
> No, fractal users cannot define custom parsl executors. They can only use the ones that are already available on the server (for their specific cluster), or they may ask the fractal admin to add new ones.

We can think about this later, if needed.

**Comment by tcompa** [comment]
Renaming this in view of the new SLURM backend.

Also, from https://github.com/fractal-analytics-platform/fractal-demos/issues/21#issuecomment-1326308014
> Note that the new SLURM backend will be simpler to configure.
> We may still want to have "executors", which will only be defined by the set of (partition name, cpu requirements, memory requirements) -- see https://github.com/fractal-analytics-platform/fractal-server/issues/278. For those executors, reading from a file is trivial.

**Comment by jluethi** [comment]
Moving this discussion here:
Very good point. If we're anyway opening a slurm job per task & parallelization object (e.g. for each well-image that we apply illum_corr to), then we can even consider making this more granular, i.e. exposing CPU & mem options directly. But a set of predetermined executors may be an easy start :)

**Comment by tcompa** [comment]
Closed in favor of #580
