### ISSUE TITLE
In slurm dockerfile, install correct fractal-server version

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#314]
- [ ] Extract the branch name from the `ci.yml` and put it into an env variable `BRANCH_NAME`
- [ ] Modify the install line in the node Dockerfile.

Old version
```
RUN pip3 install https://github.com/fractal-analytics-platform/fractal-server/releases/download/1.0.0b1/fractal_server-1.0.0b1-py3-none-any.whl
```
New version, something like:
```
RUN git clone https://github.com/fractal-analytics-platform/fractal-server
RUN cd fractal-server
RUN git checkout BRANCH_NAME
RUN pip install .
```

(note that there should be a `sed`-like replacement of the variable from within the github workflow)

**Comment by jacopo-exact** [comment]
superseded, as we now use the latest dev code
