### ISSUE TITLE
documentation CI should only run on merge

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#352]
currently the documentation is built upon every commit. It should only build upon merge to the main branch.

**Comment by tcompa** [comment]
Could we just move it to a different YAML file? (that's how we do it in the tasks: https://github.com/fractal-analytics-platform/fractal-tasks-core/tree/main/.github/workflows)

In this way it'd be simple to specify the relevant `on:` section.

**Comment by tcompa** [comment]
(but I don't know if it makes things more complex for combining jobs together, because at the moment tests is needed by coverage, and coverage is needed by docs)

**Comment by tcompa** [comment]
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1, and

> Note: More than one activity type triggers this event. For information about each activity type, see "[Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)." By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. To trigger workflows by different activity types, use the types keyword. For more information, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/articles/workflow-syntax-for-github-actions#onevent_nametypes)."

**Comment by tcompa** [comment]
Closed with #399
