### ISSUE TITLE
How to set up alembic 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#357]
Context: I'm looking for a robust way of reinstalling the server from scratch and re-creating the db. This is useful during testing, where we may have to start afresh a large number of times.

Current procedure:
1. I create a fresh (conda) env and install fractal-server from pip.
2. I want to run `alembic upgrade head`, but first I need to set `script_location` in `alembic.ini`. How do I do?

The actual location is a path within the virtual env, something like
```
script_location = /PATH/TO/ENV/lib/python3.9/site-packages/fractal_server/migrations/
```
but it looks a bit weird to hard-code this path, doesn't it?

Another option is to just copy that folder in my current folder, and then just set `script_location=migrations`. This we can obviously achieve with a simple python script.

What's the best way to proceed? Any other idea?
@mfranzon @jacopo-exact

**Comment by jacopo-exact** [comment]
> The %(here)s variable is provided as a substitution variable, which can be used to produce absolute pathnames to directories and files, as we do above with the path to the Alembic script location. (source: [2])

So something like this:
```
script_location = %(here)s/migrations/
```
mind that I might have missed a `fractal_server/`, please double check.

Ref:
* [1] https://stackoverflow.com/a/51302904/283972
* [2] https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file

**Comment by tcompa** [comment]
After some discussions:
1. It's correct that the migration folder stays within the package, inside the environment.
2. We could provide a script (in main.py or somewhere else) to automatically set the right path, and then expose it via pypoetry. In this way, the sysadmin would only use a command like `fractal-server-setup-db`, without looking for the migration folder inside the venv folder.
