### ISSUE TITLE
New monitoring endpoint: provide all logs

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#369]
https://github.com/fractal-analytics-platform/fractal-server/issues/52#issuecomment-1359409604 covers the essential logging & user feedback by giving a way to see the error messages when something failed. A future enhancement would be to give users access to the logs for each task, e.g. to see if there were any warnings for a given task. I think the core thing here would be access to the .err files.

This is not urgent though. Will also come up as a discussion around the web frontend as well :)

**Comment by tcompa** [comment]
Reference: https://fastapi.tiangolo.com/advanced/custom-response/#fileresponse
