### ISSUE TITLE
Check that SLURM worker is compatible with server

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#375]
Transmit also the server versions (fractal-server and cfut) in the cloudpickle file, and then check that they match on the receiving end (i.e. the SLURM worker running as a user on a node).

**Comment by tcompa** [comment]
Quick question about FMI deployment (@jluethi @gusqgm): do you ever set the `FRACTAL_SLURM_WORKER_PYTHON` env variable?
If not (and if you don't have reasons for doing it), then this issue becomes a bit irrelevant for the moment (we can still implement it, as it takes little, but we would never hit a version mismatch in real life).

---

From the docs
```
FRACTAL_SLURM_WORKER_PYTHON: Optional[str] = None

Path to Python interpreter that will run the jobs on the SLURM nodes.
If not specified, the same interpreter that runs the server is used.
```

**Comment by jluethi** [comment]
Hmm, I've never consciously set this and everything has been running fine on the test setup. We have not deployed to the main cluster yet though.

I'm not fully sure what we're checking here though. We're anyway providing the a full python environment within which the jobs are being run, no?

**Comment by tcompa** [comment]
This is not about the tasks' environments, but rather about the server's one.

In a typical case, the same python interpreter is available both on the machine that runs fractal-server and on the cluster computing nodes. In that case, the slurm submission script looks like
```
...
/path/to/python/that/runs/fractal-server /path/to/task.py ...
```

In some other cases, `/path/to/python/that/runs/fractal-server` could not be available on the computing nodes, and then one should set  `FRACTAL_SLURM_WORKER_PYTHON` to **another** python interpreter that is available over there. And someone should take care of installing fractal-server (and then also clusterfutures) for this latter python interpreter. In this situation, the "install" step of deployment includes both installing fractal-server on its own hosting machine **and** installing it for the python defined in `FRACTAL_SLURM_WORKER_PYTHON`. As a safety check, one can always explicitly verify that there is no version mismatch, any time that fractal-server (via clusterfutures) sends some task to be executed on a remote computing node.

If we stick with the single-interpreter use case, however, this check is always trivially true.

**Comment by jluethi** [comment]
Ah!

And do we need such a server environment even if the machine running the server can submit to slurm directly from there? Because my understanding of the FMI setup is that the server environment is "supposed to be" installed on a local storage of that server machine (the 1016 machine to give it a name). But that 1016 machine should be able to submit to slurm.
These slurm nodes then likely wouldn't have access to the server python environment. In that case, what you describe here would be a fitting solution. Let's briefly discuss tomorrow to also get @gusqgm 's insights here.

**Comment by tcompa** [comment]
> And do we need such a server environment even if the machine running the server can submit to slurm directly from there?

Briefly: yes

>  Let's briefly discuss tomorrow

Great

**Comment by tcompa** [comment]
Note: this should probably be part of https://github.com/fractal-analytics-platform/fractal-server/issues/476

**Comment by tcompa** [comment]
> Note: let's also include the python version (ref [#528 (comment)](https://github.com/fractal-analytics-platform/fractal-server/issues/528#issuecomment-1441734809))

Once again we hit the usual two-different-python-version CI problem (e.g. because the server runs with py3.10 but the remote worker runs with py3.9 on the containers)

**Comment by tcompa** [comment]
This is a broader CI issue (we sometimes run server and remote worker with different python versions), which is not trivial to fix.

Current action in this issue: let's only raise a warning, for python-version mismatch.
