### ISSUE TITLE
Is the Project directory still required?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#378]
Creating a new project requires a project directory (i.e. $PROJ_DIR in example 01) as part of the inputs of the client. As far as I've seen, this directory is empty and nothing appears to get written there. Can we deprecate it?

See:
```
(fractal-client-v1-a6) bash-4.4$ fractal project new --help
DEBUG:asyncio:Using selector: EpollSelector
usage: fractal project new [-h] [-d DATASET] name path

positional arguments:
  name                  Name of new project
  path                  Project directory of new project. New datasets will be written here.

optional arguments:
  -h, --help            show this help message and exit
  -d DATASET, --dataset DATASET
                        Name of new dataset to create. By default, the dataset `default` is created.

```

**Comment by tcompa** [comment]
As part of #475, this directory will host the user-side working directories for job execution, and thus will be clearly useful.
Note that there is an open issue about how to cleanup the server-side and user-side folders: https://github.com/fractal-analytics-platform/fractal-server/issues/474.

The only task left is to document the new folder structure - see https://github.com/fractal-analytics-platform/fractal-server/issues/483.
