### ISSUE TITLE
Jet another library for slurm submission

### ISSUE THREAD

**Issue by mfranzon** [fractal-analytics-platform/fractal-server#380]
https://github.com/facebookincubator/submitit

**Comment by tcompa** [comment]
Very interesting! Let's keep it in mind, in case anything goes wrong with clusterfutures.

Side comment, from their README:
```
Non-goals

    a task queue, this only implements the ability to launch tasks, but does not schedule them in any way.
```

**Comment by tcompa** [comment]
Yet another one: https://covalent.readthedocs.io/en/latest/api/executors/slurm.html. But note that this one doesn't seem to offer a standard Executor interface.
