### ISSUE TITLE
Define/implement standard parsl executors for fractal

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#4]
Merging https://github.com/fractal-analytics-platform/fractal/pull/172 will close fractal-analytics-platform/fractal-server#8, so that we now can specify a given executor for a task (in the manifest, or by modifying the task later on). The list of allowed executors is currently a trivial one, only including `cpu` and `cpu-2` (which are actually identical).

We should discuss on:
1. Which list of standard executors would we include? There could be four combination of `{high,low}-{mem,cpu}-cpu`, and at least one `gpu` one. There can be also a couple of gpu executors, like `gpu-single` (limited to a single gpu node) and `gpu-many`.. or something like this.
2. Where will this information on standard executors be stored (as an hard-coded list of parameters)? There are simple answers to this question, but we should first understand how many of these standards should exist: a unique one? one per lab?
3. How could a user define a fully-custom executor? This is currently not implemented. We should probably move it to another issue, after an assessment of how important it is.

**Comment by tcompa** [comment]
I am not satisfied with the current approach in https://github.com/fractal-analytics-platform/fractal-server/pull/24.

Defining a set of executors (with their given labels, like `cpu`, `gpu`, ...) each time a workflow is submitted looks dangerous. If a user submits two workflows in a row, upon submission of the second one there will be a `parsl.clear()` statement, and a new `parsl.config.Config(...)` one. This means that whatever was provided as a first config is removed and replaced by the new one.

I'm leaning towards a new, more global, approach. The server has a single set of executors, which is defined on startup. The specifics of these executors depend on an environment variable `FRACTAL_PARSL_CONFIG`, which can be set for instance to `local`, or `pelkmanslab` or `custom`. Loading a config from a set of pre-defined ones is the standard behavior (e.g. `local` will point towards two local executors, `cpu` and `cpu-2`, with the second one being useful for testing), while defining a custom one is not currently supported and will be defined later (relevant point: if executors are defined and initialized at server startup, the user cannot really modify with that.. this has to be re-assessed later, possibly leading to not letting the user define their own executors).

This new scheme is somewhat logical: a SLURM cluster comes with a set of (pre-defined) executors available, and users submit their tasks to the relevant ones. 
I will test it and see how it works.

**Comment by tcompa** [comment]
Another solution would be to internally replace the executor names (e.g. `cpu`) with something workflow-related (e.g. `cpu | my worfklow name`).

**Comment by jluethi** [comment]
I like the idea of workflow ideas / workflow-specific executor names better than the fully predefined ones. Users may mostly use our defaults, but we need to find ways to allow power-users to change things eventually when they processed atypical datasets (e.g. suddenly needs much more memory for some specific reason or such).

Each workflow is submitting separate jobs to the server that should have nothing to do with each other, so if we can make the executors unique, that sounds like a good way forward. And would still allow a (to be implemented) way for users to specify custom executors for their workflows if it becomes necessary, without involving any admins for the Fractal server.

**Comment by tcompa** [comment]
> Another solution would be to internally replace the executor names (e.g. `cpu`) with something workflow-related (e.g. `cpu | my worfklow name`).
> 
> EDIT: of course the best is to work with IDs, rather than workflow names, but we can start testing with different workflow names and then switch to IDs.

Something on this line is now in https://github.com/fractal-analytics-platform/fractal-server/pull/24/commits/b934f87b5bf614ade2bf8656a9d1faaa4e7e4449.

SUMMARY
* All executors belong to the same (unique) DataFlowKernel;
* Each executor label has a prefix based on the workflow ID (e.g. `9___cpu`, or `23___gpu`);
* When the first workflow is submitted, a new DFK is created;
* Upon submission of another workflow, new executors are created and added to the existing DFK.

PROS
* There is no risk of different workflows overriding existing executors, thanks to the ID prefix;
* We can have as many executors as we like.

CONS (or something to be understood better)
* Monitoring does not distinguish different workflows --> this probably calls for a custom handling of monitoring information, instead of using parsl built-in pages (the ones shown with `parsl-visualize`). To be honest I couldn't find the relevant information in `monitoring.db` (i.e. which executor was used for a given task), but this should be looked at more carefully.
* The same problem exists for `parsl.log`, which is now a single large file..
* We can have as many executors as we like.. but what is the limit? Can we open 1000 executors? I guess not..
Current fix (https://github.com/fractal-analytics-platform/fractal-server/commit/704c364b11691807836d96a0a2e5d432c1b4026b): shutdown executors by hand, at the end of the workflow. The problem is that when the last executor is switched off, also the server process ends - and we cannot submit workflows any more. This should be fixable, somehow.

More pros&cons are likely there, but this requires a bit more thought.

Take-home message: this is a non-trivial issue.

**Comment by tcompa** [comment]
The last change (i.e. the custom `shutdown_executors` function) was introducing other problems (shutting down executors by hand would also stop the server parsl process, and then it would be impossible to submit new workflows). At the moment the easiest fix is to simply keep all the executors alive (https://github.com/fractal-analytics-platform/fractal-server/commit/96c8e32b8dfea5fe5b5005ee7e649025b09fdf3c).

In principle I expect this new version to "work", meaning that we should be able to submit several workflows (including simultaneously) and they should all run and complete (each one on their own executors). More tests are underway. If this works, I'll suggest we go ahead and merge to `dev`, after a final touch (putting in some more realistic choices for the standard `pelkmanslab` executors).

Other issues are still open: monitoring/logs information should be more granular, and we'll probably still have to prune the number of executors at some point).

**Comment by tcompa** [comment]
The current approach (as of https://github.com/fractal-analytics-platform/fractal-server/commit/ef3c09f11230cca6d00bbd5eb9236950d154c939) was tested on pelkmanslab for:
* `01_cardio_tiny_dataset`,
* `02_cardio_tiny_dataset_with_gpu` (same as the previous one, but also using the `gpu` SLURM partition for labeling),
* `03_cardio_dataset_one_2x2_well_3_channels_10_Z` (same as the previous one, on a larger dataset).

Examples ran through as expected. There were a few stray SLURM jobs, but they ended about 30 seconds after the end of the last task.

**Comment by tcompa** [comment]
Detailed configuration will be defined in https://github.com/fractal-analytics-platform/fractal-server/issues/34.

I'm closing this, after restating the main open questions (which can be used for new issues):
* Parsl information (monitoring and logs) is less transparent, as it is not any more workflow-specific;
* The number of executors is not limited;
* We are not yet handling the (edge) case where two different workflows have the same ID.
