### ISSUE TITLE
Optimize process runner for mid-sized workflows

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#444]
To keep track of this discussion:

> > Another question I had about the process runner:
> > Given that I removed the FRACTAL_SLURM_CONFIG_FILE variable and thus didn't specify any executors anymore, how does the process runner handle "submitting" all the things locally? Will it always run all wells in parallel? Or always run sequentially? I'm wondering whether a power user could set up Fractal on a powerful workstation using the process executor and how larger experiments would then be processed.
> 
> FRACTAL_SLURM_CONFIG_FILE only matters for the SLURM backend, as the variable name says ;)
> The process backend directly submits all tasks (in the correct order) to a [concurrent.futures.ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor). Tasks that have a parallelization_level attribute are run in parallel on multiple threads.
> 
> Important: this is multi-thread parallelization, but probably to get mid-size workflows running on a powerful workstation we would need multi-process one. We would then need to play around with (concurrent.futures.ProcessPoolExecutor)[https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor]. Let's re-discuss about it.

**Comment by jluethi** [comment]
My major concern would be whether mid-sized workflows that could run through on a decent workstation would load too many things into memory at once and thus potentially crash, instead of sequentially processing them. Clearly, our preferred setup for handling large-scale deployments is using SLURM though. But let's keep track of efforts to use the process runner more broadly here.

**Comment by tcompa** [comment]
As a side effect of #377, setting `FRACTAL_RUNNER_MAX_JOBS=1` would automatically remove any parallelization, and running a task over 10 wells would proceed sequentially (well 1, then well 2, then well 3, ...).

**Comment by tcompa** [comment]
> As a side effect of #377, setting `FRACTAL_RUNNER_MAX_JOBS=1` would automatically remove any parallelization, and running a task over 10 wells would proceed sequentially (well 1, then well 2, then well 3, ...).

Note that in this case we would stick with the current multi-thread runner backend, and wouldn't try to add a multi-processing one.

**Comment by jluethi** [comment]
Ah, great idea! The max jobs variable could really be useful in this setting and, depending on usage & size of a workstation, would also be an easy part to tweak, e.g. set it to 5 for a large workstation, but to 1 on a laptop :)

And yes, let's hold off investigating multi-processing for the moment :)

**Comment by jluethi** [comment]
Max jobs is there, so that should cover it for the time being.

We're not pursuing a process runner for the time being.
