### ISSUE TITLE
Revamp users management

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#446]
It's probably betterto have a fresh issue for this feature, related to:
* #403
* #442
* #129 

In our current plan, the way users-management works would be the following:
1. At server startup, a Fractal user ("Fractal user" as in "user of the Fractal server") is created in the database, with default credentials (e.g. username `admin` and password `fractal-is-great`). `admin` is a Fractal superuser. Note that this user doesn't have any `slurm_user` attribute set.
2. Depending on your use-case, different paths are taken:
    * If you want to use Fractal on your own (that is, on your machine, and with no multiple users), you won't need to register any other user. You'll write the default credentials in your client environment variables (or `.env` file), and you are ready to start.
    * If you want to use Fractal in a multi-user way and/or on SLURM, more steps are needed. (A) Acting via the client (`fractal user edit` command) you need to edit the `admin` user (at least to change its password); (B) acting via the client (`fractal user register`), you need to register any other user that should access Fractal. Note that 

The first use case does not require many comments.
Concerning the multi-user use  case:
* Note that this also solves #129, for the moment, because the association between Fractal and SLURM usernames is guaranteed by the admin.
* Registration of new users won't any more be open (as it would be in a public service), but it will be only allowed to the a superuser - ref #403. The same is true for most of the `/users/` endpoints, with the only exception of `/users/me` (which gives to any user the possibility to see their details).
* There can be as many superusers as necessary. One is always the `admin` user, created on startup, but others can exist.

---

Open questions (@mfranzon): what happens on re-starts of the server? Let's make sure we don't try to recreate the `admin` user if it already exists.

**Comment by jluethi** [comment]
Sounds good! I like the strategy. And having a default admin user that needs to set up the other users sounds like a good path forward!
