### ISSUE TITLE
Should we rename the `process` backend?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#464]
This would be a very simple change, but the earlier we do it the less confusion in the future.

My take: I find `process` a bit confusing, I would rather suggest one of
* `local`
* `threads` (because the current one is based on `ThreadPoolExecutor`, and then in principle we may want to add a `processes` one based on `ProcessPoolExecutor`)
* Other ideas?

I think having a choice between `threads/slurm` options (or `local/slurm`) would make the scope of the two backends more clear than when choosing between `process/slurm`. Moreover `process` is a bit ambiguous, since: (1) it could also mean "process" as in "process a workflow"), and (2) it does not say much about the actual backend (which is multithreaded one).

Thoughts?

**Comment by jluethi** [comment]
Good point, it also often confused me. I personally like `local` best, as in that's what you run on your local machine.
If we think there'll be a big gain in introducing a `ProcessPoolExecutor` soon, I can also see why they should be named `threads` and `processes`.

=> all else being equal, I like `local` most at the moment, but also fine with `threads` if you prefer that.
Either is better than the `process` executor :)
