### ISSUE TITLE
What is written as history?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#507]
See overview here: https://github.com/fractal-analytics-platform/fractal-server/issues/506

The goal should be that the history stored is complete enough to trace back exactly how something was processed, with which parameters.

It needs to contain what tasks were run, in what order and whether they succeeded or not.

I wonder: Can we store a list of workflows that were applied to the data (e.g. using the new import/export functionality for workflows here: https://github.com/fractal-analytics-platform/fractal/issues/425)? This should be the complete and reproducible workflow that was applied.
We would only want to add the parts of the workflow that succeeded though. So if there is a 6 part workflow that failed at task 4, we would want to save a workflow containing the first 3 steps. Plus potentially some history that task 4 failed?

I think logs our out of scope (=> go to the actual log files) and we certainly wouldn't store the actual history of the image data.

**Comment by tcompa** [comment]
For the record, this is now covered (at least in a preliminary way) through #803 - which fully specifies a server-side history. This is a structured object, currently serving two goals (represented by one endpoint each):
* Exporting the history of a dataset as a reproducible workflow
* Learning the "current' status of a set of WorkflowTasks "associated" to a dataset

If additional features require additional contents of the history, let's open new issues.

A different issue is what history should go into an ome-zarr, and which component is responsible for preparing it (likely the server) and writing it (likely the tasks). This is deferred to #508
