### ISSUE TITLE
Who is in charge of writing the history?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#509]
See overview here: https://github.com/fractal-analytics-platform/fractal-server/issues/506

This is a bit of a tricky question. I see 3 main places of who could write this history, all with pros & cons:

### 1. Each task writes the history
Tasks write history into the metadata dictionary and the OME-Zarr file?
Or tasks write it in the metadata dictionary, something else writes it in the OME-Zarr file?
Or tasks write history to the OME-Zarr file, the server gets it from there if it's needed for the metadata

Pros:
- Minimal changes to the server

Cons:
- Every task needs to handle this => additional complexity and code repetition across tasks
- Some tasks written by a third party may not write any history

### 2. The `run_fractal_task` [function](https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/fractal_tasks_core/_utils.py) writes the history
The wrapper function that is being used to run the task and already applies the type checking of the inputs, 

Pros:
- Wrapped and abstracted from normal task running
- A single place to update for changes
- Is run as the user => has access to the OME-Zarr file on disk
- Already handles updates to the metadata dictionary, if things should go via there

Cons:
- Do all other task packages need to depend on the large fractal-tasks-core package to get this utils function? 
- What about non-Python tasks? => would need to write this on their own or not have history
- If we want to e.g. save the workflow export here, does this code executed from within the task package have access to all relevant information? It can't make a call to the server. It has access to the task parameters, but also the task version (yes via version of the installed package)?

### 3. The server writes the history

Pros
- Very general solution: Any task that is run by Fractal server will have its history written, independent of task language and how someone implements their task.

Cons:
- Server becomes OME-Zarr specific through its history writing
- The server process (e.g. the fractal user) doesn't have write access to the OME-Zarr file

----

I don't like the raw option 1. Option 2 sounds appealing, but raises some questions (see cons). Also could be a different wrapper approach than `run_fractal_task` of course. Option 3 would be the most general, but also comes with downsides.

One idea (depending on where that history is stored when, see: https://github.com/fractal-analytics-platform/fractal-server/issues/508) could also be to have this split: `run_fractal_task` adds information to the metadata dictionary and we require other tasks to also put some info in there (e.g. a Java task needs to also update that metadata json). Another part then ensures it's written to the OME-Zarr file. Not sure whether such a split would be helpful though (may still allow tasks that don't write any history and doesn't solve the access problem).
An alternative thought is having a "collection" task that is always run after each task (1 per plate), which ensures that the correct history is taken from the metadata file (or added to the metadata file first) and then written to the OME-Zarr. Downside here is that this wouldn't run in our normal setup if any well fails (see discussion on when history is written).

**Comment by tcompa** [comment]
With #803, we implemented option 3 for the server-side history. The rest is still to be decided as part of #508 (maybe this issue can be merged with #508, or a single one can be created out of these two).

**Comment by jluethi** [comment]
I'd say this is covered in the new framing of #508 as "Propagate history from db Dataset to ome-zarr"
