### ISSUE TITLE
Add `Dataset.resource.info` column?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#513]
Branching from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/177

> Should we add a Dataset.resource.info additional attribute? That could be (1) multiplexing cycle label ("monday", "tuesday", ..), or (2) something in {"3D", "3D-illumination-corrected", "2D", ...}.
> * How to update it dynamically during workflow execution (where DB is not known)
> * Related to this: how do we update metadata after a task is over? Probably we should enforce an addition-only policy, with no replacements. This is partly mitigated by points 1 and 2, at least for the problem of doing 3D->2D->3D workflows.
> * Related to this: let's make sure that info information are transferred back to the DB at the end of execution (if they are modified)

**Comment by jluethi** [comment]
And if we add such a column, make this a selection method to choose what input to run on:
the user either provides the full path as an input path (first option to implement, doesn't need the dataset info)
or (more user-friendly for later): The user can select from the available dataset info entries (or just give one as a string that will be available) to choose the dataset resource they want to use (e.g. if they provide "3D", then that allows loading the input_path for 3D images, without needing to know that path)

**Comment by tcompa** [comment]
The most up-to-date discussion is taking place as part of #792, where, for the moment, we never mentioned `Dataset.resources_list`as the appropriate source of information about component lists (but rather the component lists, currently in `Dataset.meta` and eventually in `Dataset.components`).

In my opinion, using resources instead of components does not provide any special benefit:
1. Like any other DB attribute, Dataset resources cannot be modified _during_ execution of a workflow - this would lead to using temporary files/objects, and only writing back to the db after workflow execution completes (either successfully or with an error).
2. Currently we rely on a mix of resource and components. This is not the most clear design choice, to be honest, but it has at least one advantage in that it  allows us to have some higher-level information (resource = folder where the interesting zarr files sit) and some lower-level information (component -> which can be redudant because it is stored for plate/well/image levels, and possibly for 2D/3D modalities, of unregistered/registered images, ...). Using resources as components would immediately force us to merge these two scopes into a single one, which may not be trivial.
3. The complexity of #792 does not change at all if we talk about resources rather than components.

Given there are no clear advantages, I would rather close this issue (at least in its current shape) - and rather spend time discussing the overall status/necessity of Dataset resources (ref #541, or better ideas to revamp the resource status).

**Comment by jluethi** [comment]
> it allows us to have some higher-level information (resource = folder where the interesting zarr files sit) and some lower-level information

This is actually an interesting thought. Let's define the different use-cases better and see if the split into resources & components is still the relevant one. Depending on how we order them, 2 levels may have some relevance (e.g. maybe switching between 2D and 3D should be switching between resources?)

**Comment by tcompa** [comment]
As part of V2 work, we are dropping the `resource` table.

Closing this issue, since it is (or soon will be) obsolete.
