### ISSUE TITLE
Slurm GPU configuration

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#518]
The way we're currently specifying what a GPU executor is will likely not work yet at FMI. Just learned today that, when running jobs on the GPU partitions at FMI, one needs to specify more about what GPUs are required for the job. Otherwise, it runs a CPU job on the GPU node.

Will collect more information on what additional slurm parameters we'll need to specify to cover this and follow up here. This issue is just so we don't forget about this

**Comment by jluethi** [comment]
To request GPU usage at FMI, one needs to specify the following:
`--gres=gpu`

A valid option would be:
`SBATCH --gres=gpu:v100:1`

If we don't care about which GPU model is used, we can also specify the following to request a GPU with a given amount of RAM:
`SBATCH --gres=gpu:1 --constraint=gpuram48gb`

@tcompa Do I understand the doc [here](https://fractal-analytics-platform.github.io/fractal-server/reference/fractal_server/app/runner/_slurm/) correctly that I can provide `extra_lines` of attributes for an executor? How would those need to be structured (do we need to specify `extra_lines` or just the parameter names like `gres`)? And could we do something like `SBATCH --gres=gpu:1 --constraint=gpuram48gb` with that?

**Comment by tcompa** [comment]
By the way, if the `gres` or `constraint` options are relevant, we should include them in the "standard" attributes. It's good to have `extra_lines` for testing, but let's make everything as explicit as possible if it's part of a known use case.

**Comment by jluethi** [comment]
Ah, thanks for the usage instructions! Would be great to add this to the documentation (or link to this issue for it).

I'll test this at FMI and once we know how it will actually be used, we can add it as an explicit option, that's a good idea :)

**Comment by jluethi** [comment]
That would be useful.

The 2 parameters that were relevant for FMI are:
`gres`: Takes a string value, e.g. `gpu:1`.
`constraint`: Takes a string value, e.g.`gpuram32gb`

I don't think there are Fractal-side ways to verify these parameters well, they will be quite deployment specific. If it's something that can be set up by the admin, the would be optimal. i.e. when users request a GPU, an admin can set up a list of options that will be set by default and, at the FMI, they result in the following 2 lines to be added:
```
#SBATCH --gres=gpu:1
#SBATCH --constraint=gpuram32gb
```

If a user knows what they are doing, they could overwrite the constraint with `gpuram48gb`. But mostly, they should not touch this parameter.

**Comment by tcompa** [comment]
@jluethi could you review this issue and close if appropriate? Thanks

**Comment by jluethi** [comment]
I can confirm that the new `gres` and `constraint` settings work on the FMI cluster as intended :)

I set them the following way in the config.json:

```
    "gres": "gpu:1",
    "constraint": "gpuram32gb",
```
