### ISSUE TITLE
Improve logging & have centralized user feedback

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#52]
Placeholder issue to discuss logging efforts.

Main goal: Have a centralized information of very selective logging information that we can expose to the user, e.g. the actually relevant errors on different levels (the server errors, but also things like out of memory errors that may trigger them).

Inspired by https://github.com/fractal-analytics-platform/fractal-server/issues/51#issuecomment-1247722660
As discussed there, let's discuss this further once the parsl executors are better defined

**Comment by jluethi** [comment]
Great overview! I we have those things nicely logged to a defined place, that will make debugging much easier :)

**Comment by tcompa** [comment]
As of #327, the job endpoint exposes quite a few more information - both for running or failed workflows. As soon as the client is aligned (see https://github.com/fractal-analytics-platform/fractal/pull/350), we should review the current status-query feature and close this issue (or transform it into more specific goals).

**Comment by tcompa** [comment]
Status update:
1. Logfiles are written by each task into the same workflow directory, with deterministic filenames (#315). There are two kinds of files:
    * stdout/stderr of the task (note that stdout is typically empty, while stderr includes both task's logs and error tracebacks)
    * stdout/stderr of the SLURM job, which are only useful to detect SLURM job failures
2. All those logfiles are owned by the user, and currently have 777 permissions (#317).
3. In the same folder, we also have the sbatch submission scripts - once again with deterministic filenames (#284, #363).
4. When the execution of a task raises an error (#105,#327):
    * The error is captured by fractal-server,
    * The workflow execution is stopped,
    * The job status is set to `failed`,
    * The error traceback (essentially the task's stderr file) is stored as part of the job object in the db, so that the client can ask for this information (#281).
5. When another error takes place (typically the SLURM job fails for some other reason, or is canceled), we are currently unable to catch it within fractal-server (#343). A proof-of-principle solution is in #367, but it depends on [ongoing updates in clusterfutures](https://github.com/sampsyo/clusterfutures/pull/19).

If there are other required features that are not covered in open issues like #317 and #343, let's open them. If not, let's close this one in favor of #317 and #343.

**Comment by jluethi** [comment]
@tcompa Great summary of the amazing progress we've been making on the logging front! 👏🏻👏🏻👏🏻

Besides the minor https://github.com/fractal-analytics-platform/fractal/issues/364 on formatting, I think this covers what'd we'd want to have now. 

A future enhancement would be more general log access via the client, see https://github.com/fractal-analytics-platform/fractal-server/issues/369

But this issue has been successfully addressed now! Thanks for the great work on it!
