### ISSUE TITLE
Drop python 3.8 support

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#520]
The original plan was to roughly align with https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table.

**Comment by tcompa** [comment]
Note: this requires also an update to the docker containers and tests, to make sure that they all use 3.9 (there are some hardcoded 3.8 in the tests).

**Comment by jluethi** [comment]
Sounds good to me. I'd favor also dropping it in the tasks and changing the examples to work with Python 3.9 :)
