### ISSUE TITLE
Add `Task.docs_info` and `Task.docs_link`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#549]
This would be an optional field, that would mostly be present for tasks collected from fractal-tasks-core package.
The MIP task, for instance, would have this value: "https://fractal-analytics-platform.github.io/fractal-tasks-core/api_files/fractal_tasks_core.cellpose_segmentation.html#fractal_tasks_core.cellpose_segmentation.cellpose_segmentation".

The nice consequence is that when browsing tasks in the web client we would be only one click away from the docs.

An obvious requirement is that docstrings of the tasks are detailed and precise.

**Comment by tcompa** [comment]
A caveat about this: for the moment, we are not publishing documentation for multiple versions of fractal-tasks-core, but only for the latest release. This means that `task.info` may point towards an out-of-date doc page.

How should we proceed?
Should we add the `task.info` column right now and accept that it may be out-of-date, or should we first move to a multiple-versions fractal-tasks-core documentation (e.g. via https://github.com/sphinx-contrib/sphinxcontrib-versioning) before introducing this new field?

**Comment by tcompa** [comment]
A better solution is probably to store the full docstring of a task in the manifest, and then set it as a DB task attribute (e.g. `Task.info`). In this way, each package will come with its own correct version of the docstring, and we won't hit the "which version are you using?" issue.

**Comment by jluethi** [comment]
Hmm. Yes, I like the idea that the user would never actually go to the documentation in a regular case, because we show all relevant information on fractal web directly.

Nevertheless, we should link to the task documentation from some part of fractal-web. For things like: Getting an overview of what the different tasks do, maybe we have more extensive usage documentation in the fractal-tasks-core doc page at some point.

But if we get all the core task related info directly into fractal web, that makes versioned task documentation a bit less important.

**Comment by tcompa** [comment]
We could simply set `task.info` to something like
```
See fractal-tasks-core documentation at https://fractal-analytics-platform.github.io/fractal-tasks-core (warning: the link may point to a different package version from the one used in this task).

DOCSTRING:
    Create a OME-NGFF zarr folder, without reading/writing image data

    Find plates (for each folder in input_paths)
        * glob image files
        * parse metadata from image filename to identify plates
        * identify populated channels

    Create a zarr folder (for each plate)
        * parse mlf metadata
        * identify wells and field of view (FOV)
        * create FOV ZARR
        * verify that channels are uniform (i.e., same channels)

    :param input_paths: TBD (common to all tasks)
    :param output_path: TBD (common to all tasks)
    :param metadata: TBD (common to all tasks)
    :param image_extension: Filename extension of images (e.g. `"tif"` or
                            `"png"`)
    :param image_glob_patterns: If specified, only parse images with filenames
                                that match with all these patterns. Patterns
                                must be defined as in
                                https://docs.python.org/3/library/fnmatch.html,
                                e.g. `image_glob_pattern=["*_B03_*"]`.
    :param num_levels: Number of resolution-pyramid levels
    :param coarsening_xy: Linear coarsening factor between subsequent levels
    :param allowed_channels: A list of channel dictionaries, where each channel
                             must include the ``wavelength_id`` key and where
                             the corresponding values should be unique across
                             channels.
    :param metadata_table: If equal to ``"mrf_mlf"``, parse Yokogawa metadata
                           from mrf/mlf files in the input_path folder; else,
                           the full path to a csv file containing
                           the parsed metadata table.

```

**Comment by jluethi** [comment]
That sounds good!

**Comment by jluethi** [comment]
When we tackle this: Can we also think about a way the manifest or the user registering a task can provide a relevant link that would be shown prominently?

Motivation: 
The scmultiplex package now became public: https://github.com/fmi-basel/gliberal-scMultipleX
I'll also install those tasks developed at the FMI by Nicole, Enrico & co at UZH. We want users to understand what tasks they are using, be able to cite and acknowledge them. As the best way to do this may vary by package, the easiest would be if the info page then just links to the repo page => people can put citation info, contributors etc. on their github page

**Comment by tcompa** [comment]
Current plan:
- [ ] Merge updated fractal-common (https://github.com/fractal-analytics-platform/fractal-common/issues/90)
- [ ] Add `docs_info` and `docs_link` fields to `Task` (both `Optional[str] = None`)
- [ ] Review task collection: in `create_package_environment_pip` function, while looping over `for t in task_pkg.package_manifest.task_list:`, we already include all fields via `this_task = TaskCreate(**t.dict(), ...)`. In principle this will also include the new fields, but let's make sure it works.
- [ ] Update tests: I think the easiest is to modify `tests/data/dummy_package_with_args_schemas/fractal_tasks_core_alpha/__FRACTAL_MANIFEST__.json` (by adding the two new fields to each item of `task_list`), and then updating the wheel with `poetry build` (note: the wheel must be committed). At that point, a test like `test_background_collection_with_json_schemas` should produce tasks which have the two new fields set (rather than `None`).
- [ ] Add migration/changelog to the PR


Refs:
* https://github.com/fractal-analytics-platform/fractal-common/issues/90
* https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/405
* https://github.com/fractal-analytics-platform/fractal/issues/531
