### ISSUE TITLE
Where are `n_parallel_ftasks_per_script` and `n_ftasks_per_script` defined?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#577]
As per #572 (the preliminary step towards #493), we may have a variable with a name like `n_parallel_ftasks_per_script` which defines the number of Fractal tasks that should be executed in parallel as part of the same SLURM job.

Question: where do we expect this variable to be set?

Examples:
* Global variable, for the whole fractal-server instance.
* One variable value for each operation mode in the SLURM configuration file - see #576.
* Variable is defined for each task, in the database.
* Variable is specified by the user each time they add a task to a workflow.
* ...

The same question holds for `n_ftasks_per_script`.

**Comment by tcompa** [comment]
Just to clarify: "global" means "per-task but not per-workflowtask", right?
Cause my understanding is that each task (say create-ome-zarr, or cellpose) will have a very different value.

**Comment by tcompa** [comment]
To facilitate the discussion, here are some requirements and options.

Requirements:
1. During execution of a Workflow, we need to know the value of `n_ftasks_tot` for each WorkflowTask. This is already known, since it it the number of components (e.g. whole-well images) in the dataset metadata.
2. During execution of a Workflow, we need to know the value of `n_ftasks_per_script` for each WorkflowTask.
3. During execution of a Workflow, we need to know the value of `n_parallel_ftasks_per_script` for each WorkflowTask.

Options for setting `n_ftasks_per_script` and `n_parallel_ftasks_per_script` (not mutually exclusive, since some granularity will always be needed and defaults are not enough for that): 
4. Global configuration variables for each fractal-server instance.
5. Per-workflow definition upon submission for execution.
6. Default values for each Task, coming from the fractal-tasks-core manifest.
7. Required attributes of a WorkflowTask: they become two columns of the `WorkflowTask` database table, and we always have to set them during the usual create-workflow-task or edit-workflow-task operations.
8. Optional attributes of a WorkflowTask: they become two nullable columns of the `WorkflowTask` database table, and if we do not set them during the usual create-workflow-task or edit-workflow-task operations then there we will need to be some other source.
9. ..

Let's complete this list of options, in case I missed some, and then for each one of the two relevant variables (`n_ftasks_per_script` and `n_parallel_ftasks_per_script`) we need to list all options that can be used in a priority order.
Random example:
```
n_ftasks_per_script: 8, 4
n_parallel_ftasks_per_script: 6, 7
```

Note that having more than two options per variable already seems a bit risky, in terms of clarity.

**Comment by tcompa** [comment]
I think that the source of this difficult choice is the following:
* We want the user to know at little as possible about this (that is, we need solid defaults)
* The values of `n_ftasks_per_script` and `n_parallel_ftasks_per_script` must be correlated with each other (i.e. we have to set them together in order to make a reasonable choice)
* They must be correlated with `n_ftasks_tot` (e.g. 10 or 400 wells)
* They must be correlated with the specific task (e.g. cellpose vs yokogawa-to-zarr)

**Comment by tcompa** [comment]
My best proposal at the moment is to use the current behavior (one job per task) as the default, and then modify the relevant variables only for specific cases (i.e. treating 400 wells).

This would be something like
```
n_ftasks_per_script: 4 (global default, equal to 1), 8 (overridable for each task, with N atomic operations)
n_parallel_ftasks_per_script: 4 (global default, equal to 1), 8 (overridable for each task, with N atomic operations)
```
(where N is the number of parallel tasks in the specific workflow)

**Comment by jluethi** [comment]
Priorities:
8 (optional overwrite by the user in the workflow task)
6 (task default => meta attribute)
9 (heuristics)

Example:
Most tasks have no defaults set. Cellpose will have a default for `n_parallel_ftasks_per_script = 1`.
A user could set `n_ftasks_per_script` in the meta args of any task. They could also set `n_parallel_ftasks_per_script` in the meta args (that would overwrite the default set by the task).
If nothing is set, the heuristic provides a value.

Concern:
Meta is a free-field dictionary. Different runners pick up different things.
Parallelization level key-value is treated in special way (i.e. cannot be overwritten)
Are we adding 2 new reserved keywords? Do they need special object protection?
=> formal requirements for those needed (=> suggestion by @tcompa )


----

## How does the heuristic work?

**Will require some additional parameters:**
How many cores do the nodes on the cluster have? (smallest node/node we want to use)
How much memory do the nodes we want to use have?
+ associated partitions
Getting rid of executors decreases portability of the manifest. Somewhere we need to define partitions for GPUs, CPUs => GPU True/False attribute for tasks (overwritable). Our config defines specific rules for GPU & CPU.
[=> kinda an executor]
On FMI side, we'd need to specify additional extra-lines for GPU request

**What does each task need to specify?**
CPUs required
Memory required
GPU: True/False
Partition name (through GPU True/False)
Runtime (optional)


**What does each workflow task need**
All form task
Extra lines
WORKER_INIT


**What's in the manifest?**
Whatever is not optional for tasks (e.g. CPUs, Memory, GPU Flag)
Partition name is loaded from config
runtime is optional


Some default nb_tasks_per script

Scenarios, how do we want to run them by default (for Yokogawa to Zarr):
1 task => 1 job, `n_ftasks_per_script` = 1, `n_parallel_ftasks_per_script` = 1
10 tasks => 1 job, `n_ftasks_per_script` = 10, `n_parallel_ftasks_per_script` = 10 (depending on what cluster resources allow)
10 tasks => 2 job, `n_ftasks_per_script` = 5, `n_parallel_ftasks_per_script` = 5 (depending on what cluster resources allow)
400 tasks  => 10 job, `n_ftasks_per_script` = 40, `n_parallel_ftasks_per_script` = 5 

We need to differentiate between small and large workflow (how many wells)
We first set `n_parallel_ftasks_per_script` based on slurm config & task requirements (what is still possible to run on a node)
How do we get `n_ftasks_per_script`? Do we have some target value for number of jobs running? (e.g. goal to have max. 20 jobs)


Scenario 1:
50 tasks, `n_parallel_ftasks_per_script` = 5 => `n_ftasks_per_script` = 5

Scenario 1:
200 tasks, `n_parallel_ftasks_per_script` = 5 => `n_ftasks_per_script` = 20
=> overall jobs are capped at a max value


For cellpose, we overwrite `n_parallel_ftasks_per_script` to 1 (or 2)


**Open question:** 
Do we always want to run with highest `n_parallel_ftasks_per_script` possible? Or stay smaller (e.g. 5-10) to get deployed faster [how greedy do we get]
Would the user need to know about the global target value?
Do we have different defaults for number of tasks in a config file by the admin?

**Comment by tcompa** [comment]
As per our last discussion with @jluethi @mfranzon @gusqgm 

Whenever we are running a parallel task (note: non-parallel tasks are simple instances of the more general cases described here), at some point inside `fractal_server.runner.submit_workflow` we call `executor.map(function, component_list)`. The executor may be `concurrent.futures.ThreadPoolExecutor` or `fractal_server.app.runnner._slurm.FractalSlurmExecutor`, and it takes care of executing `function` for the given arguments and returning the results.
The plan is that `FractalSlurmExecutor.map` method will look like
```python
def map(self, function, ...):
    # (1) perform heuristics to set some required parameters
    # (2) run function
```
and we are now to define point `(1)` - while `(2)` is mostly explored in #572.

Here is an example of how the heuristics block could look like. This is not meant to be the actual one (e.g. we may choose different inputs, or different logic), but it should serve as a template for proposing other examples.

```
## INPUTS ##

OPTIONAL: n_ftasks_per_script, n_parallel_ftasks_per_script
    These come from optional WorkflowTask attributes (they can only be set in
    pairs, not one by one)
REQUIRED: n_ftasks_tot
    This is equal to `len(component_list)`, and it is alwasy known
REQUIRED: cpus_per_task
    This may come from different sources, see priority list below
REQUIRED: mem_per_task
    This may come from different sources, see priority list below
REQUIRED: slurm_mem_per_node, slurm_cpus_per_node
    These are fractal-server configuration variables, specified by the admin in
    a configuration file (after learning about the SLURM configuration on a
    specific cluster).
REQUIRED: target_number_of_jobs
    This is a fractal-server configuration variable, specified by the admin in
    a configuration file (after learning about the SLURM configuration on a
    specific cluster).

## HEURISTICS / BRANCH 1 ##
If n_ftasks_per_script, n_parallel_ftasks_per_script are set, then we need to
validate this parameters set.
1st check: n_parallel_ftasks_per_script*cpus_per_task must be <= slurm_cpus_per_node
2nd check: n_parallel_ftasks_per_script*mem_per_task must be <= slurm_mem_per_node
3rd check: math.ceil(n_ftasks_tot / n_ftasks_per_script) must be <= target_number_of_jobs
If all checks pass, then return.

## HEURISTICS / BRANCH 2 ##
If n_ftasks_per_script, n_parallel_ftasks_per_script are not set, then we need
to compute them.

## HEURISTICS / BRANCH 2a ##
If n_ftasks_tot < target_number_of_jobs:
    n_ftasks_per_script=1
    n_parallel_ftasks_per_script=1

## HEURISTICS / BRANCH 2b ##
If n_ftasks_per_script, n_parallel_ftasks_per_script are not set, then we need
to compute them. Here is an example that independently maximizes
n_parallel_ftasks_per_script and minimizes n_ftasks_per_script, given some
constraints, and then reduces n_parallel_ftasks_per_script if needed.

n_ftasks_per_script = math.ceil(n_ftasks_tot // target_number_of_jobs)

max_parallel_based_on_cpus = slurm_cpus_per_node // cpus_per_task
max_parallel_based_on_mem = slurm_mem_per_node // mem_per_task
n_parallel_ftasks_per_script = min(max_parallel_based_on_cpus, max_parallel_based_on_mem)
n_parallel_ftasks_per_script = min(n_parallel_ftasks_per_script, n_ftasks_per_script)

## OUTPUTS ##
n_ftasks_per_script
n_parallel_ftasks_per_script
```

The priority list we discussed (repeated from the comment above) includes the following sources for `n_parallel_ftasks_per_script` and `n_ftasks_per_script` (highest to lowest priority):
* WorkflowTask attributes, as explicitly set by the user;
* Task attributes (either explicitly set by the user or coming from the manifest defaults);
* The heuristics logic.

**Comment by jluethi** [comment]
Very good overview of the heuristic approach & the priorities, thanks @tcompa !

**Comment by jluethi** [comment]
Content feedback on the heuristic approach:

```
## HEURISTICS / BRANCH 1 ##
If n_ftasks_per_script, n_parallel_ftasks_per_script are set, then we need to
validate this parameters set.
1st check: n_parallel_ftasks_per_script*cpus_per_task must be <= slurm_cpus_per_node
2nd check: n_parallel_ftasks_per_script*mem_per_task must be <= slurm_mem_per_node
3rd check: math.ceil(n_ftasks_tot / n_ftasks_per_script) must be <= target_number_of_jobs
If all checks pass, then return.
```

I think check 3 should just raise a (big) warning. i.e. a user can run things in a way that does not follow the heuristic goals of `target_number_of_jobs`. They are warned of this an it's their risk whether that's inefficient or will stop accepting jobs from them.

```
## HEURISTICS / BRANCH 2a ##
If n_ftasks_tot < target_number_of_jobs:
    n_ftasks_per_script=1
    n_parallel_ftasks_per_script=1
```

I'd have a different default here:
2a)
1st check: What's a reasonable / the max* `n_parallel_ftasks_per_script` that can run on the given nodes of the cluster, given the CPU & memory settings? => `n_parallel_ftasks_per_script` = X
2nd check: Is ceil(n_ftasks_tot / n_parallel_ftasks_per_script) < target_number_of_jobs
If yes, run with `n_parallel_ftasks_per_script` = X, `n_ftasks_per_script` = X
=> Runs all the jobs in parallel, in a few jobs

If no => HEURISTICS / BRANCH 2b
Choose highest reasonable/possible `slurm_cpus_per_node`, `slurm_mem_per_node` => run as described above.

Not fully sure whether this is all for 2b or there should be a 2c / separate condition.

---

* reasonable vs max `slurm_mem_per_node`, `slurm_cpus_per_node`:
If our max node size is 16 CPU cores, 62 GB of RAM, requesting max node size is reasonable.
At FMI, there are fewer, but much bigger nodes (e.g.192 CPU cores, 805 GB RAM). In that case, we may target something smaller (e.g. aim for 48 Cores, 200 GB max.) to avoid having to wait too long.

If a user for some reason would want to run something that required 250 GB of RAM per task (I don't think that should happen, but 🤷🏻‍♂️), it should be possible to run this (likely with `n_parallel_ftasks_per_script` = 1 and a high `n_ftasks_per_script`) => 2c edge case?
How would we specify reasonable max. node size vs. actual max or do we not fix an actual max?

**Comment by tcompa** [comment]
Small (side-)comment:

> I think check 3 should just raise a (big) warning. i.e. a user can run things in a way that does not follow the heuristic goals of target_number_of_jobs. They are warned of this an it's their risk whether that's inefficient or whether slurm will stop accepting jobs from them.

We don't currently have a way to provide feedback from inside the runner (nor I see an obvious way to do it, because we will hit this point while running tasks in background). We can add a warning line to the logs, but I would hardly call it a big warning.

**Comment by tcompa** [comment]
Re: reasonable/max (@jluethi)

Are you thinking about having twice as many variables (a `max_` one which is a hard constraint and a `target_` one which is a soft constraint)?
If so, let's use these variable names to turn the scheme into an explicit definition - I can try to do it, but tomorrow ;)

**Comment by tcompa** [comment]
Hi @jluethi, I am trying to compile your suggestions into something explicit and I'm not getting what's "reasonable" in this comment:
> 1st check: What's a reasonable / the max* n_parallel_ftasks_per_script that can run on the given nodes of the cluster, 

Here is a concrete example to look at, below. The question is how is XXXX defined.

```python
import math
import pytest
import logging
from devtools import debug


def heuristics(
        *,
        n_ftasks_per_script: int | None,  # Optional WorkflowTask attribute
        n_parallel_ftasks_per_script: int | None,  # Optional WorkflowTask attribute  # noqa
        n_ftasks_tot: int,  # Length of the component list, always known
        cpus_per_task: int,  # Task requirements (multiple possible sources)
        target_cpus_per_job: int,  # Fractal configuration variable (soft)
        max_cpus_per_job: int,  # Fractal configuration variable (hard)
        mem_per_task: int,  # Task requirements (multiple possible sources)
        target_mem_per_job: int,  # Fractal configuration variable (soft)
        max_mem_per_job: int,  # Fractal configuration variable (hard)
        target_num_jobs: int,  # Fractal configuration variable (soft)
        max_num_jobs: int,  # Fractal configuration variable (hard)
        ) -> tuple[int, int]:

    # TODO: memory may come as a string, with units. Here we should parse it,
    # and convert it to a given unit (say MB)

    # Branch 1
    if bool(n_ftasks_per_script) != bool(n_parallel_ftasks_per_script):
        raise ValueError(
                "n_ftasks_per_script and n_parallel_ftasks_per_script must "
                "be both set or both unset"
                )
    if n_ftasks_per_script and n_parallel_ftasks_per_script:
        if n_parallel_ftasks_per_script > n_ftasks_per_script:
            logging.warning(
                    "Setting n_parallel_ftasks_per_script="
                    f"n_ftasks_per_script={n_ftasks_per_script}"
                    )
            n_parallel_ftasks_per_script = n_ftasks_per_script
        if n_parallel_ftasks_per_script * cpus_per_task > target_cpus_per_job:
            logging.warning("Requesting more cpus than expected")
        if n_parallel_ftasks_per_script * cpus_per_task > max_cpus_per_job:
            raise ValueError("Requesting more cpus than allowed")
        if n_parallel_ftasks_per_script * mem_per_task > target_mem_per_job:
            logging.warning("Requesting more memory than expected")
        if n_parallel_ftasks_per_script * mem_per_task > max_mem_per_job:
            raise ValueError("Requesting more memory than allowed")
        num_jobs = math.ceil(n_ftasks_tot / n_ftasks_per_script)
        if num_jobs > target_num_jobs:
            logging.warning("Requesting more jobs than expected")
        if num_jobs > max_num_jobs:
            raise ValueError("Requesting more jobs than allowed")
        return n_ftasks_per_script, n_parallel_ftasks_per_script

    # Branch 2
    reasonable_n_parallel_ftasks_per_script = XXX    # <--- THIS IS THE VARIABLE I DON'T UNDERSTAND
    if math.ceil(n_ftasks_tot / reasonable_n_parallel_ftasks_per_script) <= target_num_jobs:  # noqa
        n_parallel_ftasks_per_script = reasonable_n_parallel_ftasks_per_script
        n_ftasks_per_script = reasonable_n_parallel_ftasks_per_script
    else:
        n_ftasks_per_script = math.ceil(n_ftasks_tot / target_num_jobs)
        n_parallel_based_on_cpus = target_cpus_per_job / cpus_per_task
        n_parallel_based_on_mem = target_mem_per_job / mem_per_task
        n_parallel_ftasks_per_script = min(n_parallel_based_on_cpus, n_parallel_based_on_mem)  # noqa
        n_parallel_ftasks_per_script = min(n_parallel_ftasks_per_script, n_ftasks_per_script)  # noqa

    return n_ftasks_per_script, n_parallel_ftasks_per_script


@pytest.mark.parametrize(
        "n_ftasks_per_script,n_parallel_ftasks_per_script",
        [
            (None, None),  # use the heuristics
            (20, 1),  # ask for 20-tasks job with no parallelism
            ]
        )
@pytest.mark.parametrize(
        "n_ftasks_tot,cpus_per_task,mem_per_task",  # task properties
        [
            (1, 1, 7000),  # yokogawa-to-zarr task for 1 well
            (10, 1, 7000),  # yokogawa-to-zarr task for 10 wells
            (400, 1, 7000),  # yokogawa-to-zarr task for 400 wells
            (1, 16, 63000),  # cellpose task for 1 well
            (10, 16, 63000),  # cellpose task for 10 wells
            (400, 16, 63000),  # cellpose task for 400 wells
            ]
        )
@pytest.mark.parametrize(
        "max_cpus_per_job,max_mem_per_job,max_num_jobs",  # cluster configuration  # noqa
        [
            (16, 64000, 1000),  # nodes with 16 CPUs, 64G memory, max 1000 jobs
            (192, 805000, 100),  # nodes with 192 CPUs, 805G memory, max 100 jobs  # noqa
            ]
        )
def test_heuristics(
        n_ftasks_per_script: int | None,
        n_parallel_ftasks_per_script: int | None,
        n_ftasks_tot: int,
        cpus_per_task: int,
        max_cpus_per_job: int,
        mem_per_task: int,
        max_mem_per_job: int,
        max_num_jobs: int,
        ):
    debug(n_ftasks_per_script)
    debug(n_parallel_ftasks_per_script)

    target_cpus_per_job = int(max_cpus_per_job * 0.75)
    target_mem_per_job = int(max_mem_per_job * 0.75)
    target_num_jobs = int(max_num_jobs * 0.75)

    n_ftasks_per_script, n_parallel_ftasks_per_script = heuristics(
            n_ftasks_per_script=n_ftasks_per_script,
            n_parallel_ftasks_per_script=n_parallel_ftasks_per_script,
            n_ftasks_tot=n_ftasks_tot,
            cpus_per_task=cpus_per_task,
            target_cpus_per_job=target_cpus_per_job,
            max_cpus_per_job=max_cpus_per_job,
            mem_per_task=mem_per_task,
            target_mem_per_job=target_mem_per_job,
            max_mem_per_job=max_mem_per_job,
            target_num_jobs=target_num_jobs,
            max_num_jobs=max_num_jobs,
    )
    debug(n_ftasks_per_script)
    debug(n_parallel_ftasks_per_script)
````

**Comment by tcompa** [comment]
As per our last discussion with @jluethi, here is a plan for a revamped heuristics (the one below is the part where the output parameters were not already provided as an input, not the part where we only need to validate them):
* Branch N
    * Set `n_parallel_ftasks_per_script` by aiming for target cpu/mem.
    * Given `n_parallel_ftasks_per_script`, set `n_ftasks_per_script=n_parallel_ftasks_per_script` (meaning that there is no "internal queue" inside jobs)
    * If  we are under the target job number, return.
* Branch N+1 (if branch N failed)
    * Set `n_parallel_ftasks_per_script` by aiming for max cpu/mem.
    * Given `n_parallel_ftasks_per_script`, set `n_ftasks_per_script=n_parallel_ftasks_per_script` (meaning that there is no "internal queue" inside jobs)
    * If  we are under the max job number, return.
* _**Sanity check: up to this point, we never introduced "internal queues".**_
* Branch N+2 (if branch N+1 failed)
    * Set `n_parallel_ftasks_per_script` by aiming for max cpu/mem (the same as in branch 2).
    * Given `n_parallel_ftasks_per_script`, set `n_ftasks_per_script` based on max job number. This will introduce "internal queues".

**Comment by tcompa** [comment]
I'll come up with an example table for the following 30 cases:
* Number of components in `[1, 10, 40, 96, 400]`.
* Task (CPUs/mem) in `[(1, "4G"), (16, "62G"), (4, "16G")]`.
* Site in `["UZH", "FMI"]`, where
```
# UZH
  target_cpus_per_job = 8
  max_cpus_per_job = 16
  target_mem_per_job = 32G
  max_mem_per_job = 62G
  target_num_jobs = 100
  max_num_jobs = 200
# FMI
  target_cpus_per_job = 48
  max_cpus_per_job = 96
  target_mem_per_job = 62G
  max_mem_per_job = 125G
  target_num_jobs = 5
  max_num_jobs = 10
```

**Comment by jluethi** [comment]
Great summary, thanks @tcompa ! And yes, this should be the goal of the heuristic :)

**Comment by tcompa** [comment]
Here is an example of the **current** table, not meant to be checked in detail.
(but it already shows some weird situations..)

```
Cluster   | cpus/task | mem/task | | #jobs | tasks/script | parallel_tasks/script | Parallelism |
cluster_0 |         1 |     4000 | |     1 |            2 |                     2 |       1.000 |
cluster_0 |         1 |     4000 | |     5 |            2 |                     2 |       1.000 |
cluster_0 |         1 |     4000 | |    20 |            2 |                     2 |       1.000 |
cluster_0 |         1 |     4000 | |    48 |            2 |                     2 |       1.000 |
cluster_0 |         1 |     4000 | |   100 |            4 |                     4 |       1.000 |
cluster_0 |        16 |    62000 | |     1 |            2 |                     2 |       1.000 |
cluster_0 |        16 |    62000 | |     5 |            2 |                     2 |       1.000 |
cluster_0 |        16 |    62000 | |    20 |            2 |                     2 |       1.000 |
cluster_0 |        16 |    62000 | |    48 |            2 |                     2 |       1.000 |
cluster_0 |        16 |    62000 | |   100 |            4 |                     0 |       0.000 |
cluster_0 |         4 |    16000 | |     1 |            2 |                     2 |       1.000 |
cluster_0 |         4 |    16000 | |     5 |            2 |                     2 |       1.000 |
cluster_0 |         4 |    16000 | |    20 |            2 |                     2 |       1.000 |
cluster_0 |         4 |    16000 | |    48 |            2 |                     2 |       1.000 |
cluster_0 |         4 |    16000 | |   100 |            4 |                     1 |       0.250 |

Cluster   | cpus/task | mem/task | | #jobs | tasks/script | parallel_tasks/script | Parallelism |
cluster_1 |         1 |     4000 | |     1 |            2 |                     2 |       1.000 |
cluster_1 |         1 |     4000 | |     5 |            2 |                     2 |       1.000 |
cluster_1 |         1 |     4000 | |     5 |            8 |                     8 |       1.000 |
cluster_1 |         1 |     4000 | |     5 |           20 |                    15 |       0.750 |
cluster_1 |         1 |     4000 | |     5 |           80 |                    15 |       0.188 |
cluster_1 |        16 |    62000 | |     1 |            2 |                     2 |       1.000 |
cluster_1 |        16 |    62000 | |     5 |            2 |                     2 |       1.000 |
cluster_1 |        16 |    62000 | |     5 |            8 |                     1 |       0.125 |
cluster_1 |        16 |    62000 | |     5 |           20 |                     1 |       0.050 |
cluster_1 |        16 |    62000 | |     5 |           80 |                     1 |       0.013 |
cluster_1 |         4 |    16000 | |     1 |            2 |                     2 |       1.000 |
cluster_1 |         4 |    16000 | |     5 |            2 |                     2 |       1.000 |
cluster_1 |         4 |    16000 | |     5 |            8 |                     3 |       0.375 |
cluster_1 |         4 |    16000 | |     5 |           20 |                     3 |       0.150 |
cluster_1 |         4 |    16000 | |     5 |           80 |                     3 |       0.037 |
```

**Comment by jluethi** [comment]
Quick glance feedback:

#jobs seems to scale as we'd expect in the beginning, but never reaching max job number. Also, tasks/script is a bit confusing (already at 2 for a single task)
parallel_tasks/script hits 0 for one of the cases, which is also weird :)

**Comment by tcompa** [comment]
There's plenty to fix, agreed (plus I am not even showing the number-of-wells column). Including cases where `n_parallel_ftasks_per_script` becomes.. zero??

This was just to check that the table structure makes sense. I will re-post after going through the new heuristics we described today.

**Comment by jluethi** [comment]
That looks much better. And the trade-offs appear to happen in the way that we'd want them.

One questions: In table 1, why do the napari-wf tasks have max 1. parallel task per script? With a target of 8 CPUs, 32 GB of memory, 2 should fit, no? [/ 4 for max cpus & RAM]

**Comment by tcompa** [comment]
> 32 GB of memory

The cluster spec currently has 31G, so that two parallel tasks do not fit

**Comment by tcompa** [comment]
This is when I modify cluster0 properties to have a target of 32GB:
```
Cluster   | Task       | cpus/task | mem/task | #tasks || #jobs | max #tasks/script | max #parallel_tasks/script | Parallelism |
cluster_0 | yoko2zarr  |         1 |     4000 |      1 ||     1 |                 8 |                          8 |       1.000 |
cluster_0 | yoko2zarr  |         1 |     4000 |     10 ||     2 |                 8 |                          8 |       1.000 |
cluster_0 | yoko2zarr  |         1 |     4000 |     40 ||     5 |                 8 |                          8 |       1.000 |
cluster_0 | yoko2zarr  |         1 |     4000 |     96 ||    12 |                 8 |                          8 |       1.000 |
cluster_0 | yoko2zarr  |         1 |     4000 |    400 ||    50 |                 8 |                          8 |       1.000 |
cluster_0 | napari-wf  |         4 |    16000 |      1 ||     1 |                 2 |                          2 |       1.000 |
cluster_0 | napari-wf  |         4 |    16000 |     10 ||     5 |                 2 |                          2 |       1.000 |
cluster_0 | napari-wf  |         4 |    16000 |     40 ||    20 |                 2 |                          2 |       1.000 |
cluster_0 | napari-wf  |         4 |    16000 |     96 ||    48 |                 2 |                          2 |       1.000 |
cluster_0 | napari-wf  |         4 |    16000 |    400 ||   134 |                 3 |                          3 |       1.000 |
cluster_0 | cellpose   |        16 |    61000 |      1 ||     1 |                 1 |                          1 |       1.000 |
cluster_0 | cellpose   |        16 |    61000 |     10 ||    10 |                 1 |                          1 |       1.000 |
cluster_0 | cellpose   |        16 |    61000 |     40 ||    40 |                 1 |                          1 |       1.000 |
cluster_0 | cellpose   |        16 |    61000 |     96 ||    96 |                 1 |                          1 |       1.000 |
cluster_0 | cellpose   |        16 |    61000 |    400 ||   200 |                 2 |                          1 |       0.500 |
cluster_1 | yoko2zarr  |         1 |     4000 |      1 ||     1 |                15 |                         15 |       1.000 |
cluster_1 | yoko2zarr  |         1 |     4000 |     10 ||     1 |                15 |                         15 |       1.000 |
cluster_1 | yoko2zarr  |         1 |     4000 |     40 ||     3 |                15 |                         15 |       1.000 |
cluster_1 | yoko2zarr  |         1 |     4000 |     96 ||     4 |                31 |                         31 |       1.000 |
cluster_1 | yoko2zarr  |         1 |     4000 |    400 ||    10 |                40 |                         31 |       0.775 |
cluster_1 | napari-wf  |         4 |    16000 |      1 ||     1 |                 3 |                          3 |       1.000 |
cluster_1 | napari-wf  |         4 |    16000 |     10 ||     4 |                 3 |                          3 |       1.000 |
cluster_1 | napari-wf  |         4 |    16000 |     40 ||     6 |                 7 |                          7 |       1.000 |
cluster_1 | napari-wf  |         4 |    16000 |     96 ||    10 |                10 |                          7 |       0.700 |
cluster_1 | napari-wf  |         4 |    16000 |    400 ||    10 |                40 |                          7 |       0.175 |
cluster_1 | cellpose   |        16 |    61000 |      1 ||     1 |                 1 |                          1 |       1.000 |
cluster_1 | cellpose   |        16 |    61000 |     10 ||     5 |                 2 |                          2 |       1.000 |
cluster_1 | cellpose   |        16 |    61000 |     40 ||    10 |                 4 |                          2 |       0.500 |
cluster_1 | cellpose   |        16 |    61000 |     96 ||    10 |                10 |                          2 |       0.200 |
cluster_1 | cellpose   |        16 |    61000 |    400 ||    10 |                40 |                          2 |       0.050 |
```

**Comment by jluethi** [comment]
Ah ok, then the heuristics are working as they should. 

We'd likely set default task requirements to something like 15 GB to fit better into that envelope :) Or lower, depending on some profiling of actual task memory usage of course.
