### ISSUE TITLE
How to re-order a `WorkflowTask` list?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#584]
(thanks @rkpasia)

GIVEN a `Workflow.task_list` of length 3, like `taskA, taskB, taskC`.
WHEN I patch the second WorkflowTask (`taskB`) and set its `order` attribute to 0
THEN The new `task_list` is correctly reordered, that is:
* The `order` values are `0,1,2`
* The first and second WorfklowTasks (`taskA` and `taskB`) have been exchanged.

**Comment by tcompa** [comment]
Another check, while we are at it:

What happens if we patch `taskB` and set `order=912312312`?
Valid behaviors:
* We raise an error (something like "order=912312312 is beyond task_list length")
* We replace 912312312 with the appropriate number, such that `taskB` becomes the last one in the list

**Comment by tcompa** [comment]
I've had second thoughts about this issue.

The current plan (see #585) is to expose the change-task-order feature as part of the PATCH endpoint for a WorfklowTask, but it's true (as @ychiucco noted) that this acts on the whole workflow. Apart from being slightly logically wrong, it also means that this endpoint returns the patched `WorkflowTask`, and not the whole `Workflow` (with the updated list).

Let's also consider a different option:

We could leave the WorkflowTask PATCH endpoint as it is, and work on the Workflow PATCH one. In `WorkflowUpdate`, we could include something like `reordered_workflow_task_id_list`, with this logic:
```
Current WFTasks list:
ID, order
1  0
4  1
9  2

Call endpoint with reordered_workflow_task_id_list=[9,4,1]

New WFTasks list:
ID, order
9  0
4  1
1  2
```

@ychiucco any comment?

---

More context:
Thinking about fractal-web, we could imagine that a certain "reorder tasks" button opens a new modal where the user can rearrange task order (with up/down arrows), and create an appropriate payload. In the end they would click "save", and modify the whole workflow.

**Comment by tcompa** [comment]
Useful reference:
* https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/ext/orderinglist.py

**Comment by tcompa** [comment]
Note that there are two possible meanings of or `order_permutation`.
Say we have
```
order, element
0      A
1      B
2      C
```
and we want to apply `order_permutation=[2,0,1]```.

If we assume that `order_permutation` is the new list of `order` attributes, then we end up with
```
order, element
0      B
1      C
2      A
```

On the other hand, if we decide that `order_permutation` means "reorder the list according to this permutation", then we end up with
```
order, element
0      C
1      A
2      B
```

If we stick with the first choice, maybe we should rename the variable to `new_orders` to be more explicit. If we stick with the second one, maybe we should use something that does not include "order" (e.g. `task_permutation`, or `task_list_permutation` or `permutation_indices`..). I think this could reduce confusion.

**Comment by ychiucco** [comment]
From out Telegram conversation:

```python
reordered_workflowtask_ids = [3, 42, 1]

# 422 failures:
# * non-unique values in reordered_workflowtask_ids
# * it is not a permutation of current IDs (includes wrong length)

for i_wftask, wftask in enumerate(db_workflow.task_list):
      db_workflow.task_list[i_wftask].order = reordered_workflowtask_ids.index(wftask.id)
```
