### ISSUE TITLE
Fix (or drop?) inconsistent project-name-uniqueness constraint

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#596]
At the moment:
* project-create endpoint returns an error if another project with the same name (and same user) already exists
* project-edit endpoint does not have such a check, and then we can have two projects with the same name.

We should either
1. Drop this constraint, and let a user have two projects with the same name, or
2. Make this constraint more robust, either in the endpoints (easy) or possibly directly in the DB (this may be cumbersome because it mixes the `user` and `project` tables, but let's check it out).

The uniqueness constraint was introduced a while ago, but at the moment I can't remember any special reason why this is 100% needed. After accumulating some experience with the CLI client, and some preliminary experience with the new web client, I'd say that addressing projects by name is not a relevant use case.

The only remaining issues that I can think of, with same-name projects, would be:
* A user creates a project twice, and then doesn't know which one was the right one.
* User A creates a project "image analysis", but later user B shares their own "image analysis" project with user A (i.e., user A is added to the ownership list of user B's project). User A ends up having two "image analysis" projects (with two different IDs, different datasets, and different workflows).

Any opinion/preference?

**Comment by jluethi** [comment]
Hmm, good discussion. I do think we should allow non-unique project names. Otherwise, there isn't a good way for users looking at their list of projects to figure out what it actually is, as you say above.

I'm not sure how exactly we'd be handling shared projects in this context tbh. I can see an argument that it wouldn't be enforced as strictly there, because the project is then labeled as `Test1 shared from Tommaso`, which is unique enough compared to `Test1`.

**Comment by tcompa** [comment]
> I'm not sure how exactly we'd be handling shared projects in this context tbh

Quick feedback:

At the moment we are aiming for multiple-users ownership, rather than "sharing". This means that user B should see (in the future) a "add user A to project 7" button, where they can add user A to one of their projects. After the addition, user A and user B would have the same role, for that project. This corresponds to some binary access control: you either do or do not have access to a project, and if you do have it then you can do anything with it.

This feature is in principle already supported, but we don't expose it anywhere (nor we ever tested it). Let's re-discuss it when appropriate.

We were not planning, up to now, a concept of "shared project" as different from a standard "project".

**Comment by tcompa** [comment]
General principle: in the web client, the user should probably never use IDs for anything (to be updated if we hit some edge case).

The "7" was just meant as an example. In the web client, the user would enter the project 7 page (by clicking on its name in the project list, rather than by knowing its ID), and then would see the "add a user to the current project" button.


> The question becomes: Do users ever see a list of projects and make a decision based on the list?

Yes, as in the case you describe below:

> The clearest case I can think about is seeing their list of projects and deciding which one to open. Unique project names are a benefit there.

Agreed, unique project names are useful in this case.


> Enforcing unique project names between users is not what we want though and handling namespace conflicts when adding ownerships does sound annoying.

Unique-project-name constraints are always per-user, meaning that users A and B can both have a project called "test". Note, however, that if user A tries to add user B to their own "test" project, this operation will fail (because user B already has another project with the same name).

**Comment by tcompa** [comment]
As of #689 (thanks @ychiucco), we now prevent the wrong behavior of a user calling project-edit and being able to rename a project with a name that already exists. This guarantees (at the endpoint level) that a user cannot have two projects with the same name.

We should then decide what to do, in general, about this constraint. Perhaps (as @mfranzon) suggests, we can move towards having a `Project.is_shared` property, and if this is set to `True` then two projects associated to a given user (and other users, in principle) may have the same name. The property would be set to `True` whenever we maker a project user_list larger than a single element.

To be discussed.

**Comment by jluethi** [comment]
Sounds good to me! :) As long as we can mark shared projects somehow, it's also less confusing that way.

We could still eventually hit a "6 users share a project called `Test` with me => which Test project is which?". But most users will name their projects something more reasonable I'd assume ;) And with the web interface, they'd then check who it was shared with to figure out which is which.

**Comment by jluethi** [comment]
Let's tackle this again when we do project sharing
