### ISSUE TITLE
Compound tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#6]
We have two cases with a create&fill structure:
* Global task that creates a zarr file with the right structure/metadata but without data (e.g. `create_zarr_structure`, or `replicate_zarr_structure`);
* Well-parallelized task that writes data (e.g. `yokogawa_to_zarr`, or `maximum_intensity_projection`).

We could find a new way to define them together.

Note that this only concerns fractal, while the tasks would remain as they are now.

**Comment by tcompa** [comment]
For the record, yesterday we re-discussed the option of a compound task, possibly made of pre/main/post phases.
This was not only related to the create/fill tasks discussed above, but also to the fact that the future `import-ome-zarr` task (ref https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/521) could be seen as the `pre` phase of most tasks.

For the moment we did not go too far into this direction, apart from noting that this "compound task" would still need to correspond to two actual tasks being run (independently from how transparent this is for the user), or it would be difficult to parallelize the second task (the "fill" one, in a create&fill scenario).

**Comment by jluethi** [comment]
Good summary. On the priority of this: Compound tasks in the way described above may offer a useful simplification from the users perspective. It's not a current priority to push those though, as we first want to build the features that would make up the useful pre-phases.
Even after that, TBD when this would come a priority

**Comment by jluethi** [comment]
Additional notes on what we could do with it were made here: https://github.com/fractal-analytics-platform/fractal-server/issues/514

**Comment by tcompa** [comment]
This issue in the current form is made obsolete by ongoing V2 work.
