### ISSUE TITLE
Rename SLURM-batching related variables

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#610]
In #582 we are introducing the following variables (taken from https://github.com/fractal-analytics-platform/fractal-server/issues/572#issuecomment-1475953654):
* `n_ftasks_per_script`: Maximum number of Fractal tasks for each submission script;
* `n_parallel_ftasks_per_script`: Maximum number of Fractal tasks to run in parallel, out of those grouped in the same submission script. Setting `n_parallel_ftasks_per_script=1` means that all tasks will be run sequentially.

These variables will often be internal-only, since they are typically set through the heuristics defined in #577. But the user will always be able to override them, by explicitly including them into the `WorkflowTask.meta` dictionary. Therefore their name should be somewhat reasonable.

Anyone has better variable names to suggest?
Maybe just `tasks_per_script` and `parallel_tasks_per_script`? Or something even more simple/clear?

(this is obviously not a major issue, but let's make sure we don't ask the user to know about `n_parallel_ftasks_per_script`..)

**Comment by jluethi** [comment]
I like the idea of simplifying this. Users probably don't think in terms of scripts here.

How about:
`tasks_per_job`
`parallel_tasks_per_job`
