### ISSUE TITLE
Include possibility to set (some?) SLURM-batching values per workflow

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#611]
At the moment the two variables `n_ftasks_per_script` and `n_parallel_ftasks_per_script` (to be renamed - see #610) can only be set for a given WorkflowTask (or for the corresponding Task).

We should re-include the possibility of setting them in the JSON configuration file (e.g. we may want to set both of them to 1, to reproduce a one-task-per-job situation).

**Comment by jluethi** [comment]
How would global `n_ftasks_per_script` and `n_parallel_ftasks_per_script` interact with the heuristic? i.e. if someone sets them globally (=> for the whole server?), that turns off the heuristic and always chooses those values?

If that's the intention, than it would be something that is only relevant for testing setups, not something we'd really want for deployments.

I could imagine that there are scenarios where one wants to run a given workflow on a production setup with both of them set to 1 for easier debugging. And then it would be easier to set it per workflow, but per task would also work (just a bit more cumbersome). But we wouldn't change the whole server to have them hard-coded.

**Comment by tcompa** [comment]
> How would global n_ftasks_per_script and n_parallel_ftasks_per_script interact with the heuristic? i.e. if someone sets them globally (=> for the whole server?), that turns off the heuristic and always chooses those values?

Yes, for each time when those values are set (be it globally or per-WorkflowTask), the heuristic is replaced by just a validation of the input values (as in: do they lead to a batching scheme which is consistent with the hard constraints? If yes, go on; if not, raise an error).

What we do not currently support is a way to "unset" those values (i.e. setting them to `None`); it may be that it is possible to do it (on a per-WorkflowTask level), but I would rather not support this behavior, because of

> it would be something that is only relevant for testing setups, not something we'd really want for deployments.

**Comment by tcompa** [comment]
> I could imagine that there are scenarios where one wants to run a given workflow on a production setup with both of them set to 1 for easier debugging. And then it would be easier to set it per workflow, but per task would also work (just a bit more cumbersome). But we wouldn't change the whole server to have them hard-coded.

OK, then let's use this issue to address this goal (setting per-workflow options, instead of per-workflowtask). My first take is that this would lead to too many sources for the same parameter, which is not great for clarity - but I'm of course open to this discussion.

Also note that this would mean that we introduce an additional `meta` attribute (or similar) of the Workflow or ApplyWorkflow model, which is `None` most of the times and is switched on for debugging purposes. If this is the goal, then maybe we can simply think about a broader `debug` flag for workflow execution, which in principle could be used for other goals as well.

**Comment by jluethi** [comment]
Let's see if we hit strong use cases that need this.
