### ISSUE TITLE
Update the `ApplyWorkflow.log` field also for successful worfklow runs

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#618]
For the moment we only update it when a job fails.

Let's also set this attribute when execution is complete and successful, by including the logs which are currently in `workflow.log`. Note: this log would only be available at the end of the workflow execution, when `status=done`.

Ref: https://github.com/fractal-analytics-platform/fractal-web/issues/98

**Comment by jluethi** [comment]
Sounds good. We did not have a log included originally because then the CLI status became too verbose. If we limit it to workflow.log, that is not super verbose, but still will increase the amount shown on the command line by quite a bit, right?
Or is this separate from how we do `fractal job show ID`?

**Comment by tcompa** [comment]
All the work in https://github.com/fractal-analytics-platform/fractal-server/pull/619 will end up in the following situation:
1. The env variable `FRACTAL_LOGGING_LEVEL` determines what appears in the console logs. This will be typically set to its `INFO` level (or even `WARNING`), so that all `DEBUG` logs will not appear there.
2. Loggers that have a file handler will always have a `DEBUG` level, meaning that they will write every single logging call (debug, info, warning, ...). Note that the loggers with a file handler are typically those that eventually appear in the database (e.g. in the `ApplyWorkflow.log` attribute), since they are first written to file and then read and stored in a database field.

This means we can increase the verbosity of what goes to the DB (see e.g. https://github.com/fractal-analytics-platform/fractal-server/pull/619#issuecomment-1506777473), without polluting console logs.

Note that, however, the console logs are meant to be refactored in the future - see https://github.com/fractal-analytics-platform/fractal-server/pull/619#issuecomment-1508122395
