### ISSUE TITLE
Can we request < 1 CPU per task?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#624]
See comment here: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/364

Our CPU usage for certain tasks is fairly low, i.e. below 1 CPU for a given task. If memory requirements allow, we could in theory run more tasks on a given node. i.e. if we use a node with 48 cores, we could potentially run 96 jobs in parallel on there.
The question is: Can we actually request less than 1 CPU per node?
Can we request this info from the user? => we could allow users specifying e.g. 0.5 cpu-per-task
Can we still use our srun approach when we need less than 1 CPU per task?? I have no idea here. Care to comment @tcompa ?

Our current submission goes something like this:

```
#SBATCH --ntasks=48
#SBATCH --cpus-per-task=1
#SBATCH --mem=192000M

srun --ntasks=1 --cpus-per-task=$SLURM_CPUS_PER_TASK --mem=4000MB /path/to/fractal-server-1.2.0a3/bin/python -m fractal_server.app.runner._slurm.remote --input-file /path/to/artifacts_120a3/proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_01_0__in_JALREvnPstEBdjAdrSW6GrRot5OkhTRl.pickle --output-file /path/to/.fractal/20230414_121239_proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_01_0__out_JALREvnPstEBdjAdrSW6GrRot5OkhTRl.pickle &
srun --ntasks=1 --cpus-per-task=$SLURM_CPUS_PER_TASK --mem=4000MB /path/to/fractal-server-1.2.0a3/bin/python -m fractal_server.app.runner._slurm.remote --input-file /path/to/artifacts_120a3/proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_02_0__in_hi6WwmwYgbj407tPkxARmeRgM1mh79Ph.pickle --output-file /path/to/.fractal/20230414_121239_proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_02_0__out_hi6WwmwYgbj407tPkxARmeRgM1mh79Ph.pickle &
srun --ntasks=1 --cpus-per-task=$SLURM_CPUS_PER_TASK --mem=4000MB /path/to/fractal-server-1.2.0a3/bin/python -m fractal_server.app.runner._slurm.remote --input-file /path/to/artifacts_120a3/proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_03_0__in_Y4zTHAp43tPxULwaoEGg85BBE2TCf0cg.pickle --output-file /path/to/.fractal/20230414_121239_proj_0000004_wf_0000004_job_0000004/3_par_RS211203225952_mip_zarr_A_03_0__out_Y4zTHAp43tPxULwaoEGg85BBE2TCf0cg.pickle &
....

```

So I don't see how we'd request fractional cpus per task here.

**Comment by jluethi** [comment]
Follow-up: This becomes less relevant for large real-world examples at the TB scale, where we seem to be using CPUs at a fairly high level :)

**Comment by tcompa** [comment]
>  The question is: Can we actually request less than 1 CPU per node?

My understanding is that this is not possible with our current choice of using `srun`. To achieve this, we would have to resort to _yet another_ tool, e.g. GNU parallel. Then we would fully decouple the SLURM-job requirement from the number of tasks.

I'm not in favor of introducing such additional complexity, especially in view of the last comment by Joel.

I propose we close this issue, or otherwise we should discuss it further to decide about how we could pursue this work.
