### ISSUE TITLE
Deleting Workflow Task properties after adding them

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#629]
Currently, I can not delete a property anymore after I confirmed adding it. There is a trash button, but it's dimmed and clicking on it doesn't do anything.
Users should be able to delete properties again, because properties can be added in error and Fractal server is strict to not allow unexpected properties when running tasks.

<img width="712" alt="Screenshot 2023-04-17 at 13 59 27" src="https://user-images.githubusercontent.com/18033446/232477877-88a62ed1-c2ec-41fd-8ac1-82d7764fc364.png">

**Comment by tcompa** [comment]
Side comment: the whole work on JSON Schemas makes this issue a bit less urgent to solve, as it will mostly matter for tasks that come without an arguments schema.

**Comment by tcompa** [comment]
As of #758, fractal-server now allows deleting an argument via the PATCH-WorkflowTask endpoint.

If the current `WorkflowTask.args` is `{"a": 1, "b": 2}`, then sending a PATCH request with `args={"a": 3}` will lead to a new `WorkflowTask.args = {"a":3}` (without `b`).

This behavior is available for all arguments that do not have a default value in the task args_schema (or for all arguments of tasks without args_schema). If a task has an args_schema, and `b` has a default, then with the same procedure as above we'll end up with `args = {"a": 3, "b": DEFAULT_OF_B}`.

It is not possible to fully remove an argument if it has a default value in the schema, and we are not planning to introduce this feature for the moment.
