### ISSUE TITLE
More flexible `allow_origins`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#645]
Since we'll have an http server in front of fractal-web, which then communicates with the fractal-server instance, https://github.com/fractal-analytics-platform/fractal-server/issues/634 is not enough and we have to allow more origins (that is, either `"*"`, or something defined in a `FRACTAL_ALLOW_ORIGINS` variable).

**Comment by jluethi** [comment]
For security reasons, a defined set of origins will likely be preferable.
