### ISSUE TITLE
Support connecting to postgres via UNIX socket

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#650]
See for instance:
* https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#unix-domain-connections

Current code does not support this, since we have
```python
    @property
    def DATABASE_URL(self):
        if self.DB_ENGINE == "sqlite":
            if not self.SQLITE_PATH:
                raise ValueError("SQLITE_PATH path cannot be None")
            sqlite_path = (
                abspath(self.SQLITE_PATH)
                if self.SQLITE_PATH
                else self.SQLITE_PATH
            )
            return f"sqlite+aiosqlite:///{sqlite_path}"
        elif "postgres":
            pg_uri = (
                "postgresql+asyncpg://"
                f"{self.POSTGRES_USER}:{self.POSTGRES_PASSWORD}"
                f"@{self.POSTGRES_SERVER}:{self.POSTGRES_PORT}"
                f"/{self.POSTGRES_DB}"
            )
            return pg_uri
```

**Comment by tcompa** [comment]
Also, as a future reference:
* https://dr-knz.net/local-overheads-in-postgresql-and-cockroachdb.html

**Comment by tcompa** [comment]
As soon as #657 is merged and released, the new variable (note that it was renamed from `POSTGRES_SERVER` to `POSTGRES_HOST`) can be used for either an ip address or a UNIX socket.
E.g. we tested it by setting
```
POSTGRES_HOST="/var/run/postgresql"
```
and the db connection worked.

**Comment by jluethi** [comment]
Thank @tcompa , will do!

**Comment by tcompa** [comment]
> I tried it with fractal-server-1.2.4a0 and got fractalctl set-db to run.

Thanks. I'll then turn 1.2.4a0 into 1.2.4 right away.
