### ISSUE TITLE
Review job table to allow deleting datasets or workflows

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#667]
A job is in relationship with
* a project
* a workflow
* one or two datasets

Expected behaviors:
1. Removing a project removes all associated jobs (ref #633, in progress with #666)
2. Removing a workflow removes all associated jobs - to be implemented.
3. Removing a dataset removes all associated jobs - to be implemented.

Note that 2 and 3 can be counterintuitive, let's make sure we are OK with them. If not, we can find a workaround.

Current situation is not acceptable, because removing a dataset would lead to a broken state in which the job table has rows with foreign keys pointing to non-existing datasets.

**Comment by tcompa** [comment]
Side comment: we need a much more thorough testing for all DELETE endpoints, especially in the presence of relationships.

**Comment by jluethi** [comment]
> Note that 2 and 3 can be counterintuitive, let's make sure we are OK with them. If not, we can find a workaround.

That is a very interesting question. My gut feeling is that deleting a project should remove all its contents. But would a user expect that the job log disappears after they delete a dataset? Probably not?

May require a bit more thinking on this for workflow & dataset deletion.

**Comment by jluethi** [comment]
The broader question: How strictly & how long should the server keep track of all the things it ran?

I can see an argument that we'd always like to go through the server history to see what was actually run. This is probably a broader feature than the discussion here though. My main history priority would be storing history in the OME-Zarr file itself (see discussion here: https://github.com/fractal-analytics-platform/fractal-server/issues/506).

In that spirit, I think I'd be fine if we are deleting associated jobs upon dataset or workflow deletion for the time being. And, if after the history work we realize we also want the server to store logs even upon deletion of projects, datasets, workflows or a subset thereof, we'd specifically design that feature and change this again (i.e. instead of deletion, it just marks these object with a flag so the user doesn't actively see them anymore). Whether we will add such a feature is unclear to me as of now though.

**Comment by tcompa** [comment]
EDIT:
"how this thing should work" means "how this thing should work, if we decide that (some) jobs should be persistently stored"

**Comment by tcompa** [comment]
(note: the latest commit referencing to this issue, [aedbf38](https://github.com/fractal-analytics-platform/fractal-server/commit/aedbf389a9032419a385f8896e23cbd89e3c6cee), was a typo in the commit message)

**Comment by jluethi** [comment]
Just following up on the need for Job Archives:
A thing that gets confusing to users sometimes is why they can't delete datasets once they have run a job on them. That's mostly because we don't show the error in the interface (see https://github.com/fractal-analytics-platform/fractal-web/issues/250). But even then, would be useful if that eventually becomes possible.

**Comment by tcompa** [comment]
We had a brainstorming with @ychiucco and @mfranzon, and came up with a plan for an experimental implementation.
We can discuss it further, but in the meanwhile here is the corresponding to-do list:

1. Add `applyworkflow.input_dataset_dump` and `applyworkflow.output_dataset_dump` columns, and fill them within the apply endpoint (in the same way as we already do for `workflow_dump`)
2. Add new `applyworkflow.archived` boolean column, `False` by default
3. Create new `archived_applyworkflow` table
    * Only one FK, pointing to `project_id` (needed e.g. for access control, but also for project listing)
    * The `project_id` FK is such that a project deletion also triggers cascade deletion of the related `archived_job` rows
    * All the “dump” columns from the FKs that we remove (I/O datasets and workflow)
4. Add new `GET /api/v1/project/{project_id}/job/{job_id}/archive` endpoint
    * Check that `job.archived` is `False`, otherwise fail 422 (or do something smart)
    * Set `job.archived = True`
    * Create new `archived_job` row, with the same `project_id` FK and a copy of all the “dump” columns
5. Add new `DELETE /api/v1/project/{project_id}/job/{job_id}`  endpoint
    * If `job.archived` is `False` -> do something (either raise 422, or call archive first and then delete job)
6. Add new `GET /api/v1/project/{project_id}/archived_job/` endpoint
7. Add new `GET /api/v1/project/{project_id}/archived_job/{archived_job_id}` endpoint
8. In project/dataset/workflow DELETE endpoints, detect when you would delete a job, and act in a specific way. Options:
    * Raise an informative error (please first archive jobs 1,2,3)
    * Automatically archive&delete the job

**Comment by jluethi** [comment]
Looks promising! 

In the options on what to do during deletion, I think they should basically always be "Automatically archive&delete the job" where possible.

The only thing I'm not fully sure yet is the complete deletion of the job records on project deletion. It makes sense to allow this way of cleaning up (and we may then want to add an additional warning text in the web interface to make the user aware that everything gets deleted that way).
But we may need to keep some record for accounting purposes of number of jobs run for a given user, their runtimes and some of the details. At that point, maybe the user has no more access to the job, but could it be kept such that admins still see them and accounting can still track them?

**Comment by tcompa** [comment]
While reviewing #906 with @ychiucco and @mfranzon, we came up with an alternative proposal (as compared to https://github.com/fractal-analytics-platform/fractal-server/issues/667#issuecomment-1766051376) which looks promising. We are now exploring that option as well.

The main point is that we may remove several ApplyWorkflow FKs (or at least make them optional): workflow_id, input_dataset_id, output_dataset_id. This is true for at least two reasons:
1. In principle we can always use the new "dump" columns, as defined in #906.
2. Even more important: the `submit_workflow` function already includes these three IDs as input parameters, so that we never really use e.g. `ApplyWorkflow.workflow_id`.

Thus the new TODO would be:
- [ ] Make the three FKs of ApplyWorkflow table nullable (while keeping `project_id` as required)
- [ ] Include `{input,output}_dataset_dump` columns (same as `workflow_dump`)
- [ ] Remove checks from delete-dataset and delete-workflow endpoints
- [ ] Sanity check: when deleting a dataset or workflow, the FKs of the corresponding jobs are automatically set to null (via cascade option)
