### ISSUE TITLE
Task collection: package-extras not installed

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#670]
I made the scMultipleX task installable by Fractal. It has an optional dependency on fractal-tasks-core. The following is in setup.cfg:
```
[options.extras_require]
fractal = 
    fractal-tasks-core >=0.9.4
```

Given that it's in a repo that's currently still private, I want to collect it via:
`fractal task collect /path/to/scmultiplex-version-details.whl --package-extras fractal`

I created the wheel with `python -m build` in the package. Then ran the command above. This successfully collects the task, but does not install the extras package.

Manually just installing the package with the extras as in `pip install ".[fractal]"` in the package folder does work though.

Do I need to do anything extra when building the wheel? Or is there a bug when using the `--package-extras fractal` option (with wheel-based collection)?
The task collection log doesn't show any warnings or errors.

**Comment by jluethi** [comment]
It's all using this branch of the scMultipleX package and the steps described in that README: https://github.com/fmi-basel/gliberal-scMultipleX/tree/fractal-task-installation/src/scmultiplex/fractal

**Comment by tcompa** [comment]
I confirm that local-package installation is currently not considering extras:

```python
    if task_pkg.is_local_package:
        pip_install_str = task_pkg.package_path.as_posix()  # type: ignore
    else:
        version_string = f"=={task_pkg.version}" if task_pkg.version else ""
        extras = (
            f"[{task_pkg.package_extras}]" if task_pkg.package_extras else ""
        )
        pip_install_str = f"{task_pkg.package}{extras}{version_string}"
```


Have you already checked whether
```
pip install /path/to/file.whl[fractal]
```
works as intended? If so, the fix to fractal-server should be trivial (just preparing the correct `pip_install_str`).

**Comment by jluethi** [comment]
Yes, I can confirm that 

```
pip install /path/to/file.whl[fractal]
```

works as intended, installing the fractal extra options as well. Would be nice to add this.
