### ISSUE TITLE
Remove pin `typing-extensions = "4.5.0"`

### ISSUE THREAD

**Issue by ychiucco** [fractal-analytics-platform/fractal-server#706]
Introduced here https://github.com/fractal-analytics-platform/fractal-server/pull/705/commits/d624f76ee0868e9b8302f3ffcb40066e528012e7 because of this https://github.com/pydantic/pydantic/issues/5821.

**Comment by tcompa** [comment]
This was fast: https://docs.pydantic.dev/latest/changelog/#v1108-2023-05-23.
@ychiucco, could you upgrade pydantic and unpin typing-extensions? Thanks!
