### ISSUE TITLE
How to handle import/export of workflows with custom tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#729]
Branching from #702:

> > Define what behaviors depend on the task being standard or not (e.g. import/export of a workflow is not guaranteed to work for non-standard tasks - we should at least raise a warning, or maybe even fail).
> > EDIT: depending on the choice made in https://github.com/fractal-analytics-platform/fractal-server/issues/721, we may not have to raise any warning/error.
> 
> As of 01f7486, we have a warning when exporting a workflow which includes workflow tasks. This will be enough for the current issue, and I'm opening a new issue to decide whether this should be simply a server-side warning or it should actually affect the server response during workflow import/export.

**Comment by jluethi** [comment]
At this stage, displaying a user warning when exporting from Fractal web listing the custom tasks that are used could optionally be done. Not very critical for the time being though.

**Comment by tcompa** [comment]
> At this stage, displaying a user warning when exporting from Fractal web listing the custom tasks that are used could optionally be done. Not very critical for the time being though.

Agreed.
Also note that warnings are to be handled client-side (e.g. in fractal-web), cause a warning in the endpoint will only be visible in the fractal-server logs.
