### ISSUE TITLE
Review task collection after task-package refactor

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#735]
Ref https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/378.
This won't probably require any change (as per https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/378#issuecomment-1578058244), but we should check that we never rely on the tasks being in the main tasks package.

As for the manifest, for the moment we are not moving it away from the main package.

**Comment by jluethi** [comment]
I would expect this to work. For both the scMultipleX as well as the faim-hcs package (see e.g. here: https://github.com/jluethi/faim-hcs/tree/fractal-roi-tables/src/faim_hcs), I am using task collection from wheels with this package structure and it's working fine. 

The only thing I stumbled over a few times was making sure all the files were actually included in the wheel, i.e. adding 

```
[options.package_data]
faim_hcs = __FRACTAL_MANIFEST__.json
```

to the setup.cfg to make sure the manifest was packages and adding an `__init__.py` to the new subfolder.
