### ISSUE TITLE
Review normalization of package and extra names

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#736]
Ref: https://packaging.python.org/en/latest/specifications/name-normalization:
```python
import re

def normalize(name):
    return re.sub(r"[-_.]+", "-", name).lower()
```

Note that this is not a big deal on fractal-server side, but it is creating some issues in the fractal-tasks-core for defining extras (ref https://github.com/python-poetry/poetry/issues/6819 and https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/390#issuecomment-1578188213). Thus it's better to also make the right decision on the fractal-server side.

**Comment by jluethi** [comment]
This came up here:
https://github.com/fmi-basel/cellpose_2d3d_merging/blob/main/pyproject.toml

With the packaging
```
# Project metadata (see https://peps.python.org/pep-0621)
[project]
name = "cellpose-2D3D-merging"
version = "0.0.1"
description = "Cellpose based segmentation combining 2D and 3D segmentation"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "Franziska Moos", email = "franziska.moos@fmi.ch" },
]

# Required Python version and dependencies
requires-python = ">=3.8"
dependencies = [
    "fractal-tasks-core==0.14.1",
    "anndata",
    "cellpose",
    "dask",
    "numpy",
    "pandas",
    "zarr",
    "pydantic",
    "scikit-image==0.20.0",
]

# Optional dependencies (e.g. for `pip install -e ".[dev]"`, see
# https://peps.python.org/pep-0621/#dependencies-optional-dependencies)
[project.optional-dependencies]
dev = ["devtools", "pytest", "requests", "build", "jsonschema"]

# Build options (see https://peps.python.org/pep-0517)
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["cellpose_2d3d_merging"]

# Always include the __FRACTAL_MANIFEST__.json file in the package
[tool.setuptools.package-data]
"*" = ["__FRACTAL_MANIFEST__.json"]
```

**Comment by tcompa** [comment]
Quick fix: do not use capital letters in project name, that is go from
```toml
[project]
name = "cellpose-2D3D-merging"
...
```
to
```toml
[project]
name = "cellpose-2d3d-merging"
...
```

---

Meanwhile we'll improve on this, based on https://packaging.python.org/en/latest/specifications/pyproject-toml/#name ("Tools SHOULD [normalize](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization) this name, as soon as it is read for internal consistency.") and https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization (which defines how to normalize a name).

**Comment by enricotagliavini** [comment]
Hello @tcompa , we did switch to lower case, but we still got the same error and I see the folder created for the task virtualenv is still with the upper case letters. We are sure we used the correct wheel (we removed the previous one and the timestamp in the web interface is also from today). There might be more places affected than just the project name.

We are now trying to remove the upper case letters from all the occurrences of the module name.

**Comment by enricotagliavini** [comment]
I think we found the mistake on our side actually. But we anyway removed any occurrence of upper case letters from everywhere. Thank you.

**Comment by tcompa** [comment]
> I think we found the mistake on our side actually. But we anyway removed any occurrence of upper case letters from everywhere. Thank you.

Good to hear.
For the record, I had just created https://github.com/tcompa/example-fractal-server-issue-736. This package can be successfully collected, as in:
![image](https://github.com/fractal-analytics-platform/fractal-server/assets/3862206/38d31ed3-8295-445c-a848-79b194dcf027)

A slight variation, where I just change the `name` in `pyproject.toml` into something with capital letters (e.g. `package-NAME`) leads to a failure in task collection.
