### ISSUE TITLE
Review how to back-up postgres DB

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#773]
Ref https://www.postgresql.org/docs/current/app-pgdump.html

**Comment by tcompa** [comment]
Note: see [this other comment](https://github.com/fractal-analytics-platform/fractal-server/issues/774#issuecomment-1614233382 ) for other examples of relevant postgres commands.

---

Say we are using the `fractal` postgres DB in a fractal-server instance, and we created some objects. The goal is then to create a backup and restore it (to a different DB, for instance).

We can take a dump of the current DB via
```
pg_dump fractal --file=dump_fractal.sql
```

We then create the new DB, where we will restore the one we backed up:
```
$ psql -d postgres
psql (14.8 (Ubuntu 14.8-0ubuntu0.22.04.1))
Type "help" for help.

postgres=# create database fractal_new;
CREATE DATABASE
postgres=# \l
                                     List of databases
       Name       |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
------------------+----------+----------+-------------+-------------+-----------------------
 fractal          | tommaso  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 fractal_new      | tommaso  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres         | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0        | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
                  |          |          |             |             | postgres=CTc/postgres
 template1        | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
                  |          |          |             |             | postgres=CTc/postgres
(5 rows)
```
and finally recreate it as in
```
psql -d fractal_new -f dump_fractal.sql
```

If we now modify the fractal-server `POSTGRES_DB` environment variable from `fractal` to `fractal_new`, and restart fractal-server, we have a working instance with all data in there.

**Comment by tcompa** [comment]
The previous comment is essentially all we need for a backup/restore operation.
There's room for improvement, e.g.
* Create compressed files
* Restore the status of a DB without switching to a new one.

but the main procedure will remain the same: perform regular backups, and make sure that you have at least one way to go back to one of those.

I'd say: let's set up a script and a cron job to back up things regularly (in progress), and then a bit later (maybe a week, or the time needed for a few users to use Fractal) let's have a scheduled downtime in which we try to go back to a specific past backup, and then again to the latest one. We will also immediately notice whether sql scripts are too heavy, and then we'll decide whether we should include compression.


 we can move on, and then review after a bit of experience with at least one  (e.g. how large will a "typical" file be? if large, let's use compressed files (if it requires shutting down fractal server for a small amount of time, that's not such a big deal - for the moment).



Note that there are for sure other options (that is, without creating a new DB), but for the moment the clean one is clearly sufficient. We would care about this

**Comment by jluethi** [comment]
Sounds great! I tested this at UZH and FMI for the export part, working well in both. I have not tested the import & state restoration part yet though. But already very useful that we have this! :)

And yes, let's review with some databases of the real size :)

**Comment by tcompa** [comment]
Just for testing, I'm setting up the following at UZH

1. A simple script `/somewhere/backup_postgres_db.sh` like:
```bash
#!/bin/bash

BACKUP_DATABASENAME=$1
BACKUP_TIMESTAMP=`date +%Y%m%d_%H%M%S`
BACKUP_FILE=/var/backups/fractal/${BACKUP_TIMESTAMP}_${BACKUP_DATABASENAME}.gz
pg_dump $BACKUP_DATABASENAME | gzip -c > $BACKUP_FILE
```

2. A backup folder where the current user has writing access
```
$ ls -la /var/backups/fractal/
total 8
drwxrwxrwx 2 root root 4096 Jun 30 12:20 .
drwxr-xr-x 3 root root 4096 Jun 30 11:52 ..
```
3. A crontab entry like

```
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command
55 23 * * * /somewhere/backup_postgres_db.sh DBNAME
```
where `DBNAME` is to be replaced with the postgresql DB name.

After one of these backup files is created, we can always decompress it as in
```
$ gzip --decompress --keep /var/backups/fractal/20230630_122509_fractal2.gz

$ ls -l /var/backups/fractal/
total 324
-rw-r--r-- 1 fractal fractal 284843 Jun 30 12:25 20230630_122509_fractal2
-rw-r--r-- 1 fractal fractal  42037 Jun 30 12:25 20230630_122509_fractal2.gz
```

**Comment by tcompa** [comment]
This preliminary version is currently in-place at UZH, and no further action is needed. There are multiple possible improvements, but we can re-evaluate once we gain some more experience (e.g. the first time we have to do a migration). Closing for now.
