### ISSUE TITLE
run fractal-server separately from slurm master

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#78]
after #77, #10 are solved, it is going to be possible to run fractal-server on a separate machine wrt slurm master node, on condition that

* [ ] network filesystem be mounted
* [ ] slurm master node be reachable via ssh
* [ ] fractal-server be reachable form slurm nodes (workers' hartbeat need to reach Parsl Interchange)

**Comment by tcompa** [comment]
Currently deprecated, as we moved towards the sudo approach - see recent comments in https://github.com/fractal-analytics-platform/fractal-server/issues/10.
