### ISSUE TITLE
Store (rich and machine-readable) history data as a Dataset attribute

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#793]
Let's start a fresh issue, based on last week meetings. This will have to be connected to:
* #506 
* #507 
* #508 
* #509

Note: This is meant to roughly represent a log of our discussions, and not yet an implementation plan.

1. fractal-server stores a rich history as a dataset attribute (either `Dataset.meta["history"]` or `Dataset.history`)
2. Every time the partial/full execution of a workflow ends (successfully or because some task failed), all tasks that ended successfully are appended to the history. The tasks that did not run are obviously not included. TBD what to do with the failed tasks.
NOTE: History is compiled by the runner, written to a file in the job folder and merged into the dataset (in the DB) at the end of execution.
4. The object that gets appended to history is as close as possible to a full dump of the corresponding `WorkflowTask` data. For sure it has to include the `Task` object (either in its entirety, or with only a subset of its attributes - e.g. we may want to strip away the `command` one) and the `WorkflowTask.args` and `WorkflowTask.meta` attributes.
5. History should have a similar structure to an exported `Worklow`, but there may be some relevant differences. For instance we may want to include database IDs, if we plan to use the history as a source for a more granular "show me the dataset processing status" feature in fractal-web.
6. High-level: we are also planning to include this history data (either identical or similar - TBD) directly into the OME-Zarrs, somewhere in the metadata.
7. High-level comment: using the same history data for multiple goals (provenance, reproducibility, and status monitoring) and in multiple places (both in the DB and in the OME-Zarr's) will likely require some trade-offs. Provenance would require us to include as much information as possible (e.g. including the full executable command), which we likely don't want to include in OME-Zarrs. Status monitoring requires DB-specific information that also won't make sense as part of a OME-Zarr history. Reproducibility would require the equivalent of an exported `Workflow`, which typically doesn't need DB- or instance-specific details.

**Comment by jluethi** [comment]
> 5. High-level: we are also planning to include this history data (either identical or similar - TBD) directly into the OME-Zarrs, somewhere in the metadata.

When would this be written? Preferably whenever a task actually finishes, such that the OME-Zarr history is always as up-to-date as possible.
Given that a currently being processed OME-Zarr can anyway be a bit weird (i.e. contain metadata but partially missing data => potentially couldn't open in a viewer), we can also go with "whenever the workflow fails or ends", as long as that covers all ending scenarios (i.e. history also gets written after an out of memory error).

Who actually writes to the Zarr file? Needs to be something running as the user on the cluster. So either something that happens at the end of every task or e.g. a plate-level task that writes all history to all OME-Zarr files (i.e. every OME-Zarr file in a plate, meaning every individual well image) can probably have its own history.

> 6. High-level comment: using the same history data for multiple goals (provenance, reproducibility, and status monitoring) and in multiple places (both in the DB and in the OME-Zarr's) will likely require some trade-offs. 

Good point! I'm not sure if it will make sense to have the same trade-offs everywhere or whether we should vary them.
If we do vary them, I'd say the database version of history favors status monitoring (& provenance?), the OME-Zarr history favors reproducibility (& provenance?). Not sure about where provenance matters most tbh. But I'd be ok for example if the way to "reproduce" the workflow that create a Zarr file was only/best possible based on that on-disk Zarr file, not a database representation of it.

**Comment by tcompa** [comment]
Brief comment from a discussion with @jluethi:
Instead of having separate `history` and `status`, it's probably better to have a rich ground-truth attribute (e.g. `history`) and different endpoints that can extract what is relevant from it (e.g. `/dataset/{dataset_id}/export_reproducible_history` and `/dataset/{dataset_id}/get_workflowtask_statuses`).

More on this later.

**Comment by tcompa** [comment]
Here are more specific details on how we are implementing things, based on discussions with @mfranzon.
CAVEAT: both this comment and PR #803 are in-progress, more on this later.

---

For the moment we will not touch `Dataset.meta["history"]`, but we will rather work on `Dataset.meta["history_next"]`. We can make a full switch once we are happy with the result.

The description below includes:

0. History structure
1. Writing the history (which will need to happen in at least two modules)
2. Extracting a reproducible workflow from a Dataset history
3. Extracting the status of WorkflowTask's from a Dataset history

While it does not include

4. Writing the history into the OME-Zarr
5. Adding constraints on execution (ref new issue #805)

----

# 0. History structure

The new history will be a list of WorkflowTask-specific items, each one related to a WorkflowTask that either went through or failed.
Each item will include the following information:
* A dump of the whole WorkflowTask DB entry, including its first-level fields (`id`, `meta`, `args`, ..) and nested relationships (`task`).
* Information about status (for the moment this is just a `done/failed` string).
* A dictionary with information on the parallelization: `parallelization_level` (even though it's already present in WorkflowTask.meta, but it's handy to have it there) and `component_list` (which can be `None`, for non-parallel tasks).

These three pieces of information would be encoded in a dictionary, with keys like `workflowtask`, `status` and `parallelization`.

# 1. Writing the history

The history is written to two places, and from two different modules.

Places where the history is written:
* After job execution (independently on the job success status), history is written to `Dataset.meta["history_next"]`, in the DB. This history is meant to be permanent.
* During execution of a job, the history of _that specific job_ is also written to disk in `job.working_dir / METADATA_FILE`. This file only includes entries for the tasks (of this job) that ran through successfully. This history files are meant to be useful only during job execution.

History is written from two different modules:
* The function `fractal_server.app.runner._common.execute_multiple_tasks` is the one that loops over `Workflow.task_list` (or a sublist). Each time a task completes successfully, its new metadata are written to `job.working_dir / METADATA_FILE` (see diagram in https://github.com/fractal-analytics-platform/fractal-server/issues/785#issuecomment-1625406645). Also history is updated in this file (this is already the case for the legacy `history` key, and the same should hold for the new `history_next` key).
* When a job runs through (until the last WorkflowTask that was meant to be executed), the call to `process_workflow` completes and we are back in `fractal_server.app.runner.submit_workflow`. We are already writing the output of `process_workflow` into `output_dataset.meta` and committing it into the DB, so that this use case should require no special change.
* When a job fails at a given task, we are also back in (a different branch of) `fractal_server.app.runner.submit_workflow`. In this case, we need to modify the history by appending a new item (with `status="failed"`), and then we need to update the DB entry. This is currently missing.

# 2. Extracting a reproducible workflow from a Dataset history

Pseudo-code

```python
@router.post(
    "/project/{project_id}/dataset/{dataset_id}/export_history?workflow_id={workflow_id}",
    response_model=WorkflowExport,
    )
async def export_reproducible_history(
    project_id: int,
    dataset_id: int
    workflow_id: int
    user: User = Depends(current_active_user),
    db: AsyncSession = Depends(get_db),
) -> Optional[WorkflowExport]:
    """
    Extract a reproducible workflow from the dataset history
    """

    # Get the dataset DB entry
    dataset = get_dataset_check_owner(...)

    # Check whethere there exists a job `job` such that
    # 1. `job.workflow_id == workflow_id`
    # 2. `job.output_dataset_id == dataset_id`
    # 3. `job.status` is either submitted or running
    job = ApplyWorkflow.get(...)

    # If such a job exists, then this endpoint should fail (what would "extract
    # a reproducible workflow" mean when execution is in-progress?)
    if job is not None:
        # fail with 422 error

    # It such a job does not exist, continue with the endpoint. Note that this
    # means that the history in the DB is up-to-date.

    # Read history from DB
    history_next = dataset.meta["history_next"]

    # Construct reproducible workflow
    task_list = []
    for history_item in history_next:
        wftask = history_item["workflowtask"]
        status = history_item["status"]
        if status == "done":
            task_list.append(WorkflowTaskExport(**wftask)
        # Maybe we can do as in the workflow/export, and print a warning if the
        # workflow includes any custom (AKA non-common) tasks. However this is
        # a bit irrelevant, since the log is only visible in the fractal-server
        # logs
        # if wftask.task.owner is not None:
        #     ...

    workflow = WorkflowExport(task_list=task_list)
    return workflow
```


# 3. Extracting the status of WorkflowTask's from a Dataset history

WIP

# Examples

WIP

**Comment by tcompa** [comment]
(the comment above is now complete, even if it's still a work-in-progress version which may change during implementation)

**Comment by tcompa** [comment]
A small update to the "2. Extracting a reproducible workflow from a Dataset history" section in https://github.com/fractal-analytics-platform/fractal-server/issues/793#issuecomment-1648043804: I think the endpoint should not depend on `workflow_id`, since the reproducible history of a given dataset should not be related to a specific workflow.

### Example
Workflow 1 acts on dataset A
Workflow 2 acts on dataset A
The reproducible history of dataset A should include both workflows 1 and 2.
