### ISSUE TITLE
In `ApplyWorkflow`, store a copy of the `Workflow` at the time of submission

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#794]
This is because the workflow may change during execution.

**Comment by jluethi** [comment]
i.e. store an equivalent of the workflow download, containing at least all args, meta & versions.

**Comment by tcompa** [comment]
Closed with #804 

> i.e. store an equivalent of the workflow download, containing at least all args, meta & versions.

This field is meant to be an internal information (akin to #667), and not something the user should rely on for some action (like reproducing a job), so we went with a full dump of the workflow.
This solution obviously include all information that you mentioned above, but it does not provide a ready-to-import workflow; we can set up an additional endpoint, if needed, to extract this information.
