### ISSUE TITLE
Handle executors in v1.x

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#82]
executor is a configuration detail of the single installation of fractal server and as such should not be part of the task model.

cc @tcompa

**Comment by jacopo-exact** [comment]
executor becomes a parameter in the workflow, default if not provided

**Comment by tcompa** [comment]
> executor becomes a parameter in the workflow, default if not provided

Quick reminder: executor**s** can be attached to a workflow (*), but we want the possibility of giving a specific executor to each task.


(*) Side comment:
We could also envision global executors shared by all workflows. This would be the logical way to go, if we were addressing SLURM directly, but with parsl in the middle it may mess with prioritization of jobs. Anyway, this discussion does not belong to the current issue.
