### ISSUE TITLE
Is `POSTGRES_PASSWORD` optional or required?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#841]
The line
```
                POSTGRES_PASSWORD: str
```
in `config.py` (in the `check` method) suggests it should be required. Is it true?

**Comment by mfranzon** [comment]
Yes, it is required for Postgres container image

**Comment by ychiucco** [comment]
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by ychiucco** [comment]
To do without `POSTGRES_PASSWORD`, the database must have "trusted" connection allowed:

`docker run -e POSTGRES_HOST_AUTH_METHOD=trust -d postgres`

**Comment by tcompa** [comment]
My first question: are we actually catching the correct Pydantic errors if POSTGRES_PASSWORD is not there?
Answer: no!

- [ ] First reason: none of the `migrations/env.py` branches for online/offline migrations do call the `settings.check()` -> This should be done in both
- [ ] Second reason, it seems that `StrictSetting` definition is just wrong and must be fixed. Note that the following script runs through with no error (and it does not set `s2.PATH`)`:
```python
from pydantic import BaseSettings
from typing import Literal
from pydantic import Field
from devtools import debug


class StrictSettings(BaseSettings):
    DB: str = Field()
    if DB == "sqlite":
        PATH: str = "DEFAULT"


s1 = StrictSettings(DB="asd")
debug(s1)
s2 = StrictSettings(DB="sqlite")
debug(s2)
```

---

Once these points are cleared, we can eventually decide whether this pwd variable is required or optional. I think it must remain optional, because there are use cases where you don't need it (e.g. the `peer` authentication mode for local connections, which looks for a match between the machine user and the postgres user).
