### ISSUE TITLE
Update `output_dataset.meta` also when workflow execution fails

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#844]
Branching from https://github.com/fractal-analytics-platform/fractal-server/issues/842#issuecomment-1719147615 (and differently from #788):

When a workflow fails at task N, update `output_dataset.meta` to the latest valid state (that is, the output of task N-1).

Consequences of this change in different scenarios still need to be reviewed.

**Comment by jluethi** [comment]
> When a workflow fails at task N, update output_dataset.meta to the latest valid state (that is, the output of task N-1).

This seems to be a valid behavior from my perspective.

There can be some complexities depending on how exactly task N failed and what it may already have changed. But for 99% of cases, the N-1 metadata would be correct and would allow e.g. resuming workflows that failed at a late task. Also, many edge-cases will be handled by the tasks themselves through their overwrite functionality.

**Comment by tcompa** [comment]
> > When a workflow fails at task N, update output_dataset.meta to the latest valid state (that is, the output of task N-1).
> 
> This seems to be a valid behavior from my perspective.
> 
> There can be some complexities depending on how exactly task N failed and what it may already have changed. But for 99% of cases, the N-1 metadata would be correct and would allow e.g. resuming workflows that failed at a late task. Also, many edge-cases will be handled by the tasks themselves through their overwrite functionality.

Fine, I'll merge #845 and make a pre-release 1.3.6a0.
Let's test this a bit more, before actually updating the running instances to 1.3.6.
