### ISSUE TITLE
Forbid a task update that changes `meta["parallelization_level"]`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#9]
If a core task is designed to work e.g. at the well level, it means it will not work if it is parallelized over plates.
The manifest should then specify the right `parallelization_level` for each one of the core tasks, and this should not be overridden later.

**Comment by tcompa** [comment]
This `parallelization_level` parameter must be defined in the manifest, and it must not be possible to override it (this is because each task is designed to receive a specific type of `component` as input, e.g. a well, and it cannot be fully general). In practice, the `patch_task` endpoint must raise an error (or at least a warning) if we try to modify this attribute.
@ychiucco and @jacopo-exact: anything against this?

**Comment by tcompa** [comment]
The current issue concerns the previous comment, @jluethi let's perhaps continue somewhere else for a broader discussion?

In the meanwhile:
> Hmm, we also have a bit of a two-tier system with parallelization now. Initially, we were thinking that parsl parallelizes over the levels. But with all the recent ROI work, it's more that most things run on the well level, except some operations need to run on the plate level, right?
> So we should reevaluate whether this is still such a top-level option or whether tasks just either work per plate (=> preparing zarr files) or per well (most content tasks, where the task then controls whether the whole well is processed or ROIs within the well).

Note that there is still a crucial difference between sequential and parallel tasks (this was there in v0.x and is still there in v1.x). Note that "sequential" tasks may need to really be "global", which is different from a per-plate parallelization. This is clear, e.g., for the `create_ome_zarr` task, which runs at a point where plates are not even known. At the moment we are keeping the full flexibility: we allow each task to have a specific `parallelization_level`, and we only use either `well` (the typical per-well parallelization) or `None` (for global tasks like `create_ome_zarr` or others).

That said, there's obviously no problem if we decide to simplify the handling of `parallelization_level`..

**Comment by jluethi** [comment]
Sounds good to me. I think this setup is good for the time being then, we don't need to start a broader discussion about it for now

**Comment by tcompa** [comment]
Renamed the task as something that can be completed.

Notice that the whole task-update functionality needs some more thoughts (see https://github.com/fractal-analytics-platform/fractal-server/issues/192).

**Comment by tcompa** [comment]
At the moment the only edit endpoint which is part of frequent use cases is the one for the WorkflowTask. Within that endpoint, @mfranzon is adding an explicit error message for when the user tries to override `parallelization_level`. This will close the current issue.
