### ISSUE TITLE
Task collection should use ` --copies` when creating the task Python venv

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#907]
We had some discussions on this before somewhere, here's another reason on why it would be great to use ` --copies` when creating the venvs:
I cleaned up old server environments (because a machine was running out of space). That inadvertently broke the old fractal-tasks-core tasks that were still supposed to be active on the new server. Why? Because the Python in those task environments was just a link to the server Python, and that was removed during this cleanup.

What this means:
1. Don't delete old server environments for the moment
2. We really want to have the task environments being independent of the server environments, so that this doesn't happen in the future

**Comment by tcompa** [comment]
The `--copies` option is not generally reliable - as described above.

> We really want to have the task environments being independent of the server environments, so that this doesn't happen in the future

This is covered by #1575 or future follow ups.


Closing this one. Let's re-open it in more specific forms when needed.
