### ISSUE TITLE
Review libsqlite3-0 requirements

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#910]
We discovered that 3.31 (the version shipped with ubuntu 20) is not enough for fractal-server, while 3.37 does work - see discussion starting from https://github.com/fractal-analytics-platform/fractal-server/pull/906#issuecomment-1766492534.

We should:
1. Make sure that the github runners use a recent sqlite version (possibly switching to ubuntu 22, see dedicated issue)
2. Clarify this requirement in the docs, and in the sqlite-related warning that we already print

**Comment by mfranzon** [comment]
If the new version of sqlite works fine, we can remove the `batch_op` from migrations.
