### ISSUE TITLE
Expose SLURM accounts via API

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#956]
# Current status

Currently, there exists several different ways of choosing a specific SLURM account for job execution. From the more general to the more specific one:

1. The admin may set a default account in the SLURM/Fractal configuration file, which applies by default to all jobs (unless it is overridden). This looks like
```json
{
    "default_slurm_config": {
        "partition": "main",
        "cpus_per_task": 1,
        "account": "somecommonaccount"
    }
}
```
2. The user may add this information to the `WORKER_INIT` variable, as in
```python
WORKER_INIT = "#SBATCH --account=myaccount"
```
3. For a given task, a user can add a new `meta` property, with the key-value pair `account->something`.

Each one of these three options is then transformed in the same kind of line within the sbatch submission script.

# Future changes

There are multiple possible extensions of this mechanism:

4. We may add a column to the user DB table, that lists all their available slurm accounts (similar to the `slurm_user` attribute).
    * Why this is useful: this information can be used to offer a pre-filled drop-down menu in fractal-web, at the job-run stage
    * Why this is not useful: At a difference from `slurm_user`, a Fractal user should be able to freely add/remove/modify their own accounts (since this does not require any sudo privilege). But modifying a user is currently restricted to superusers, and then this wouldn't immediately work. We can still make it work, but we need to rework the permissions of the user CRUD endpoints.
5. We may include a string query parameter for the apply endpoint, named `slurm_account`, and offer the corresponding input form in fractal-web. Inference of possible values would not be available from fractal-server, but we could in principle build it within fractal-web (based on the previous values that were used by a given user).
6. Independently on how the apply-workflow endpoint receives this information (be it one of a list of user's accounts or a free-field endpoint query parameter), further changes are needed:
    * The DB model for jobs must be modified, as it should also include a `slurm_account` optional column.
    * The attribute `job.slurm_account` should then be used in the backend runner component (or neglected, for the local runner), and it should be passed as an additional argument to the `_slurm_submit_setup` function, which (if not `None`) will take priority over any existing value of `account` (e.g. the ones included through methods 1 and 3 above).
    * There will always be a chance of conflicts, if the user sets an account both via approach 2 above and any other method (1, 3, or any other future method). Note that this is already an issue in the current status. We could add a check that makes the job execution fail in the presence of multiple values for `account` (or we may verify what is the SLURM behavior in this case, as I guess that this will already be an error).

A couple of general notes:
* We will (likely) add some backend-specific information to DB model and API endpoints. This is not the first time, and it's acceptable because SLURM is our main target, and because these attributes are clearly optional. Let's keep it in mind that this approach won't scale forever, especially if we introduce a new runner.
* Within SLURM, we may be moving towards _four_ possible sources of the same information (actually five: task.meta, workflowtask.meta, job.worker_init, SLURM configuration file, and potentially one more). I'd be in favor of pruning some branch, since this situation could lead to unclear situations. Some options:
    * We start filtering some strings from worker-init (e.g. `# SBATCH --account`), and returning a 422 error from the workflow-apply endpoint in case they are present (together with a suggestion of where this should go).

Feedback is welcome.

**Comment by jluethi** [comment]
> If the account is not set, but the user's slurm_accounts list is non-empy, do something - cc @jluethi. What should we do here? Should we say e.g. that the first account in the list is always used by default?

Yes, that sounds good to me.

Is there another way that the slurm account can be set besides using the `slurm_accounts` afterwards?

What I'd expect on the web front-end:
The submit dialogue has a "slurm account" dropdown. By default, the top entry in the `slurm_accounts` list is selected.

What if there are no entries in that list? Then null is passed and no slurm account is provided?

What if it's not running on a slurm backend? Then that option isn't really relevant. But for just this, I don't think we need to make things too complex.

We could always put the slurm account & worker init parameters in an "advanced options" boxed that is not expanded by default

**Comment by jluethi** [comment]
The part above seems reasonable to no or 1 account. Thinking through some more edge-cases in the scenario that a user has multiple accounts in `slurm_accounts`

Do we want to remember which one was used last and default to that? 
Not sure if that is actually the main usage pattern.

Or default to no account to force the user to pick?
Would be very counter-intuitive if submission fails because no account was specified. But in general, accounts are optional (e.g. not currently required at UZH).

Or just also default to the top entry?
That should always work, but sometimes a user submits to the wrong account by mistake.


=> I'd probably still start with the option above, to be reevaluated for these edge-cases once we actually have actual users with multiple accounts

**Comment by tcompa** [comment]
> Expose optional selection of slurm account upon job submission (e.g. via query parameter? TBD)

While discussing with @ychiucco: let's rather proceed in the same way as for `worker_init`. We can add a new (nullable string) column to the `ApplyWorkflow` table, and include it also in the pydantic schemas. Then the apply-workflow endpoint will receive it directly from within the request body.

**Comment by tcompa** [comment]
Summary of use cases, also based on @jluethi comments above (and open to improvements after some actual usage):

1. `current_user.slurm_accounts = []`, `ApplyWorkflowCreate.slurm_account=None` --> `job.slurm_account=None`
2. `current_user.slurm_accounts = []`, `ApplyWorkflowCreate.slurm_account="a"` --> 422 error
3. `current_user.slurm_accounts = ["a", "b", "c"]`, `ApplyWorkflowCreate.slurm_account=None` --> `job.slurm_account="a"`
4. `current_user.slurm_accounts = ["a", "b", "c"]`, `ApplyWorkflowCreate.slurm_account="b"` --> `job.slurm_account="b"`
5. `current_user.slurm_accounts = ["a", "b", "c"]`, `ApplyWorkflowCreate.slurm_account="d"` --> 422 error
