### ISSUE TITLE
Handle OAuth-self-authenticated users

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#959]
cc @ychiucco

When the `associate_by_email` action (within a OAuth authentication) fails, a new user is created in the DB. This user doesn't have any of the custom Fractal attributes (e.g. `slurm_user`, or the cache directory), and then they would not be able to run a workflow on a SLURM cluster.

Apart from that, should we be more strict in what this user can do with Fractal? The current freedom we have has to do with three user attributes:
* `is_superuser`: currently required for a few specific endpoints
* `is_active`: currently required for most (all?) endpoints
* `is_verified`: currently not used, as far as I remember

If we set the self-authenticated user as non-active, they will have essentially no access to any endpoint. In this case, fractal-web should simply show a big warning page that says something on the line of "Please go and ask the admin to activate your account'.

This is a first proposal, and we can then iterate on it.

**Comment by jluethi** [comment]
is_active=False upon self sign-up sounds good to me

**Comment by tcompa** [comment]
How to proceed:

1. Introduce `current_active_verified_user` dependency
2. Use this new dependency in all endpoints under `/api/v1/`
3. Make sure that endpoints in `/auth` (especially `GET /auth/current-user/`) remain accessible to non-verified users
4. As of `/admin/` endpoints, it's not really important to ask for verification (if you are a superuser it means that another admin granted you this role, and this essentially counts as being verified) -> let's not ask for `is_verified=True` for superuser-restricted endpoints.
5. Make sure that a user who self-authenticates via OAuth (and whose email address is not yet present in the DB) is created with `is_verified=False`

Note: "verified" here corresponds to "an admin verified this user account", rather than the common "I verified my user account by clicking a link my in email I received".

**Comment by jluethi** [comment]
Good question @tcompa 

For our target deployments (within given, typically academic institutions, not accessible on the public internet), option 2 seems fair to me. We could think about also limiting task selection (as a user could collect an arbitrary package, not sure if that is at all a security concern?). But them creating projects, datasets, workflows etc. seems unproblematic and indeed a nice thing to already be able to do.

**Comment by tcompa** [comment]
As of this morning call:

Let's only prevent access to apply-workflow and collect-tasks endpoints, for non-verified users.
